In [123]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import os
import seaborn as sns
import sys
import glob
import tqdm
plt.style.use('default')
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams.update({'font.size': 22, 'legend.facecolor': 'white', 'legend.framealpha': 1, "legend.frameon": 1, "lines.linewidth": 2})

In [124]:
label_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/runs/exp_MRNA/ON0090/ON0090/label/Baeklab.070.GP3.depth5_None.twm6astrict.tsv", sep="\t")
label_df = label_df[["id", "depth", "label", "m6A_level", "5mer", "drach"]]
label_df.rename(columns = {"id": "label_id","m6A_level": "dom_label"}, inplace = True)
label_df_filtered = label_df[((label_df["dom_label"] > 0.0) & (label_df["label"] == 1)) | (label_df["label"] == 0)]
print(label_df_filtered["label"].value_counts())

label
0    18399879
1      100118
Name: count, dtype: int64

In [125]:
logsum_df = "/extdata4/baeklab/Hyeonseo/m6A/inference/inference/AIRNA-DW-v4-20240905-092858-10-177000-token_normalise_dwell_bq_npz_allmotif_pileup_psum/pileup.npz"
with np.load(logsum_df, allow_pickle=True) as data:
    logsum_df = pd.DataFrame({key: data[key] for key in data.keys()})
logsum_df = logsum_df[logsum_df["count_dom"] >= 20]
logsum_df = logsum_df.merge(label_df, on="label_id", how="inner")
print(logsum_df)

                label_id      p_sum  logsum_p_pos  logsum_1_p_pos  count_pos  \
0         NM_000016:1000   0.606511      0.000000        0.000000          0
1         NM_000016:1008   0.948786      0.000000        0.000000          0
2         NM_000016:1009   2.607620      0.000000        0.000000          0
3         NM_000016:1010   4.912612      0.000000        0.000000          0
4         NM_000016:1014   3.237954      0.000000        0.000000          0
...                  ...        ...           ...             ...        ...
15992331    NR_184306:85   1.133184      0.000000        0.000000          0
15992332    NR_184306:87   3.771550     -0.001452       -2.476578          1
15992333    NR_184306:88   2.137289      0.000000        0.000000          0
15992334    NR_184306:93  32.341377     -0.011076      -78.301079         23
15992335    NR_184306:98   4.046034      0.000000        0.000000          0

          logsum_p_neg  logsum_1_p_neg  count_neg  logsum_p_all  \
0          -956.270630       -0.051888        255   -958.656189
1          -889.857605       -0.163932        256   -890.094971
2          -797.323303       -0.185970        253   -801.533447
3          -829.828186       -0.369536        251   -836.544189
4          -846.109802       -0.358758        251   -849.422791
...                ...             ...        ...           ...
15992331   -125.325714       -0.212535         49   -126.338715
15992332   -119.744133       -0.257785         46   -121.008987
15992333   -126.637619       -0.201301         46   -129.754410
15992334    -29.832476       -0.090345         13    -33.269665
15992335    -75.639572       -0.327148         36    -82.901642

          logsum_1_p_all  count_all       dom  count_dom  depth  label  \
0              -0.283450        258  0.000000        258    268      0
1              -0.539576        257  0.000000        256    268      0
2              -1.731233        260  0.003891        257    268      0
3              -2.919629        263  0.011583        259    268      0
4              -1.683928        258  0.000000        252    268      0
...                  ...        ...       ...        ...    ...    ...
15992331       -0.566040         51  0.000000         49     51     -3
15992332       -4.505512         51  0.061224         49     51     -3
15992333       -1.310418         51  0.039216         51     51     -3
15992334      -87.197701         50  0.695652         46     51     -3
15992335       -2.085456         48  0.000000         40     52     -3

          dom_label   5mer  drach
0               0.0  AAACT   True
1               0.0  GGAAA  False
2               0.0  GAAAG  False
3               0.0  AAAGC  False
4               0.0  CTACT  False
...             ...    ...    ...
15992331        0.0  TTATA  False
15992332        0.0  ATAAT  False
15992333        0.0  TAATC  False
15992334        0.0  GGACT   True
15992335        0.0  TCAGC  False

[15992336 rows x 18 columns]

In [126]:
dorado_080_df = pd.read_pickle("/extdata4/baeklab/Hyeonseo/m6A/dorado-080/ON0090_dorado_basecall.bed" + ".m6A.pkl")
dorado_080_df.rename(columns = {"count_dom": "dorado_count", "dom": "pred_dorado"}, inplace = True)
dorado_080_df = dorado_080_df[dorado_080_df["dorado_count"] >= 20]
dorado_080_df = dorado_080_df.merge(label_df, on="label_id", how="inner")
dorado_080_df = dorado_080_df[["pred_dorado", "dorado_count", "label_id"]]
print(dorado_080_df)

          pred_dorado  dorado_count       label_id
0              0.0161            62    NM_000016:2
1              0.0149            67    NM_000016:5
2              0.0125           160   NM_000016:21
3              0.0616           146   NM_000016:24
4              0.0412           170   NM_000016:29
...               ...           ...            ...
15312228       0.1463            41  NR_184306:326
15312229       0.0000            40  NR_184306:330
15312230       0.0233            43  NR_184306:331
15312231       0.0000            43  NR_184306:333
15312232       0.0938            32  NR_184306:334

[15312233 rows x 3 columns]

In [127]:
dorado_080_df.rename(columns = {"dorado_count": "dorado_count_080", "pred_dorado": "pred_dorado_080"}, inplace = True)
eval_df = logsum_df.merge(dorado_080_df, on="label_id", how="left").fillna(0)
print(eval_df)

                label_id      p_sum  logsum_p_pos  logsum_1_p_pos  count_pos  \
0         NM_000016:1000   0.606511      0.000000        0.000000          0
1         NM_000016:1008   0.948786      0.000000        0.000000          0
2         NM_000016:1009   2.607620      0.000000        0.000000          0
3         NM_000016:1010   4.912612      0.000000        0.000000          0
4         NM_000016:1014   3.237954      0.000000        0.000000          0
...                  ...        ...           ...             ...        ...
15992369    NR_184306:85   1.133184      0.000000        0.000000          0
15992370    NR_184306:87   3.771550     -0.001452       -2.476578          1
15992371    NR_184306:88   2.137289      0.000000        0.000000          0
15992372    NR_184306:93  32.341377     -0.011076      -78.301079         23
15992373    NR_184306:98   4.046034      0.000000        0.000000          0

          logsum_p_neg  logsum_1_p_neg  count_neg  logsum_p_all  \
0          -956.270630       -0.051888        255   -958.656189
1          -889.857605       -0.163932        256   -890.094971
2          -797.323303       -0.185970        253   -801.533447
3          -829.828186       -0.369536        251   -836.544189
4          -846.109802       -0.358758        251   -849.422791
...                ...             ...        ...           ...
15992369   -125.325714       -0.212535         49   -126.338715
15992370   -119.744133       -0.257785         46   -121.008987
15992371   -126.637619       -0.201301         46   -129.754410
15992372    -29.832476       -0.090345         13    -33.269665
15992373    -75.639572       -0.327148         36    -82.901642

          logsum_1_p_all  count_all       dom  count_dom  depth  label  \
0              -0.283450        258  0.000000        258    268      0
1              -0.539576        257  0.000000        256    268      0
2              -1.731233        260  0.003891        257    268      0
3              -2.919629        263  0.011583        259    268      0
4              -1.683928        258  0.000000        252    268      0
...                  ...        ...       ...        ...    ...    ...
15992369       -0.566040         51  0.000000         49     51     -3
15992370       -4.505512         51  0.061224         49     51     -3
15992371       -1.310418         51  0.039216         51     51     -3
15992372      -87.197701         50  0.695652         46     51     -3
15992373       -2.085456         48  0.000000         40     52     -3

          dom_label   5mer  drach  pred_dorado_080  dorado_count_080
0               0.0  AAACT   True           0.0076             263.0
1               0.0  GGAAA  False           0.0000             262.0
2               0.0  GAAAG  False           0.0039             257.0
3               0.0  AAAGC  False           0.0077             260.0
4               0.0  CTACT  False           0.0039             255.0
...             ...    ...    ...              ...               ...
15992369        0.0  TTATA  False           0.0000              42.0
15992370        0.0  ATAAT  False           0.0000              32.0
15992371        0.0  TAATC  False           0.0000              46.0
15992372        0.0  GGACT   True           0.6047              43.0
15992373        0.0  TCAGC  False           0.0000              39.0

[15992374 rows x 20 columns]

In [128]:
eval_df["pm6a"] =  -(2-eval_df["dom"])*eval_df["logsum_1_p_pos"]/eval_df["count_all"] + ((1-eval_df["dom"])*np.log10(np.clip(1-eval_df["dom"],1e-30,1)) + eval_df["dom"] * np.log10(np.clip(eval_df["dom"],1e-30,1)))*(eval_df["count_pos"]/eval_df["count_all"])

print(eval_df[['pm6a', 'dom', 'count_dom', 'count_all', '5mer', 'drach', 'pred_dorado_080', 'dorado_count_080']])

              pm6a       dom  count_dom  count_all   5mer  drach  \
0         0.000000  0.000000        258        258  AAACT   True
1         0.000000  0.000000        256        257  GGAAA  False
2        -0.000000  0.003891        257        260  GAAAG  False
3        -0.000000  0.011583        259        263  AAAGC  False
4         0.000000  0.000000        252        258  CTACT  False
...            ...       ...        ...        ...    ...    ...
15992369  0.000000  0.000000         49         51  TTATA  False
15992370  0.092186  0.061224         49         51  ATAAT  False
15992371 -0.000000  0.039216         51         51  TAATC  False
15992372  1.919874  0.695652         46         50  GGACT   True
15992373  0.000000  0.000000         40         48  TCAGC  False

          pred_dorado_080  dorado_count_080
0                  0.0076             263.0
1                  0.0000             262.0
2                  0.0039             257.0
3                  0.0077             260.0
4                  0.0039             255.0
...                   ...               ...
15992369           0.0000              42.0
15992370           0.0000              32.0
15992371           0.0000              46.0
15992372           0.6047              43.0
15992373           0.0000              39.0

[15992374 rows x 8 columns]

In [129]:

geneid_table = pd.read_pickle("/extdata4/baeklab/Hyeonseo/m6A/res/ref/GRCh38_latest_genomic.convert_table.pkl")
geneid_table.rename({"transcript_id":"refseq"}, axis=1, inplace=True)
print(geneid_table)

              gene_id        refseq
6             DDX11L1     NR_046018
11             WASH7P     NR_024540
24          MIR6859-1     NR_106918
31        MIR1302-2HG  XR_007065314
36          MIR1302-2     NR_036051
...               ...           ...
4683855     KIR2DS5_6  XM_054333504
4683875    KIR2DL5A_7  XM_054333508
4683946     KIR3DS1_9  XM_054333507
4683987  LOC128966733  XR_008485847
4683991  LOC128966733  XM_054333509

[184489 rows x 2 columns]

In [130]:
eval_df["refseq"] = eval_df["label_id"].str.split(":").str[0]
eval_df = eval_df.merge(geneid_table, on="refseq", how="left")
eval_df.rename(columns = {"pm6a": "log_pm6a", "pred_dorado_080": "pred_dorado", "dorado_count_080": "count_dorado"}, inplace=True)
print(eval_df)

                label_id      p_sum  logsum_p_pos  logsum_1_p_pos  count_pos  \
0         NM_000016:1000   0.606511      0.000000        0.000000          0
1         NM_000016:1008   0.948786      0.000000        0.000000          0
2         NM_000016:1009   2.607620      0.000000        0.000000          0
3         NM_000016:1010   4.912612      0.000000        0.000000          0
4         NM_000016:1014   3.237954      0.000000        0.000000          0
...                  ...        ...           ...             ...        ...
15992369    NR_184306:85   1.133184      0.000000        0.000000          0
15992370    NR_184306:87   3.771550     -0.001452       -2.476578          1
15992371    NR_184306:88   2.137289      0.000000        0.000000          0
15992372    NR_184306:93  32.341377     -0.011076      -78.301079         23
15992373    NR_184306:98   4.046034      0.000000        0.000000          0

          logsum_p_neg  logsum_1_p_neg  count_neg  logsum_p_all  \
0          -956.270630       -0.051888        255   -958.656189
1          -889.857605       -0.163932        256   -890.094971
2          -797.323303       -0.185970        253   -801.533447
3          -829.828186       -0.369536        251   -836.544189
4          -846.109802       -0.358758        251   -849.422791
...                ...             ...        ...           ...
15992369   -125.325714       -0.212535         49   -126.338715
15992370   -119.744133       -0.257785         46   -121.008987
15992371   -126.637619       -0.201301         46   -129.754410
15992372    -29.832476       -0.090345         13    -33.269665
15992373    -75.639572       -0.327148         36    -82.901642

          logsum_1_p_all  ...  depth  label  dom_label   5mer  drach  \
0              -0.283450  ...    268      0        0.0  AAACT   True
1              -0.539576  ...    268      0        0.0  GGAAA  False
2              -1.731233  ...    268      0        0.0  GAAAG  False
3              -2.919629  ...    268      0        0.0  AAAGC  False
4              -1.683928  ...    268      0        0.0  CTACT  False
...                  ...  ...    ...    ...        ...    ...    ...
15992369       -0.566040  ...     51     -3        0.0  TTATA  False
15992370       -4.505512  ...     51     -3        0.0  ATAAT  False
15992371       -1.310418  ...     51     -3        0.0  TAATC  False
15992372      -87.197701  ...     51     -3        0.0  GGACT   True
15992373       -2.085456  ...     52     -3        0.0  TCAGC  False

          pred_dorado count_dorado  log_pm6a     refseq    gene_id
0              0.0076        263.0  0.000000  NM_000016      ACADM
1              0.0000        262.0  0.000000  NM_000016      ACADM
2              0.0039        257.0 -0.000000  NM_000016      ACADM
3              0.0077        260.0 -0.000000  NM_000016      ACADM
4              0.0039        255.0  0.000000  NM_000016      ACADM
...               ...          ...       ...        ...        ...
15992369       0.0000         42.0  0.000000  NR_184306  ZNF747-DT
15992370       0.0000         32.0  0.092186  NR_184306  ZNF747-DT
15992371       0.0000         46.0 -0.000000  NR_184306  ZNF747-DT
15992372       0.6047         43.0  1.919874  NR_184306  ZNF747-DT
15992373       0.0000         39.0  0.000000  NR_184306  ZNF747-DT

[15992374 rows x 23 columns]

In [131]:
ivt_tpm_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/runs/exp_MRNA/ON0105/ON0105/result/tpm/tpm.tsv",sep="\t")
ivt_tpm_df = ivt_tpm_df[ivt_tpm_df["tpm"] > 0.0]
ivt_tpm_df["logtpm"] = np.log10(ivt_tpm_df["tpm"])
ivt_tpm_df["refseq"] = ivt_tpm_df["transcript_name"].str.split(".").str[0]
ivt_tpm_df["ivt_perc"] = ivt_tpm_df["logtpm"].rank(pct=True)
ivt_tpm_df

,transcript_name,raw,est_count,tpm,transcript_length,logtpm,refseq,ivt_perc
0,NM_002952.4,1.339165e-02,1.840900e+04,1.339165e+04,945,4.126834,NM_002952,1.000000
1,NR_026712.1,1.118017e-02,1.536897e+04,1.118017e+04,658,4.048449,NR_026712,0.999981
2,NM_001000.4,9.515059e-03,1.308000e+04,9.515059e+03,390,3.978411,NM_001000,0.999961
3,NM_022551.3,9.240792e-03,1.270297e+04,9.240792e+03,549,3.965709,NM_022551,0.999942
4,NM_001404.5,9.131693e-03,1.255300e+04,9.131693e+03,1446,3.960551,NM_001404,0.999922
...,...,...,...,...,...,...,...,...
51536,NR_024240.1,3.105177e-40,4.268573e-34,3.105177e-34,1580,-33.507914,NR_024240,0.000097
51537,NR_024219.1,6.239105e-49,8.576667e-43,6.239105e-43,120,-42.204878,NR_024219,0.000058
51538,NR_024217.1,6.239105e-49,8.576667e-43,6.239105e-43,120,-42.204878,NR_024217,0.000058
51539,NR_024220.1,6.239105e-49,8.576667e-43,6.239105e-43,120,-42.204878,NR_024220,0.000058
51540,NM_199290.4,4.260183e-51,5.856316e-45,4.260183e-45,799,-44.370572,NM_199290,0.000019

In [132]:
cell_tpm_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/runs/exp_MRNA/ON0090/ON0090/result/dorado-070-aligned/tpm/tpm.tsv",sep="\t")
cell_tpm_df = cell_tpm_df[cell_tpm_df["tpm"] > 0.0]
cell_tpm_df["logtpm"] = np.log10(cell_tpm_df["tpm"])
cell_tpm_df["refseq"] = cell_tpm_df["transcript_name"].str.split(".").str[0]
cell_tpm_df["cell_perc"] = cell_tpm_df["logtpm"].rank(pct=True)
cell_tpm_df

,transcript_name,raw,est_count,tpm,transcript_length,logtpm,refseq,cell_perc
0,NM_002952.4,1.124904e-02,4.911100e+04,1.124904e+04,945,4.051116,NM_002952,1.000000
1,NM_022551.3,6.785937e-03,2.962600e+04,6.785937e+03,549,3.831610,NM_022551,0.999984
2,NM_001000.4,6.460679e-03,2.820599e+04,6.460679e+03,390,3.810278,NM_001000,0.999967
3,NM_000972.3,5.957222e-03,2.600800e+04,5.957222e+03,887,3.775044,NM_000972,0.999951
4,NR_026712.1,5.942332e-03,2.594299e+04,5.942332e+03,658,3.773957,NR_026712,0.999934
...,...,...,...,...,...,...,...,...
60667,NM_001395980.1,7.291763e-45,3.183433e-38,7.291763e-39,1559,-38.137167,NM_001395980,0.000082
60668,NR_001434.4,2.219039e-46,9.687866e-40,2.219039e-40,1705,-39.653835,NR_001434,0.000066
60669,NR_144546.2,9.444820e-51,4.123413e-44,9.444820e-45,1456,-44.024806,NR_144546,0.000041
60670,NR_176224.1,9.444820e-51,4.123413e-44,9.444820e-45,1414,-44.024806,NR_176224,0.000041
60671,NR_026715.1,1.237254e-60,5.401594e-54,1.237254e-54,653,-53.907541,NR_026715,0.000016

In [133]:
eval_df = eval_df.merge(ivt_tpm_df[["refseq", "ivt_perc"]], on="refseq", how="left")
eval_df = eval_df.merge(cell_tpm_df[["refseq", "cell_perc"]], on="refseq", how="left")
eval_df.fillna(0, inplace=True)
print(eval_df)

                label_id      p_sum  logsum_p_pos  logsum_1_p_pos  count_pos  \
0         NM_000016:1000   0.606511      0.000000        0.000000          0
1         NM_000016:1008   0.948786      0.000000        0.000000          0
2         NM_000016:1009   2.607620      0.000000        0.000000          0
3         NM_000016:1010   4.912612      0.000000        0.000000          0
4         NM_000016:1014   3.237954      0.000000        0.000000          0
...                  ...        ...           ...             ...        ...
15992369    NR_184306:85   1.133184      0.000000        0.000000          0
15992370    NR_184306:87   3.771550     -0.001452       -2.476578          1
15992371    NR_184306:88   2.137289      0.000000        0.000000          0
15992372    NR_184306:93  32.341377     -0.011076      -78.301079         23
15992373    NR_184306:98   4.046034      0.000000        0.000000          0

          logsum_p_neg  logsum_1_p_neg  count_neg  logsum_p_all  \
0          -956.270630       -0.051888        255   -958.656189
1          -889.857605       -0.163932        256   -890.094971
2          -797.323303       -0.185970        253   -801.533447
3          -829.828186       -0.369536        251   -836.544189
4          -846.109802       -0.358758        251   -849.422791
...                ...             ...        ...           ...
15992369   -125.325714       -0.212535         49   -126.338715
15992370   -119.744133       -0.257785         46   -121.008987
15992371   -126.637619       -0.201301         46   -129.754410
15992372    -29.832476       -0.090345         13    -33.269665
15992373    -75.639572       -0.327148         36    -82.901642

          logsum_1_p_all  ...  dom_label   5mer  drach  pred_dorado  \
0              -0.283450  ...        0.0  AAACT   True       0.0076
1              -0.539576  ...        0.0  GGAAA  False       0.0000
2              -1.731233  ...        0.0  GAAAG  False       0.0039
3              -2.919629  ...        0.0  AAAGC  False       0.0077
4              -1.683928  ...        0.0  CTACT  False       0.0039
...                  ...  ...        ...    ...    ...          ...
15992369       -0.566040  ...        0.0  TTATA  False       0.0000
15992370       -4.505512  ...        0.0  ATAAT  False       0.0000
15992371       -1.310418  ...        0.0  TAATC  False       0.0000
15992372      -87.197701  ...        0.0  GGACT   True       0.6047
15992373       -2.085456  ...        0.0  TCAGC  False       0.0000

          count_dorado  log_pm6a     refseq    gene_id  ivt_perc  cell_perc
0                263.0  0.000000  NM_000016      ACADM  0.710793   0.685415
1                262.0  0.000000  NM_000016      ACADM  0.710793   0.685415
2                257.0 -0.000000  NM_000016      ACADM  0.710793   0.685415
3                260.0 -0.000000  NM_000016      ACADM  0.710793   0.685415
4                255.0  0.000000  NM_000016      ACADM  0.710793   0.685415
...                ...       ...        ...        ...       ...        ...
15992369          42.0  0.000000  NR_184306  ZNF747-DT  0.718021   0.683742
15992370          32.0  0.092186  NR_184306  ZNF747-DT  0.718021   0.683742
15992371          46.0 -0.000000  NR_184306  ZNF747-DT  0.718021   0.683742
15992372          43.0  1.919874  NR_184306  ZNF747-DT  0.718021   0.683742
15992373          39.0  0.000000  NR_184306  ZNF747-DT  0.718021   0.683742

[15992374 rows x 25 columns]

In [134]:
eval_df["noisy_or"] = - eval_df["logsum_1_p_pos"] /  eval_df["count_all"]
select_df = eval_df[['label_id', 'gene_id', 'log_pm6a', "noisy_or", 'dom', 'dom_label', 'label', 'count_dom', 'count_all', '5mer', 'drach', 'pred_dorado', 'count_dorado', "ivt_perc", "cell_perc"]].copy()
select_df[select_df["log_pm6a"] > 1.0]

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc
784,NM_000017:1321,ACADS,2.021584,1.425952,0.492063,0.452959,-1,126,131,GGACT,True,0.4634,123.0,0.898421,0.918282
796,NM_000017:1373,ACADS,2.437110,1.898793,0.632000,0.720267,1,125,130,AGACT,True,0.5882,119.0,0.898421,0.918282
2170,NM_000021:1584,PSEN1,3.293502,3.287473,0.992908,0.875758,-1,141,143,GGACC,True,0.9856,139.0,0.825547,0.801762
2191,NM_000021:1655,PSEN1,1.550892,1.055201,0.444444,0.498157,-1,135,145,TGACT,True,0.4191,136.0,0.825547,0.801762
2217,NM_000021:1730,PSEN1,2.817645,2.696066,0.916667,0.916725,1,144,145,GGACT,True,0.9203,138.0,0.825547,0.801762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15990848,NR_184072:1057,ATXN7L3-AS1,1.224421,0.889524,0.517241,0.000000,-3,29,35,GAACT,True,0.0000,0.0,0.137434,0.697447
15990939,NR_184072:1390,ATXN7L3-AS1,1.092904,0.713811,0.375000,0.000000,-3,24,30,GAACT,True,0.0000,0.0,0.137434,0.697447
15990972,NR_184072:502,ATXN7L3-AS1,1.675686,1.527358,0.850000,0.000000,-3,20,25,GGACT,True,0.0000,0.0,0.137434,0.697447
15992368,NR_184306:77,ZNF747-DT,1.229243,0.736066,0.260870,0.000000,-3,46,49,GGACC,True,0.2500,44.0,0.718021,0.683742
15992372,NR_184306:93,ZNF747-DT,1.919874,1.566022,0.695652,0.000000,-3,46,50,GGACT,True,0.6047,43.0,0.718021,0.683742

In [135]:
select_df[select_df["gene_id"]=="ACTB"]

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc
1257724,NM_001101:1000,ACTB,0.035447,0.018853,0.072576,0.0,0,10086,10918,GTACC,False,0.0762,7050.0,0.998525,0.999506
1257725,NM_001101:1008,ACTB,0.020233,0.010883,0.082912,0.0,-1,9890,11212,GCATT,False,0.0329,6377.0,0.998525,0.999506
1257726,NM_001101:1015,ACTB,0.006398,0.003242,0.013325,0.0,0,11182,11402,CGACA,False,0.0177,8150.0,0.998525,0.999506
1257727,NM_001101:1017,ACTB,0.006861,0.003500,0.019469,0.0,0,10838,11175,ACAGG,False,0.0548,7319.0,0.998525,0.999506
1257728,NM_001101:1020,ACTB,0.000395,0.000198,0.001941,0.0,-1,11336,11377,GGATG,False,0.0116,8269.0,0.998525,0.999506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1258107,NM_001101:972,ACTB,0.006705,0.003473,0.037617,0.0,-1,10607,11300,ACACA,False,0.0564,6893.0,0.998525,0.999506
1258108,NM_001101:974,ACTB,0.006030,0.003073,0.018454,0.0,0,10838,11331,ACAGT,False,0.0375,7042.0,0.998525,0.999506
1258109,NM_001101:990,ACTB,0.009454,0.004902,0.038906,0.0,0,10127,10790,GCACC,False,0.0207,7446.0,0.998525,0.999506
1258110,NM_001101:993,ACTB,0.030987,0.016887,0.097828,0.0,0,9946,11155,CCACC,False,0.0128,7414.0,0.998525,0.999506
1258111,NM_001101:996,ACTB,0.058757,0.032774,0.132572,0.0,-1,9723,11258,CCATG,False,0.0532,6544.0,0.998525,0.999506

In [136]:
select_df["refseq"] = select_df["label_id"].str.split(":").str[0]

In [137]:
m6a_counts = select_df[select_df["log_pm6a"] > np.percentile(select_df["log_pm6a"],99.5)].groupby("refseq").count().sort_values("refseq")["count_all"]
m6a_counts = m6a_counts.reset_index()
m6a_counts = m6a_counts.merge(cell_tpm_df[["refseq", "transcript_length"]], on="refseq", how="left")
m6a_counts.fillna(0)
m6a_counts["m6a_density"] = m6a_counts["count_all"]/m6a_counts["transcript_length"]
m6a_counts.rename(columns = {"count_all": "m6a_count"}, inplace=True)
m6a_counts[m6a_counts["m6a_density"] > 0.005]

             refseq  m6a_count  transcript_length  m6a_density
49        NM_000199         19             2705.0     0.007024
101       NM_000418         22             3624.0     0.006071
144       NM_000676         12             1522.0     0.007884
147       NM_000692         17             3028.0     0.005614
257    NM_001002914         18             2783.0     0.006468
...             ...        ...                ...          ...
15284     NR_171561          8             1405.0     0.005694
15285     NR_171563          8             1566.0     0.005109
15291     NR_172519         16             2722.0     0.005878
15323     NR_183329          4              761.0     0.005256
15326     NR_183514         10             1453.0     0.006882

[486 rows x 4 columns]

In [138]:
pm6a_cutoff = np.percentile(select_df["log_pm6a"],99.5)

In [144]:
hiconf_df = select_df[(select_df["log_pm6a"] > pm6a_cutoff) & (~select_df["drach"]) & (select_df["cell_perc"] > 0.9)].copy().sort_values("gene_id")
hiconf_df = hiconf_df.merge(m6a_counts, on="refseq", how="left").fillna(0)
hiconf_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density
0,NM_001089:5961,ABCA3,2.685794,2.127319,0.655290,0.711017,1,293,296,GGACG,False,0.6536,280.0,0.952834,0.961819,NM_001089,4,6602.0,0.000606
1,NM_004996:5211,ABCC1,2.338132,1.984957,0.751908,0.709251,-1,262,283,GAACG,False,0.7126,261.0,0.934344,0.964893,NM_004996,14,6504.0,0.002153
2,NM_001198934:1073,ABCC10,2.337938,1.841972,0.647059,0.687953,1,68,75,GGACG,False,0.6579,76.0,0.833143,0.924578,NM_001198934,9,5043.0,0.001785
3,NM_198147:462,ABHD15,2.393320,2.227509,0.872642,0.942997,-1,212,229,GGACG,False,0.8122,197.0,0.810287,0.919411,NM_198147,29,3492.0,0.008305
4,NM_198147:1838,ABHD15,2.998586,2.858266,0.912698,0.950749,-1,252,258,AGACG,False,0.9102,245.0,0.810287,0.919411,NM_198147,29,3492.0,0.008305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,NM_001195605:938,ZNF865,3.145893,2.856116,0.847222,0.897226,-1,72,76,GGACG,False,0.7639,72.0,0.576541,0.906464,NM_001195605,29,3763.0,0.007707
1004,NM_023926:2063,ZSCAN18,2.756144,2.249168,0.701754,0.778869,-1,57,63,GGACG,False,0.7083,48.0,0.817941,0.948312,NM_023926,3,2783.0,0.001078
1005,NM_001145543:1819,ZSCAN18,2.973099,2.354091,0.664835,0.778869,-1,182,189,GGACG,False,0.6532,173.0,0.817941,0.909085,NM_001145543,3,2539.0,0.001182
1006,NM_199341:1013,ZSWIM9,2.064114,1.343236,0.384615,0.596064,-1,52,52,AGACG,False,0.4038,52.0,0.870297,0.905434,NM_199341,11,3600.0,0.003056
1007,NM_199341:2634,ZSWIM9,2.054012,1.400837,0.447059,0.517804,1,85,91,GGACG,False,0.4231,78.0,0.870297,0.905434,NM_199341,11,3600.0,0.003056

In [145]:
hiconf_df = hiconf_df[hiconf_df["m6a_density"] <= 0.005]
hiconf_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density
0,NM_001089:5961,ABCA3,2.685794,2.127319,0.655290,0.711017,1,293,296,GGACG,False,0.6536,280.0,0.952834,0.961819,NM_001089,4,6602.0,0.000606
1,NM_004996:5211,ABCC1,2.338132,1.984957,0.751908,0.709251,-1,262,283,GAACG,False,0.7126,261.0,0.934344,0.964893,NM_004996,14,6504.0,0.002153
2,NM_001198934:1073,ABCC10,2.337938,1.841972,0.647059,0.687953,1,68,75,GGACG,False,0.6579,76.0,0.833143,0.924578,NM_001198934,9,5043.0,0.001785
5,NM_032182:965,ABRAXAS2,1.675232,1.481502,0.789855,0.871889,1,138,150,GTACT,False,0.7883,137.0,0.915679,0.925905,NM_032182,9,2955.0,0.003046
8,NM_005736:1364,ACTR1A,2.895120,2.557538,0.803279,0.825807,1,488,493,GGACG,False,0.7918,490.0,0.977891,0.979900,NM_005736,2,2830.0,0.000707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,NM_025069:1812,ZNF703,1.689626,1.570630,0.868580,0.918589,1,662,721,ACACT,False,0.7813,567.0,0.963728,0.987853,NM_025069,11,3316.0,0.003317
1004,NM_023926:2063,ZSCAN18,2.756144,2.249168,0.701754,0.778869,-1,57,63,GGACG,False,0.7083,48.0,0.817941,0.948312,NM_023926,3,2783.0,0.001078
1005,NM_001145543:1819,ZSCAN18,2.973099,2.354091,0.664835,0.778869,-1,182,189,GGACG,False,0.6532,173.0,0.817941,0.909085,NM_001145543,3,2539.0,0.001182
1006,NM_199341:1013,ZSWIM9,2.064114,1.343236,0.384615,0.596064,-1,52,52,AGACG,False,0.4038,52.0,0.870297,0.905434,NM_199341,11,3600.0,0.003056
1007,NM_199341:2634,ZSWIM9,2.054012,1.400837,0.447059,0.517804,1,85,91,GGACG,False,0.4231,78.0,0.870297,0.905434,NM_199341,11,3600.0,0.003056

In [180]:
pm6a_cutoff = 0.712
exclude_gene = [
    "MKI67",
    "NTN1",
    "RMI2",
    "MICU1",
    "KAT6A",
    "TNFRSF1A",
    "KHDRBS1",
    "CDV3",
    "PRMT6",
    "KDM4A",
    "CENPB",
    "PXDN",
]
print(pm6a_cutoff)

hiconf_df = select_df[(select_df["log_pm6a"] > pm6a_cutoff) & (~select_df["drach"]) & (select_df["cell_perc"] > 0.9)].copy().sort_values("gene_id")
hiconf_df = hiconf_df.merge(m6a_counts, on="refseq", how="left").fillna(0)

print(len(select_df[select_df["log_pm6a"] > pm6a_cutoff]))

dorado_fail_df = hiconf_df[(hiconf_df["pred_dorado"] == 0)].copy()
dorado_fail_df = dorado_fail_df[~dorado_fail_df["gene_id"].isin(exclude_gene)]


dorado_fail_df

0.712
151687

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density
108,NM_001013620:638,ALG10B,0.834373,0.634318,0.550000,0.000000,0,20,21,AAAAC,False,0.0,0.0,0.815438,0.931632,NM_001013620,5.0,10050.0,0.000498
114,NM_020690:2983,ANKHD1-EIF4EBP3,0.819586,0.562345,0.416667,0.000000,0,24,25,TGAAC,False,0.0,25.0,0.904775,0.902228,NM_020690,18.0,8328.0,0.002161
165,NM_018171:3043,APPL2,0.712054,0.588520,0.686567,0.000000,0,134,164,CCATC,False,0.0,146.0,0.903446,0.900770,NM_018171,1.0,3171.0,0.000315
274,NM_001377448:4028,BAHCC1,0.932408,0.528186,0.173913,0.335664,-1,23,25,GGACG,False,0.0,0.0,0.773724,0.904577,NM_001377448,11.0,10726.0,0.001026
459,NM_001170629:536,CHD8,1.165228,1.009193,0.746835,0.000000,0,79,84,AGAAC,False,0.0,78.0,0.903009,0.967135,NM_001170629,20.0,8467.0,0.002362
475,NR_171547:2308,CHPF2,2.214009,1.435382,0.380952,0.394277,1,21,21,GGACG,False,0.0,0.0,0.748113,0.921084,NR_171547,13.0,4206.0,0.003091
546,NM_005730:2720,CTDSP2,0.744648,0.654327,0.766055,0.000000,0,218,256,CCATC,False,0.0,246.0,0.935149,0.966443,NM_005730,10.0,4785.0,0.002090
674,NM_080738:2202,EDARADD,0.766543,0.740457,0.901838,0.000000,0,2720,2959,TCAAA,False,0.0,46.0,0.979026,0.927396,NM_080738,6.0,3095.0,0.001939
740,NM_001329090:805,EPHA2,1.608960,1.455806,0.818182,0.941250,-1,22,24,GCACT,False,0.0,0.0,0.872480,0.901347,NM_001329090,10.0,3878.0,0.002579
841,NM_001316938:1630,FBXL12,1.174176,0.702675,0.250000,0.410789,1,20,22,GGACG,False,0.0,0.0,0.942648,0.903827,NM_001316938,6.0,1917.0,0.003130
950,NM_001371462:2217,GALNT11,0.839246,0.458507,0.125000,0.275112,1,24,24,GAACG,False,0.0,0.0,0.383520,0.903267,NM_001371462,1.0,2861.0,0.000350
951,NM_001371462:2561,GALNT11,0.790883,0.442281,0.160000,0.000000,0,25,25,GGATA,False,0.0,0.0,0.383520,0.903267,NM_001371462,1.0,2861.0,0.000350
952,NM_001371462:2250,GALNT11,0.947466,0.554661,0.208333,0.630171,-1,24,24,GGAGT,False,0.0,0.0,0.383520,0.903267,NM_001371462,1.0,2861.0,0.000350
1003,NM_001282618:1722,GNAI2,0.835328,0.568109,0.419355,0.000000,0,31,33,AAAAC,False,0.0,0.0,0.863400,0.962075,NM_001282618,0.0,0.0,0.000000
1025,NM_001136557:2193,GPR107,1.787405,1.127730,0.333333,0.214130,1,24,24,GGACG,False,0.0,0.0,0.855416,0.908063,NM_001136557,4.0,6873.0,0.000582
1120,NM_006041:687,HS3ST3B1,0.807728,0.534294,0.400000,0.399642,-3,25,31,GGACG,False,0.0,0.0,0.828341,0.912876,NM_006041,4.0,5369.0,0.000745
1155,NM_001542:603,IGSF3,0.833784,0.824020,0.954545,0.000000,0,22,29,CCAAC,False,0.0,29.0,0.900021,0.911096,NM_001542,22.0,7327.0,0.003003
1221,NM_152405:308,JMY,1.766405,1.105077,0.333333,0.406751,-1,21,22,GGACG,False,0.0,0.0,0.797200,0.906464,NM_152405,14.0,9096.0,0.001539
1222,NM_003724:2200,JRK,1.594822,1.524985,0.909091,0.764723,1,22,25,CAACT,False,0.0,0.0,0.633641,0.903382,NM_003724,15.0,9097.0,0.001649
1292,NM_004798:4860,KIF3B,0.723263,0.517513,0.475728,0.000000,0,103,110,AGAAC,False,0.0,108.0,0.830193,0.918488,NM_004798,18.0,6116.0,0.002943
1412,NM_032270:1119,LRRC8C,1.053979,0.899947,0.725000,0.000000,0,40,41,AAAAC,False,0.0,33.0,0.718021,0.912802,NM_032270,22.0,7170.0,0.003068
1611,NR_040103:1355,NAXD,0.880428,0.808055,0.821429,0.000000,0,28,34,TGAAC,False,0.0,27.0,0.895132,0.915793,NR_040103,10.0,2612.0,0.003828
1719,NM_001278209:2701,NUP153,1.899402,1.336646,0.480000,0.231919,1,25,25,ATACT,False,0.0,0.0,0.906337,0.935234,NM_001278209,15.0,6119.0,0.002451
1828,NM_001172437:455,PEG10,0.905034,0.618601,0.409091,0.000000,-3,22,26,CAAGC,False,0.0,0.0,0.911895,0.922996,NM_001172437,24.0,6639.0,0.003615
1830,NM_001172437:509,PEG10,0.808276,0.450523,0.148148,0.000000,-3,27,28,GGACG,False,0.0,0.0,0.911895,0.922996,NM_001172437,24.0,6639.0,0.003615
1965,NM_001080121:594,PRNP,0.777541,0.446523,0.181818,0.097249,-1,22,24,CGACT,False,0.0,0.0,0.899274,0.932951,NM_001080121,3.0,2430.0,0.001235
1968,NM_003913:416,PRPF4B,0.733431,0.521564,0.489510,0.000000,-1,143,166,AGAAC,False,0.0,160.0,0.867077,0.942725,NM_003913,7.0,7517.0,0.000931
2045,NM_021168:1039,RAB40C,0.851994,0.768906,0.804348,0.000000,-1,46,51,AGAAC,False,0.0,50.0,0.386605,0.905278,NM_021168,18.0,2718.0,0.006623
2097,NM_001366508:923,RGMB,1.083403,0.966792,0.785047,0.000000,0,107,114,AGAAC,False,0.0,103.0,0.725112,0.947076,NM_001366508,14.0,4463.0,0.003137
2160,NM_001199974:543,RPL36A-HNRNPH2,1.367006,0.869347,0.333333,0.000000,1,27,27,GGATT,False,0.0,0.0,0.924419,0.917136,NM_001199974,5.0,2408.0,0.002076
2164,NR_077246:698,RPS14P3,1.000152,0.620240,0.296296,0.000000,-3,27,28,GGACG,False,0.0,0.0,0.975049,0.919897,NR_077246,0.0,0.0,0.000000
2444,NM_001291411:1034,SON,1.141648,0.681444,0.250000,0.342017,1,24,24,GGATT,False,0.0,0.0,0.640607,0.903539,NM_001291411,38.0,7897.0,0.004812
2447,NM_001291411:684,SON,0.976099,0.676202,0.428571,0.000000,-1,21,24,AAAAC,False,0.0,0.0,0.640607,0.903539,NM_001291411,38.0,7897.0,0.004812
2527,NM_003185:2748,TAF4,0.793451,0.555245,0.453333,0.000000,0,75,87,GGAAT,False,0.0,80.0,0.685629,0.903011,NM_003185,8.0,4699.0,0.001702
2552,NM_001113361:2293,TBC1D14,0.775750,0.756598,0.931035,0.000000,0,29,33,AAAAC,False,0.0,0.0,0.854417,0.902731,NM_001113361,7.0,4861.0,0.001440
2588,NM_001129884:340,TEX264,1.031691,0.673970,0.363636,0.000000,0,22,24,CAAGC,False,0.0,20.0,0.946935,0.915876,NM_001129884,3.0,1372.0,0.002187
2813,NM_018052:1605,VAC14,0.893817,0.646648,0.503704,0.000000,-1,135,151,AGACG,False,0.0,148.0,0.898809,0.934484,NM_018052,2.0,3096.0,0.000646
2857,NR_001564:546,XIST,0.778385,0.621211,0.609756,0.000000,-3,82,92,TGAAC,False,0.0,72.0,0.998719,0.999753,NR_001564,17.0,19296.0,0.000881
2865,NM_001354729:1390,XPC,1.221978,0.698606,0.192308,0.213089,-1,26,26,GGATT,False,0.0,0.0,0.900671,0.920128,NM_001354729,6.0,3632.0,0.001652

In [210]:
very_hiconf_df = hiconf_df[(hiconf_df["log_pm6a"] > np.percentile(select_df["log_pm6a"],99.8)) & (hiconf_df["cell_perc"] > 0.90)].copy()
very_hiconf_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density
5,NM_001089:5961,ABCA3,2.685794,2.127319,0.655290,0.711017,1,293,296,GGACG,False,0.6536,280.0,0.952834,0.961819,NM_001089,4.0,6602.0,0.000606
14,NM_198147:462,ABHD15,2.393320,2.227509,0.872642,0.942997,-1,212,229,GGACG,False,0.8122,197.0,0.810287,0.919411,NM_198147,29.0,3492.0,0.008305
16,NM_198147:1838,ABHD15,2.998586,2.858266,0.912698,0.950749,-1,252,258,AGACG,False,0.9102,245.0,0.810287,0.919411,NM_198147,29.0,3492.0,0.008305
27,NM_005736:1364,ACTR1A,2.895120,2.557538,0.803279,0.825807,1,488,493,GGACG,False,0.7918,490.0,0.977891,0.979900,NM_005736,2.0,2830.0,0.000707
32,NM_138422:1052,ADAT3,2.389407,1.779976,0.569767,0.586346,-1,86,93,GGACG,False,0.6180,89.0,0.779622,0.913205,NM_138422,14.0,1599.0,0.008755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2958,NM_003575:2234,ZNF282,3.129509,2.669289,0.761905,0.718320,1,273,276,GGACG,False,0.7547,265.0,0.731175,0.933231,NM_003575,10.0,3651.0,0.002739
2991,NM_001195605:938,ZNF865,3.145893,2.856116,0.847222,0.897226,-1,72,76,GGACG,False,0.7639,72.0,0.576541,0.906464,NM_001195605,29.0,3763.0,0.007707
2993,NM_001195605:1756,ZNF865,3.206811,3.156591,0.965517,0.949771,1,87,90,AGACG,False,0.9512,82.0,0.576541,0.906464,NM_001195605,29.0,3763.0,0.007707
2995,NM_023926:2063,ZSCAN18,2.756144,2.249168,0.701754,0.778869,-1,57,63,GGACG,False,0.7083,48.0,0.817941,0.948312,NM_023926,3.0,2783.0,0.001078
2996,NM_001145543:1819,ZSCAN18,2.973099,2.354091,0.664835,0.778869,-1,182,189,GGACG,False,0.6532,173.0,0.817941,0.909085,NM_001145543,3.0,2539.0,0.001182

In [139]:
gene_list = very_hiconf_df["gene_id"].unique()

In [141]:
import os, tqdm, xmltodict, requests, glob

def get_pubmed_count(gene):
    API_KEY="e60738641b2884a4933fe8291725f839bd07"
    query_template = '("Nat *"[Journal] OR "Nature"[Journal] OR "Science"[Journal] OR "Cell"[Journal] OR "Cell *"[Journal]) AND "{gene}"[tiab]'
    retmax = 1000
    search_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term={term}&retmax={retmax}&usehistory=y&api_key={apikey}"
    response = requests.get(search_url.format(term=query_template.format(gene=gene), retmax=retmax, apikey = API_KEY))
    count = int(xmltodict.parse(response.content)["eSearchResult"]["Count"])
    return count

In [142]:
count_dict = {gene: get_pubmed_count(gene) for gene in tqdm.tqdm(gene_list)}
print(count_dict)

  0%|                                                                                                                                                                      | 0/54 [00:00<?, ?it/s]
  2%|██▉                                                                                                                                                           | 1/54 [00:00<00:41,  1.29it/s]
  4%|█████▊                                                                                                                                                        | 2/54 [00:01<00:40,  1.29it/s]
  6%|████████▊                                                                                                                                                     | 3/54 [00:02<00:38,  1.32it/s]
  7%|███████████▋                                                                                                                                                  | 4/54 [00:03<00:37,  1.34it/s]
  9%|██████████████▋                                                                                                                                               | 5/54 [00:03<00:37,  1.32it/s]
 11%|█████████████████▌                                                                                                                                            | 6/54 [00:04<00:36,  1.31it/s]
 13%|████████████████████▍                                                                                                                                         | 7/54 [00:05<00:35,  1.31it/s]
 15%|███████████████████████▍                                                                                                                                      | 8/54 [00:06<00:34,  1.33it/s]
 17%|██████████████████████████▎                                                                                                                                   | 9/54 [00:06<00:34,  1.31it/s]
 19%|█████████████████████████████                                                                                                                                | 10/54 [00:07<00:33,  1.30it/s]
 20%|███████████████████████████████▉                                                                                                                             | 11/54 [00:08<00:32,  1.31it/s]
 22%|██████████████████████████████████▉                                                                                                                          | 12/54 [00:09<00:32,  1.31it/s]
 24%|█████████████████████████████████████▊                                                                                                                       | 13/54 [00:09<00:31,  1.30it/s]
 26%|████████████████████████████████████████▋                                                                                                                    | 14/54 [00:10<00:30,  1.31it/s]
 28%|███████████████████████████████████████████▌                                                                                                                 | 15/54 [00:11<00:29,  1.30it/s]
 30%|██████████████████████████████████████████████▌                                                                                                              | 16/54 [00:12<00:28,  1.32it/s]
 31%|█████████████████████████████████████████████████▍                                                                                                           | 17/54 [00:12<00:27,  1.32it/s]
 33%|████████████████████████████████████████████████████▎                                                                                                        | 18/54 [00:14<00:30,  1.17it/s]
 35%|███████████████████████████████████████████████████████▏                                                                                                     | 19/54 [00:14<00:28,  1.21it/s]
 37%|██████████████████████████████████████████████████████████▏                                                                                                  | 20/54 [00:15<00:28,  1.20it/s]
 39%|█████████████████████████████████████████████████████████████                                                                                                | 21/54 [00:16<00:26,  1.23it/s]
 41%|███████████████████████████████████████████████████████████████▉                                                                                             | 22/54 [00:17<00:25,  1.27it/s]
 43%|██████████████████████████████████████████████████████████████████▊                                                                                          | 23/54 [00:17<00:24,  1.27it/s]
 44%|█████████████████████████████████████████████████████████████████████▊                                                                                       | 24/54 [00:18<00:23,  1.28it/s]
 46%|████████████████████████████████████████████████████████████████████████▋                                                                                    | 25/54 [00:19<00:22,  1.30it/s]
 48%|███████████████████████████████████████████████████████████████████████████▌                                                                                 | 26/54 [00:20<00:22,  1.24it/s]
 50%|██████████████████████████████████████████████████████████████████████████████▌                                                                              | 27/54 [00:21<00:22,  1.20it/s]
 52%|█████████████████████████████████████████████████████████████████████████████████▍                                                                           | 28/54 [00:22<00:21,  1.21it/s]
 54%|████████████████████████████████████████████████████████████████████████████████████▎                                                                        | 29/54 [00:22<00:20,  1.24it/s]
 56%|███████████████████████████████████████████████████████████████████████████████████████▏                                                                     | 30/54 [00:23<00:19,  1.25it/s]
 57%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                  | 31/54 [00:24<00:19,  1.21it/s]
 59%|█████████████████████████████████████████████████████████████████████████████████████████████                                                                | 32/54 [00:25<00:17,  1.24it/s]
 61%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                             | 33/54 [00:25<00:16,  1.26it/s]
 63%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 34/54 [00:26<00:15,  1.28it/s]
 65%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                       | 35/54 [00:27<00:17,  1.08it/s]
 67%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                    | 36/54 [00:28<00:15,  1.13it/s]
 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                 | 37/54 [00:29<00:14,  1.19it/s]
 70%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                              | 38/54 [00:30<00:13,  1.22it/s]
 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                           | 39/54 [00:31<00:12,  1.22it/s]
 74%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 40/54 [00:31<00:11,  1.20it/s]
 76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 41/54 [00:32<00:11,  1.13it/s]
 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 42/54 [00:33<00:10,  1.18it/s]
 80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                | 43/54 [00:34<00:09,  1.22it/s]
 81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 44/54 [00:35<00:08,  1.24it/s]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 45/54 [00:36<00:07,  1.25it/s]
 85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 46/54 [00:36<00:06,  1.27it/s]
 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 47/54 [00:37<00:05,  1.23it/s]
 89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 48/54 [00:38<00:04,  1.24it/s]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 49/54 [00:39<00:03,  1.26it/s]
 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 50/54 [00:40<00:03,  1.25it/s]
 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 51/54 [00:41<00:02,  1.18it/s]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 52/54 [00:41<00:01,  1.21it/s]
 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 53/54 [00:42<00:00,  1.19it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 54/54 [00:43<00:00,  1.24it/s]

{'ABCA3': 2, 'ACTR1A': 0, 'ADGRA3': 0, 'AKT1S1': 0, 'CDC42EP4': 1, 'CENPB': 10, 'COL6A2': 4, 'CSNK1G2': 0, 'CTCF': 367, 'FAAP100': 3, 'FAM171A1': 0, 'FAM32A': 1, 'FOXD1': 6, 'FZD7': 17, 'GNA11': 8, 'GPR27': 0, 'ICMT': 4, 'KDM4A': 17, 'KIAA2013': 0, 'KLF9': 7, 'MARCKS': 33, 'MEX3D': 0, 'MKI67': 14, 'MLLT1': 3, 'MYOM2': 0, 'NIBAN2': 0, 'NLGN2': 2, 'NORAD': 13, 'NRN1': 1, 'NTN1': 8, 'NXN': 1, 'PLXNA1': 2, 'POM121': 3, 'POM121C': 0, 'PPP1R26': 0, 'PPP1R9B': 1, 'PRMT6': 10, 'PTGFRN': 0, 'PXDN': 2, 'QSOX2': 0, 'RMI2': 5, 'RNF126': 4, 'RRAGA': 1, 'SAPCD2': 0, 'SLC35E2B': 0, 'SMIM13': 0, 'SON': 89, 'SPEN': 18, 'SPEN-AS1': 0, 'TBC1D10B': 0, 'TMEM248': 0, 'TNFRSF1A': 12, 'TOB2': 2, 'WDR6': 1}

In [143]:
very_hiconf_df["hit"] = very_hiconf_df["gene_id"].apply(lambda x: count_dict[x])

In [144]:
very_hiconf_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density,hit
0,NM_001089:5961,ABCA3,2.685794,2.127319,0.655290,0.711017,1,293,296,GGACG,False,0.6536,280.0,0.952834,0.961819,NM_001089,4,6602.0,0.000606,2
8,NM_005736:1364,ACTR1A,2.895120,2.557538,0.803279,0.825807,1,488,493,GGACG,False,0.7918,490.0,0.977891,0.979900,NM_005736,2,2830.0,0.000707,0
15,NM_145290:3525,ADGRA3,2.676393,2.183380,0.695652,0.773499,-1,276,277,GGACG,False,0.6926,270.0,0.956869,0.960855,NM_145290,16,4577.0,0.003496,0
31,NM_032375:532,AKT1S1,3.016171,2.831370,0.890000,0.839323,1,100,101,GGACG,False,0.8750,96.0,0.814711,0.963261,NM_032375,3,2447.0,0.001226,0
119,NM_012121:1462,CDC42EP4,2.722056,2.492623,0.847926,0.826430,1,217,219,GGACG,False,0.8311,219.0,0.915679,0.951848,NM_012121,13,3098.0,0.004196,1
130,NM_001810:825,CENPB,3.157752,2.861978,0.842424,0.913360,-1,330,334,GGACG,False,0.8274,336.0,0.810287,0.982966,NM_001810,14,2890.0,0.004844,10
131,NM_001810:597,CENPB,2.901590,2.442747,0.739394,0.858509,1,330,335,GGACG,False,0.7407,324.0,0.810287,0.982966,NM_001810,14,2890.0,0.004844,10
160,NM_001849:3036,COL6A2,2.526744,2.022392,0.666667,0.760047,-1,492,508,GGACG,False,0.6875,496.0,0.859025,0.978112,NM_001849,2,3445.0,0.000581,4
169,NM_001319:1927,CSNK1G2,3.073604,2.681436,0.793151,0.893732,1,730,748,GGACG,False,0.7699,730.0,0.883239,0.986715,NM_001319,7,2895.0,0.002418,0
173,NM_006565:596,CTCF,2.630316,2.236568,0.745665,0.807812,1,173,173,GGACG,False,0.7314,175.0,0.895219,0.955317,NM_006565,8,3814.0,0.002098,367
237,NR_033338:3250,FAAP100,2.566943,2.320042,0.829114,0.905165,1,158,162,GGATT,False,0.8699,146.0,0.765022,0.959850,NR_033338,10,3793.0,0.002636,3
244,NM_001010924:1590,FAM171A1,2.697631,2.540684,0.892351,0.944195,1,353,364,GGACG,False,0.8914,350.0,0.931327,0.974568,NM_001010924,18,4182.0,0.004304,0
253,NM_014077:1189,FAM32A,2.416122,2.039284,0.731161,0.745549,1,491,500,GGACG,False,0.7271,491.0,0.993685,0.978013,NM_014077,6,1463.0,0.004101,1
277,NM_004472:1012,FOXD1,2.350945,2.097018,0.811224,0.847685,1,196,209,GGACG,False,0.7958,191.0,0.743961,0.969896,NM_004472,7,2512.0,0.002787,6
291,NM_003507:1754,FZD7,2.903024,2.854372,0.960784,0.955482,-1,255,260,GGACG,False,0.9569,255.0,0.640607,0.957196,NM_003507,21,4587.0,0.004578,17
312,NM_002067:1889,GNA11,3.297375,3.102891,0.897833,0.948511,-1,323,332,GGACG,False,0.8994,318.0,0.859025,0.972211,NM_002067,10,4190.0,0.002387,8
330,NM_018971:1373,GPR27,2.639808,2.553286,0.929825,0.947105,1,342,343,GGACG,False,0.9281,334.0,0.782416,0.966953,NM_018971,11,2642.0,0.004164,0
360,NM_012405:992,ICMT,3.128682,2.896143,0.874494,0.915624,-1,741,763,GGATT,False,0.8109,735.0,0.982596,0.981046,NM_012405,12,4795.0,0.002503,4
406,NM_014663:3515,KDM4A,2.755024,2.458995,0.813370,0.820826,1,359,367,GGACG,False,0.8034,356.0,0.959576,0.969385,NM_014663,3,4486.0,0.000669,17
410,NM_138346:1775,KIAA2013,2.651895,2.159449,0.693267,0.832076,-1,802,824,GGACG,False,0.7262,767.0,0.915679,0.973472,NM_138346,12,2819.0,0.004257,0
418,NM_001206:2071,KLF9,2.886841,2.702250,0.881579,0.883446,-1,76,77,GGAGA,False,0.8533,75.0,0.640607,0.951081,NM_001206,11,5201.0,0.002115,7
470,NM_002356:981,MARCKS,2.687683,2.330944,0.774051,0.916105,1,1133,1158,GGACG,False,0.7714,1146.0,0.576541,0.957839,NM_002356,5,4296.0,0.001164,33
482,NM_203304:1406,MEX3D,3.154321,2.909654,0.869159,0.938457,-1,107,109,GGACG,False,0.8316,95.0,0.576541,0.952153,NM_203304,10,3114.0,0.003211,0
492,NM_002417:980,MKI67,2.361893,2.026780,0.760563,0.711384,-1,71,78,GGACG,False,0.6623,77.0,0.940261,0.954839,NM_002417,34,12716.0,0.002674,14
493,NM_005934:4071,MLLT1,2.616506,2.448171,0.882883,0.931805,1,333,363,GGACG,False,0.8625,320.0,0.887216,0.967530,NM_005934,10,4532.0,0.002207,3
505,NM_003970:4846,MYOM2,3.106454,2.932258,0.900000,0.853199,-1,470,478,GGACG,False,0.8898,463.0,0.970848,0.973942,NM_003970,4,5008.0,0.000799,0
528,NM_022833:2141,NIBAN2,2.607689,2.079941,0.666667,0.656167,1,180,187,GGACG,False,0.6167,180.0,0.856260,0.960921,NM_022833,4,3942.0,0.001015,0
538,NM_020795:2743,NLGN2,2.652124,2.376987,0.824390,0.843307,1,205,217,GGACG,False,0.7958,191.0,0.942832,0.959940,NM_020795,10,4980.0,0.002008,2
541,NR_027451:446,NORAD,2.820073,2.798810,0.976190,0.000000,-3,42,42,GGACG,False,0.9767,43.0,0.903009,0.981985,NR_027451,7,5378.0,0.001302,13
548,NM_016588:691,NRN1,3.024294,2.833947,0.887097,0.910687,1,186,189,GGACG,False,0.8453,181.0,0.970470,0.957526,NM_016588,5,1582.0,0.003161,1
549,NM_004822:5645,NTN1,2.674269,2.066470,0.630573,0.655234,1,471,500,GGACG,False,0.5449,457.0,0.838750,0.974741,NM_004822,13,5986.0,0.002172,8
561,NM_022463:1426,NXN,3.109544,2.523765,0.694836,0.776929,-1,213,213,AGACG,False,0.7054,224.0,0.872315,0.955416,NM_022463,10,3045.0,0.003284,1
609,NM_032242:676,PLXNA1,3.140351,2.598445,0.724138,0.735075,1,116,117,GGACG,False,0.7155,116.0,0.969587,0.961144,NM_032242,15,9309.0,0.001611,2
618,NM_001387691:2841,POM121,2.724077,2.019772,0.573034,0.721154,-1,89,90,TGACG,False,0.5375,80.0,0.672280,0.955696,NM_001387691,10,5842.0,0.001712,3
620,NM_001099415:2912,POM121C,2.548580,2.005678,0.653710,0.746047,-1,283,303,TGACG,False,0.5694,288.0,0.965911,0.971090,NM_001099415,12,5867.0,0.002045,0
627,NM_014811:3615,PPP1R26,2.503581,2.037864,0.688889,0.698052,1,270,280,GGACG,False,0.6828,268.0,0.838750,0.960047,NM_014811,23,4951.0,0.004646,0
629,NM_032595:1281,PPP1R9B,3.205540,3.021730,0.902813,0.942157,1,391,421,GGACG,False,0.8854,314.0,0.928717,0.985364,NM_032595,7,4212.0,0.001662,1
633,NM_018137:1048,PRMT6,2.992098,2.888870,0.929530,0.957377,1,298,300,GGACG,False,0.9286,294.0,0.934120,0.955457,NM_018137,11,2621.0,0.004197,10
657,NM_020440:2956,PTGFRN,2.573867,2.258111,0.787286,0.819444,-1,409,422,GGACG,False,0.7798,386.0,0.944006,0.977461,NM_020440,15,6314.0,0.002376,0
665,NM_012293:3381,PXDN,2.325224,2.242015,0.928571,0.930413,1,182,199,GGATT,False,0.8192,177.0,0.846608,0.961275,NM_012293,15,6817.0,0.002200,2
666,NM_012293:3195,PXDN,2.871657,2.749361,0.915789,0.936917,1,190,193,GGACG,False,0.8969,194.0,0.846608,0.961275,NM_012293,15,6817.0,0.002200,2
668,NM_181701:1897,QSOX2,2.611960,2.160741,0.713816,0.802023,1,304,322,GGACG,False,0.7113,291.0,0.936381,0.964827,NM_181701,11,4501.0,0.002444,0
686,NM_152308:1117,RMI2,2.437597,2.024977,0.709677,0.830415,1,403,409,AGACG,False,0.6985,408.0,0.773724,0.973167,NM_152308,7,1427.0,0.004905,5
693,NM_194460:1334,RNF126,3.047968,2.770707,0.845779,0.933931,1,616,626,GGACG,False,0.8326,645.0,0.880872,0.979546,NM_194460,2,1631.0,0.001226,4
703,NM_006570:1335,RRAGA,3.165622,3.123860,0.968889,0.956867,1,450,455,GGACG,False,0.9581,453.0,0.975922,0.974379,NM_006570,3,1599.0,0.001876,1
710,NM_178448:3273,SAPCD2,2.511361,2.010625,0.666667,0.623418,1,387,398,GGACG,False,0.6447,380.0,0.864972,0.971066,NM_178448,10,3814.0,0.002622,0
764,NM_001290264:2192,SLC35E2B,3.047642,2.884313,0.904762,0.894169,1,63,65,GGACG,False,0.8852,61.0,0.933732,0.962849,NM_001290264,20,6434.0,0.003108,0
793,NM_001135575:1767,SMIM13,2.275729,2.025191,0.794118,0.837424,1,68,69,AGACG,False,0.7794,68.0,0.810287,0.958094,NM_001135575,11,4887.0,0.002251,0
810,NM_138927:3267,SON,2.415122,2.307777,0.910345,0.924502,1,145,154,GAACG,False,0.8561,132.0,0.880445,0.967464,NM_138927,36,8393.0,0.004289,89
812,NM_138927:3243,SON,2.401637,2.207457,0.851351,0.873767,1,148,154,GAACG,False,0.8045,133.0,0.880445,0.967464,NM_138927,36,8393.0,0.004289,89
817,NM_015001:741,SPEN,2.883851,2.833272,0.956522,0.923825,1,46,46,GGACG,False,0.9767,43.0,0.989251,0.983089,NM_015001,42,12385.0,0.003391,18
818,NR_024279:1171,SPEN-AS1,2.354381,2.308103,0.950495,0.000000,-3,101,107,GGACG,False,0.9619,105.0,0.970266,0.961737,NR_024279,8,2732.0,0.002928,0
819,NR_024279:2534,SPEN-AS1,2.452236,2.009451,0.691803,0.000000,-3,305,310,AGACG,False,0.6928,306.0,0.970266,0.961737,NR_024279,8,2732.0,0.002928,0
842,NM_015527:2724,TBC1D10B,3.381225,3.123083,0.873418,0.876744,1,474,487,GGACG,False,0.8655,476.0,0.859025,0.979900,NM_015527,14,3580.0,0.003911,0
881,NM_017994:1463,TMEM248,3.111821,2.652911,0.761364,0.843684,-1,528,533,GGACG,False,0.7638,525.0,0.891281,0.965272,NM_017994,7,4229.0,0.001655,0
887,NM_001065:1876,TNFRSF1A,2.635865,2.116341,0.674352,0.651300,-1,347,357,GGACG,False,0.6343,350.0,0.890068,0.954823,NM_001065,5,2171.0,0.002303,12
892,NM_016272:764,TOB2,2.869116,2.469243,0.773050,0.793662,1,141,142,GGATT,False,0.7246,138.0,0.948866,0.954460,NM_016272,11,4337.0,0.002536,2
943,NM_001320546:1148,WDR6,2.449718,2.092763,0.760000,0.699817,1,75,84,GGACG,False,0.7324,71.0,0.961468,0.974453,NM_001320546,21,4284.0,0.004902,1

In [145]:
gene_list = dorado_fail_df["gene_id"].unique()
count_dict = {gene: get_pubmed_count(gene) for gene in tqdm.tqdm(gene_list)}
dorado_fail_df["hit"] = dorado_fail_df["gene_id"].apply(lambda x: count_dict[x])
dorado_fail_df

  0%|                                                                                                                                                                      | 0/11 [00:00<?, ?it/s]
  9%|██████████████▎                                                                                                                                               | 1/11 [00:00<00:07,  1.36it/s]
 18%|████████████████████████████▋                                                                                                                                 | 2/11 [00:01<00:06,  1.37it/s]
 27%|███████████████████████████████████████████                                                                                                                   | 3/11 [00:02<00:06,  1.30it/s]
 36%|█████████████████████████████████████████████████████████▍                                                                                                    | 4/11 [00:03<00:05,  1.33it/s]
 45%|███████████████████████████████████████████████████████████████████████▊                                                                                      | 5/11 [00:03<00:04,  1.33it/s]
 55%|██████████████████████████████████████████████████████████████████████████████████████▏                                                                       | 6/11 [00:04<00:03,  1.33it/s]
 64%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                         | 7/11 [00:05<00:03,  1.33it/s]
 73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 8/11 [00:06<00:02,  1.32it/s]
 82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 9/11 [00:06<00:01,  1.31it/s]
 91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 10/11 [00:07<00:00,  1.31it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:08<00:00,  1.31it/s]
/tmp/ipykernel_75550/2078951856.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dorado_fail_df["hit"] = dorado_fail_df["gene_id"].apply(lambda x: count_dict[x])

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density,hit
125,NM_001410823:1309,CDV3,1.869049,1.671504,0.809524,0.678599,1,21,21,GGATT,False,0.0,0.0,0.747327,0.923029,NM_001410823,6,3361.0,0.001785,0
146,NR_171547:2308,CHPF2,2.214009,1.435382,0.380952,0.394277,1,21,21,GGACG,False,0.0,0.0,0.748113,0.921084,NR_171547,13,4206.0,0.003091,0
228,NM_001329090:805,EPHA2,1.608960,1.455806,0.818182,0.941250,-1,22,24,GCACT,False,0.0,0.0,0.872480,0.901347,NM_001329090,10,3878.0,0.002579,49
322,NM_001136557:2193,GPR107,1.787405,1.127730,0.333333,0.214130,1,24,24,GGACG,False,0.0,0.0,0.855416,0.908063,NM_001136557,4,6873.0,0.000582,0
387,NM_152405:308,JMY,1.766405,1.105077,0.333333,0.406751,-1,21,22,GGACG,False,0.0,0.0,0.797200,0.906464,NM_152405,14,9096.0,0.001539,4
390,NM_003724:2200,JRK,1.594822,1.524985,0.909091,0.764723,1,22,25,CAACT,False,0.0,0.0,0.633641,0.903382,NM_003724,15,9097.0,0.001649,2
393,NM_006766:777,KAT6A,1.793477,1.532469,0.750000,0.858974,-1,20,20,GAACG,False,0.0,0.0,0.810287,0.906464,NM_006766,27,9153.0,0.002950,9
408,NR_073498:1533,KHDRBS1,1.532830,0.994549,0.360000,0.545374,1,25,26,GGACG,False,0.0,0.0,0.920141,0.984606,NR_073498,1,2796.0,0.000358,2
488,NM_006077:1871,MICU1,1.987081,1.232901,0.318182,0.261607,1,22,22,GGATT,False,0.0,0.0,0.945733,0.916782,NM_006077,3,2363.0,0.001270,43
552,NM_001278209:2701,NUP153,1.899402,1.336646,0.480000,0.231919,1,25,25,ATACT,False,0.0,0.0,0.906337,0.935234,NM_001278209,15,6119.0,0.002451,21
888,NM_001346092:1994,TNFRSF1A,2.074902,1.581490,0.600000,0.651300,-1,20,21,GGACG,False,0.0,0.0,0.827070,0.936626,NM_001346092,2,2289.0,0.000874,12

In [148]:
neg_df = select_df[(select_df["log_pm6a"] == 0.0) & (select_df["dom"] == 0.0) & ((select_df["label"] == 0 )|( select_df["label"] == -3)) & (~select_df["drach"]) & (select_df["cell_perc"] > 0.9)].copy().sort_values("gene_id")
print(neg_df)

                label_id gene_id  log_pm6a  noisy_or  dom  dom_label  label  \
10894242   NM_015665:557    AAAS       0.0      -0.0  0.0   0.000000     -3
10894038  NM_015665:1283    AAAS       0.0      -0.0  0.0   0.000000     -3
10894053  NM_015665:1324    AAAS       0.0      -0.0  0.0   0.000000     -3
10894065  NM_015665:1390    AAAS       0.0      -0.0  0.0   0.000000     -3
10894068  NM_015665:1395    AAAS       0.0      -0.0  0.0   0.043657     -3
...                  ...     ...       ...       ...  ...        ...    ...
10561478  NM_015113:1893   ZZEF1       0.0      -0.0  0.0   0.000000      0
10561480   NM_015113:190   ZZEF1       0.0      -0.0  0.0   0.000000      0
10561481  NM_015113:1904   ZZEF1       0.0      -0.0  0.0   0.000000      0
10561472  NM_015113:1883   ZZEF1       0.0      -0.0  0.0   0.000000      0
10561974  NM_015113:3828   ZZEF1       0.0      -0.0  0.0   0.000000      0

          count_dom  count_all   5mer  drach  pred_dorado  count_dorado  \
10894242        506        508  AGATC  False       0.0020         510.0
10894038        528        530  AGATC  False       0.0000         532.0
10894053        534        536  AGAGG  False       0.0019         520.0
10894065        506        511  TGAAA  False       0.0020         488.0
10894068        511        522  GGAAA  False       0.0000         502.0
...             ...        ...    ...    ...          ...           ...
10561478         23         23  GAATT  False       0.0000          22.0
10561480         20         22  CGAGG  False       0.0000           0.0
10561481         22         23  CGACG  False       0.0000          24.0
10561472         23         24  ACACA  False       0.0000          23.0
10561974         41         41  GAAGT  False       0.0000          38.0

          ivt_perc  cell_perc     refseq
10894242  0.988863   0.981754  NM_015665
10894038  0.988863   0.981754  NM_015665
10894053  0.988863   0.981754  NM_015665
10894065  0.988863   0.981754  NM_015665
10894068  0.988863   0.981754  NM_015665
...            ...        ...        ...
10561478  0.859025   0.930025  NM_015113
10561480  0.859025   0.930025  NM_015113
10561481  0.859025   0.930025  NM_015113
10561472  0.859025   0.930025  NM_015113
10561974  0.859025   0.930025  NM_015113

[894044 rows x 16 columns]

In [149]:
from Bio import SeqIO
fasta = "/extdata4/baeklab/Hyeonseo/m6A/res/ref/isoform/hg38_rna_nrnm.fasta"
seq_dict = SeqIO.to_dict(SeqIO.parse(fasta, "fasta"))
seq_dict = {key.split(".")[0]: str(value.seq) for key, value in seq_dict.items()}

In [197]:
refseq_list = [
               "NM_006565",
               "NM_138927",
               "NM_138927",
               "NM_002417",
               "NR_027451",
               "NM_018137",
               "NM_001329090",
               "NM_006766",
               "NM_006077",
               "NM_001278209",
               "NM_001346092",
               "NR_073498",
               ]

pos_list = [
            596,
            3267,
            3243,
            980,
            446,
            1048,
            805,
            777,
            1871,
            2701,
            1994,
            1533]

In [209]:
import RNA
final_df_list = []
for refseq, pos in tqdm.tqdm(zip(refseq_list, pos_list), total=len(refseq_list)):
    refseq_df = neg_df[neg_df["refseq"] == refseq].copy()
    refseq_df["pos"] = refseq_df["label_id"].str.split(":").str[1].astype(int)
    seq = seq_dict[refseq].seq
    refseq_df = refseq_df[(refseq_df["pos"]>50) & (refseq_df["pos"]<(len(seq)-51))]
    refseq_df = refseq_df[(refseq_df["pos"]>pos-200) & (refseq_df["pos"]<(pos+201))].copy()
    refseq_df["seq"] = refseq_df["pos"].apply(lambda x: str(seq[x-50:x+51]))
    refseq_df["mfe"] = refseq_df["seq"].apply(lambda x: RNA.fold(x)[1])
    final_df_list.append(refseq_df)
    if len(refseq_df) == 0:
        raise ValueError("No data")
final_df = pd.concat(final_df_list)
final_df

  0%|                                                                                                                                                                      | 0/12 [00:00<?, ?it/s]
  8%|█████████████▏                                                                                                                                                | 1/12 [00:00<00:03,  3.43it/s]
 17%|██████████████████████████▎                                                                                                                                   | 2/12 [00:00<00:02,  4.37it/s]
 25%|███████████████████████████████████████▌                                                                                                                      | 3/12 [00:00<00:01,  4.91it/s]
 33%|████████████████████████████████████████████████████▋                                                                                                         | 4/12 [00:01<00:02,  3.30it/s]
 42%|█████████████████████████████████████████████████████████████████▊                                                                                            | 5/12 [00:01<00:02,  3.26it/s]
 50%|███████████████████████████████████████████████████████████████████████████████                                                                               | 6/12 [00:01<00:01,  3.89it/s]
 58%|████████████████████████████████████████████████████████████████████████████████████████████▏                                                                 | 7/12 [00:01<00:01,  3.66it/s]
 67%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                    | 8/12 [00:02<00:01,  3.72it/s]
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 9/12 [00:02<00:00,  3.27it/s]
 83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 10/12 [00:03<00:00,  2.78it/s]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 11/12 [00:03<00:00,  3.25it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.37it/s]

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,pos,seq,mfe
9345625,NM_006565:403,CTCF,0.0,-0.0,0.0,0.0,0,160,166,AGAGA,False,0.0000,174.0,0.895219,0.955317,NM_006565,403,TGGAGGAGTCCGAAACTTTTATTAAAGGAAAGGAGAGAAAGACTTA...,-22.200001
9345698,NM_006565:635,CTCF,0.0,-0.0,0.0,0.0,0,174,176,GGAGG,False,0.0114,176.0,0.895219,0.955317,NM_006565,635,GGCTGCTGTGGACGATACCCAGATTATAACTTTACAGGTTGTAAAT...,-20.600000
9345708,NM_006565:657,CTCF,0.0,-0.0,0.0,0.0,0,168,174,GGAGA,False,0.0234,171.0,0.895219,0.955317,NM_006565,657,ATTATAACTTTACAGGTTGTAAATATGGAGGAACAGCCCATAAACA...,-22.299999
9345729,NM_006565:741,CTCF,0.0,-0.0,0.0,0.0,0,174,175,GAAAA,False,0.0000,178.0,0.895219,0.955317,NM_006565,741,ACTGTACCTGTTGCTACCACTTCAGTAGAAGAACTTCAGGGGGCTT...,-18.600000
9345732,NM_006565:746,CTCF,0.0,-0.0,0.0,0.0,0,176,177,TGAAG,False,0.0061,163.0,0.895219,0.955317,NM_006565,746,ACCTGTTGCTACCACTTCAGTAGAAGAACTTCAGGGGGCTTATGAA...,-18.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15518876,NR_073498:1720,KHDRBS1,0.0,-0.0,0.0,0.0,0,43,44,GTATG,False,0.0000,22.0,0.920141,0.984606,NR_073498,1720,CTTCTTCTCCCCACCTTATTCCATTCTTAACTCTGCATTCTGGCTT...,-11.700000
15518875,NR_073498:1706,KHDRBS1,0.0,-0.0,0.0,0.0,0,44,44,GCATT,False,0.0000,22.0,0.920141,0.984606,NR_073498,1706,TTCTTCGTGGTCCCCTTCTTCTCCCCACCTTATTCCATTCTTAACT...,-12.100000
15518878,NR_073498:1727,KHDRBS1,0.0,-0.0,0.0,0.0,0,44,44,GTATT,False,0.0000,22.0,0.920141,0.984606,NR_073498,1727,TCCCCACCTTATTCCATTCTTAACTCTGCATTCTGGCTTCTGTATG...,-11.700000
15518879,NR_073498:1732,KHDRBS1,0.0,-0.0,0.0,0.0,0,44,44,TTAAA,False,0.0000,24.0,0.920141,0.984606,NR_073498,1732,ACCTTATTCCATTCTTAACTCTGCATTCTGGCTTCTGTATGTAGTA...,-12.900000
15518877,NR_073498:1724,KHDRBS1,0.0,-0.0,0.0,0.0,0,43,44,GTAGT,False,0.0000,21.0,0.920141,0.984606,NR_073498,1724,TTCTCCCCACCTTATTCCATTCTTAACTCTGCATTCTGGCTTCTGT...,-11.700000

In [224]:
very_hiconf_df = hiconf_df[(hiconf_df["log_pm6a"] > np.percentile(select_df["log_pm6a"],99.8)) & (hiconf_df["cell_perc"] > 0.92)].copy()

exclude_gene = [
    "MKI67",
    "NTN1",
    "RMI2",
    "MICU1",
    "KAT6A",
    "TNFRSF1A",
    "KHDRBS1",
    "CDV3",
    "PRMT6",
    "KDM4A",
    "CENPB",
    "PXDN",
                ]
very_hiconf_df = very_hiconf_df[~very_hiconf_df["gene_id"].isin(exclude_gene)]
very_hiconf_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density
5,NM_001089:5961,ABCA3,2.685794,2.127319,0.655290,0.711017,1,293,296,GGACG,False,0.6536,280.0,0.952834,0.961819,NM_001089,4.0,6602.0,0.000606
27,NM_005736:1364,ACTR1A,2.895120,2.557538,0.803279,0.825807,1,488,493,GGACG,False,0.7918,490.0,0.977891,0.979900,NM_005736,2.0,2830.0,0.000707
37,NM_001116:4959,ADCY9,3.524732,3.454622,0.960000,0.957745,1,150,150,GGACG,False,0.9252,147.0,0.830193,0.932333,NM_001116,21.0,7980.0,0.002632
38,NM_001116:4608,ADCY9,3.266177,3.231568,0.973684,0.962620,1,152,153,GGACG,False,0.9536,151.0,0.830193,0.932333,NM_001116,21.0,7980.0,0.002632
44,NM_145290:3525,ADGRA3,2.676393,2.183380,0.695652,0.773499,-1,276,277,GGACG,False,0.6926,270.0,0.956869,0.960855,NM_145290,16.0,4577.0,0.003496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,NM_001171135:2355,ZBED1,2.640257,2.618904,0.973684,0.000000,-3,38,40,GGACG,False,0.9706,34.0,0.820890,0.945790,NM_001171135,30.0,4653.0,0.006447
2897,NM_181842:922,ZBTB12,2.861479,2.715035,0.902985,0.957345,1,134,136,GGAGG,False,0.8397,131.0,0.000000,0.922773,NM_181842,6.0,1963.0,0.003057
2918,NM_015168:3833,ZC3H4,2.721331,2.046289,0.590000,0.752688,1,100,104,GGACG,False,0.5816,98.0,0.859025,0.944513,NM_015168,27.0,6143.0,0.004395
2958,NM_003575:2234,ZNF282,3.129509,2.669289,0.761905,0.718320,1,273,276,GGACG,False,0.7547,265.0,0.731175,0.933231,NM_003575,10.0,3651.0,0.002739
2995,NM_023926:2063,ZSCAN18,2.756144,2.249168,0.701754,0.778869,-1,57,63,GGACG,False,0.7083,48.0,0.817941,0.948312,NM_023926,3.0,2783.0,0.001078

In [225]:

data_df = very_hiconf_df.copy().reset_index(drop=True)
data_df["pos"] = data_df["label_id"].str.split(":").str[1].astype(int)
## filter out pos within 100 bp from the edge
data_df = data_df[(data_df["pos"]>100) & (data_df["pos"]<data_df["refseq"].apply(lambda x: len(seq_dict[x])-100))].copy()

up_seq= "tagccagtaccgtagtgcgtg".upper()
down_seq = "cagaggctgagtcgctgcat".upper()

data_df["up_probe_30"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+31]), axis=1)
data_df["down_probe_30"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-30:x["pos"]])+down_seq, axis=1)
data_df["up_probe_25"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+26]), axis=1)
data_df["down_probe_25"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-25:x["pos"]])+down_seq, axis=1)
data_df["up_probe_20"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+21]), axis=1)
data_df["down_probe_20"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-20:x["pos"]])+down_seq, axis=1)

from Bio.SeqUtils import MeltingTemp as mt
tmfunc = (lambda x: mt.Tm_NN(x, saltcorr=6, nn_table=mt.DNA_NN4))
data_df["tm_up_30"] = data_df["up_probe_30"].apply(tmfunc)
data_df["tm_down_30"] = data_df["down_probe_30"].apply(tmfunc)
data_df["tm_up_25"] = data_df["up_probe_25"].apply(tmfunc)
data_df["tm_down_25"] = data_df["down_probe_25"].apply(tmfunc)
data_df["tm_up_20"] = data_df["up_probe_20"].apply(tmfunc)
data_df["tm_down_20"] = data_df["down_probe_20"].apply(tmfunc)


data_df["tm_max"] = data_df[["tm_up_30", "tm_down_30", "tm_up_25", "tm_down_25", "tm_up_20", "tm_down_20"]].max(axis=1)

data_df = data_df[data_df["tm_max"] < 80].copy()
data_df.drop(columns=["noisy_or", "tm_up_30", "tm_down_30", "tm_up_25", "tm_down_25", "tm_up_20", "tm_down_20",
                      "up_probe_25", "down_probe_25", "up_probe_20", "down_probe_20"
                      ], inplace=True)

repeats = ["A"*5, "C"*5, "G"*5, "T"*5]
data_df["seq"] = data_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-30:x["pos"]+31], axis=1)
data_df["has_repeat"] = data_df["seq"].apply(lambda x: any([repeat in x for repeat in repeats]))
data_df= data_df[~data_df["has_repeat"]]
data_df ["gene_id"].value_counts()
very_hiconf_df = data_df.copy()

very_hiconf_df

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,refseq,m6a_count,transcript_length,m6a_density,pos,up_probe_30,down_probe_30,tm_max,seq,has_repeat
5,NM_014913:3321,ADNP2,2.610246,0.716867,0.639166,-1,166,170,GGACG,False,...,NM_014913,32.0,5157.0,0.006205,3321,TAGCCAGTACCGTAGTGCGTGGGATCTAATGCTAAAATCTGAAGAG...,CCTTGACAATAGGTCCCTCTGTTCTGCTTTCAGAGGCTGAGTCGCT...,72.690258,AAAGCAGAACAGAGGGACCTATTGTCAAGGACGAGGCTCTTCAGAT...,False
8,NM_032375:481,AKT1S1,2.408016,0.666667,0.650000,-1,93,96,GGACG,False,...,NM_032375,3.0,2447.0,0.001226,481,TAGCCAGTACCGTAGTGCGTGCCACAGTAAACGAAGGCAAGCGACC...,CCCTGACCCACAATAAACTTCTTCGACAAACAGAGGCTGAGTCGCT...,76.384300,TTTGTCGAAGAAGTTTATTGTGGGTCAGGGACGTCAGGTCGCTTGC...,False
14,NM_013275:2171,ANKRD11,2.668826,0.674419,0.748822,1,43,46,GGACG,False,...,NM_013275,27.0,9301.0,0.002903,2171,TAGCCAGTACCGTAGTGCGTGAGGAGTAGTCAGACTCGCTTGTCAG...,CCTTGTGGAGTCTGATAAAGAACTGACCTCCAGAGGCTGAGTCGCT...,73.494963,GAGGTCAGTTCTTTATCAGACTCCACAAGGACGAGACTGACAAGCG...,False
15,NM_001256183:2168,ANKRD11,2.641805,0.696970,0.748822,1,33,38,GGACG,False,...,NM_001256183,29.0,9298.0,0.003119,2168,TAGCCAGTACCGTAGTGCGTGAGGAGTAGTCAGACTCGCTTGTCAG...,CCTTGTGGAGTCTGATAAAGAACTGACCTCCAGAGGCTGAGTCGCT...,73.494963,GAGGTCAGTTCTTTATCAGACTCCACAAGGACGAGACTGACAAGCG...,False
16,NM_001006634:3184,ARHGAP17,3.434832,0.936508,0.894110,1,126,129,GGACG,False,...,NM_001006634,5.0,3495.0,0.001431,3184,TAGCCAGTACCGTAGTGCGTGAGCCTCCCTCCTAATACATAAGAAT...,CCAGGTAGCAGAGAGTAGGCGACTTGCATACAGAGGCTGAGTCGCT...,74.771050,TATGCAAGTCGCCTACTCTCTGCTACCTGGACGTTCATTCTTATGT...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,NM_030775:1378,WNT5B,3.130428,0.939130,0.925638,1,115,118,AGACG,False,...,NM_030775,15.0,2184.0,0.006868,1378,TAGCCAGTACCGTAGTGCGTGGCAAAGTCCACTCCTCAGAGATCTC...,CTCTTAAATAAGCTCTTCCTTTCCATTTTCCAGAGGCTGAGTCGCT...,75.835004,GAAAATGGAAAGGAAGAGCTTATTTAAGAGACGCTGGAGATCTCTG...,False
188,NM_032642:1431,WNT5B,3.130807,0.958904,0.925638,1,146,148,AGACG,False,...,NM_032642,15.0,2238.0,0.006702,1431,TAGCCAGTACCGTAGTGCGTGGCAAAGTCCACTCCTCAGAGATCTC...,CTCTTAAATAAGCTCTTCCTTTCCATTTTCCAGAGGCTGAGTCGCT...,75.835004,GAAAATGGAAAGGAAGAGCTTATTTAAGAGACGCTGGAGATCTCTG...,False
189,NM_016258:1442,YTHDF2,2.736059,0.733711,0.768524,1,353,355,GGACG,False,...,NM_016258,17.0,2744.0,0.006195,1442,TAGCCAGTACCGTAGTGCGTGATATTATACTTAATGGAACGGTGAA...,CCTCAGAGTAGCTCTTAATGATGAAAACCCCAGAGGCTGAGTCGCT...,71.607184,GGGTTTTCATCATTAAGAGCTACTCTGAGGACGATATTCACCGTTC...,False
191,NM_001173128:1521,YTHDF2,2.713925,0.732759,0.768524,1,116,119,GGACG,False,...,NM_001173128,17.0,2823.0,0.006022,1521,TAGCCAGTACCGTAGTGCGTGATATTATACTTAATGGAACGGTGAA...,CCTCAGAGTAGCTCTTAATGATGAAAACCCCAGAGGCTGAGTCGCT...,71.607184,GGGTTTTCATCATTAAGAGCTACTCTGAGGACGATATTCACCGTTC...,False
194,NM_001171135:4087,ZBED1,2.405275,0.765625,0.000000,-3,64,66,GAACG,False,...,NM_001171135,30.0,4653.0,0.006447,4087,TAGCCAGTACCGTAGTGCGTGGCTGAGTGGGGTCATCCCTCCTAGA...,TCTCCCCAGCCCAGCTTGTCTTCACGGAGGCAGAGGCTGAGTCGCT...,79.857620,CCTCCGTGAAGACAAGCTGGGCTGGGGAGAACGGTGTCTAGGAGGG...,False

In [226]:
very_hiconf_df["pos"] = very_hiconf_df["label_id"].str.split(":").str[1].astype(int)

## SET PATH for module import
sys.path.append("/extdata4/baeklab/Hyeonseo/m6A/modformer")
from utils.utils import revcomp_DNA

very_hiconf_df["up_probe"] = very_hiconf_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+31], axis=1)
very_hiconf_df["down_probe"] = very_hiconf_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-30:x["pos"]], axis=1)

In [227]:
up_probe_fasta = "\n".join([f">{label_id}\n{seq}" for label_id, seq in zip(very_hiconf_df["label_id"], very_hiconf_df["up_probe"])])
print(up_probe_fasta)

>NM_014913:3321
CGAGGCTCTTCAGATTTTAGCATTAGATCC
>NM_032375:481
CGTCAGGTCGCTTGCCTTCGTTTACTGTGG
>NM_013275:2171
CGAGACTGACAAGCGAGTCTGACTACTCCT
>NM_001256183:2168
CGAGACTGACAAGCGAGTCTGACTACTCCT
>NM_001006634:3184
CGTTCATTCTTATGTATTAGGAGGGAGGCT
>NM_004491:2100
CGCTAAGATTGAGCACTTGATTAGTTCTCG
>NM_024585:1771
CGCAGTGAGTGTTGCTCAAGGGAGTCAGGA
>NM_032047:1365
CGATGTGTTCATGGGCCTCTGTGCCAATAA
>NM_005180:1768
CGTTAATTGAAAAGAAAGATTGTTGTTATA
>NM_138793:2815
CGTTTCCATCATTCACAGTGCCCTCCCCAC
>NM_015005:2554
CGCTGTGTTATCTAGGAAACCGCTTGCGGC
>NM_004854:1260
CGATGCCCCATACATCTTAAAAGAGGCTGG
>NM_018714:1651
CGTTTCTCCCACACAGGCCAAGAGTTCTGC
>NM_006565:596
CGATACCCAGATTATAACTTTACAGGTTGT
>NM_032656:3836
CGCTGTTCTGTTCAGTGTGCTCTTTGGACT
>NM_014908:1815
TTTTGGGGTCCATCAGCACTGTGTCCCTCC
>NR_033338:3250
TTTCTGGGGTTTGGACTTGGGGTGAGTTTG
>NM_001010924:1590
CGCTGGGGAAAGACTACCATAAGTCAGTGG
>NM_020223:2709
CGTGTACACAGATGCCAATCACCTACCAAA
>NM_003468:1682
CGCTTCCGCTATCCTGAGCGCCCCATCATC
>NM_002048:1328
CGAATGCCGCACCGTCATTGAGGACATGCT
>NM_003272:1305
CGATTCCTCAGATGAAAAGCTTCAGAAAAG
>NM_018971:1379
CGTTGTATCTTTTCCTTCTGGCCCCTGTTT
>NM_004807:1223
CGTTCAACCTCAAGTTCATCCGGCCCTTCA
>NM_012405:992
TTTTCTTAATCGTTTTATGTCATTAGTCAC
>NM_004907:1337
CGTGAACCTTTCGCTCTCCTTCTGGACTGG
>NM_000875:9375
CGTTCTCCCACACAGCCCTTCCCTGAGGCA
>NM_001291858:9372
CGTTCTCCCACACAGCCCTTCCCTGAGGCA
>NM_015483:1790
CGATGGTAAGCCCTTTACCTTGTGCTTGGC
>NM_015353:1176
CGCTGGAGCCAAGAGGATTGTTCCCGTGCC
>NM_015353:1241
CGTTAGCAGCTGCTTCGGAACACCGTCCCT
>NM_014851:2195
CGATGACTTGGGAGGGACGCGTGAAGGGAG
>NM_015627:1614
CGATACAGCTTGGCACTTTAAAGCATTAAC
>NM_004789:1781
CTCTTACCAACCTTTTCTAATGACTCGCAA
>NM_014916:6647
CGTTGCCAGAGAGTGCGCAGCAAATGACCT
>NM_138699:1421
CGGTTGGTCTTGAAGAGTGGCAGTGTGTGG
>NM_145021:1545
TATGGAATCTGTCATTCCGACACAAACTCT
>NM_018019:1579
CGTTTTATTTGTGTGCTCTCCCTTGACTGT
>NM_018019:971
CGAATTAAGCCTGCACTCATATGGCATAGA
>NM_001543:398
CGATTCTCGTGTCTCCTCCTGTGTGGGGCC
>NM_030759:991
TTTATGAATAATTAAAATGGAAGGCCACAG
>NM_016588:691
CGTTGTGATTCTCTGTGATGCTGAAAACAC
>NM_005124:2717
TTGTGATACCTGTTTAGTGCAAAATAAACC
>NM_001278209:2810
TTGTGATACCTGTTTAGTGCAAAATAAACC
>NM_005392:3674
CGTCTTTTCTCAAGTTGCTAAGAGTGATCT
>NM_014602:1875
CGTTGACCAAAGTTCTTGCTCTCGTCAAAG
>NM_032242:7237
CGATTTGAACAAGAAAATGAAGGCAGTGGG
>NM_032242:1108
CGACCCCAAATTCTACTCGTACGTTGAGTT
>NM_012406:1083
CGGTGTTGCAGGCGAGCATTCCCAAATCCC
>NM_194460:1334
CGTTTGAGCTCACGTGGCGGCCATGCATGG
>NM_006570:1335
CGCTATTTACTCAGCTACCCAGTAGAGCTT
>NM_016240:1342
CGCATGGCTTCTCACGAGATTGAAATTGGC
>NM_017841:583
CGTTAGCCTTGCTTCCGGCTTCTTAGATGC
>NM_006598:3539
CGATTTCCTTGCATCTGAGGGCAGACGCTG
>NM_031212:1043
CGGTATATCAAGTAGGTGGGGTGACCGCCT
>NM_031212:807
CGTTCCTTTCCAAGCCATTCACTTCATGAC
>NM_006931:1729
CGCTTCTGAATGCTGCTACTTAATTCCTTT
>NM_138927:3243
CGCTCCATGATGTCAGCTTATGAACGCTCC
>NM_138927:3267
CGCTCCATGATGTCCCCAATGGCTGATCGA
>NR_024279:2534
CGTTGGTTTTCATTGGCTGGCCATTAAGCA
>NM_173216:4332
CGTTATCATTGGTCTGGTGAGATGTTTCAT
>NM_014409:1486
CGTACCCGCTGAGGATATATGCAGGACACC
>NM_007024:678
CGTGGCCATCAGCCTGACAACGGTGGTGGT
>NM_017994:1463
CGTTTCCACGTGTCTCTAGAGAAGGATTCC
>NM_016272:764
TTGATCCCTTTGAGGTGTCCTACCAGATTG
>NM_012288:1898
CGTGACAACTCAATCCAGAAGGATGGTGTG
>NM_178014:1365
CGAGATGGAGTTCACCGAGGCTGAGAGCAA
>NM_175852:1914
TTTTGTGGGTCAGTTTTACGTACATAGGGC
>NM_014823:6074
CGTTTTCAGGTGACAACTACAGCAAACAAA
>NM_030775:1378
CGCTGGAGATCTCTGAGGAGTGGACTTTGC
>NM_032642:1431
CGCTGGAGATCTCTGAGGAGTGGACTTTGC
>NM_016258:1442
CGATATTCACCGTTCCATTAAGTATAATAT
>NM_001173128:1521
CGATATTCACCGTTCCATTAAGTATAATAT
>NM_001171135:4087
CGGTGTCTAGGAGGGATGACCCCACTCAGC

In [228]:
down_probe_fasta = "\n".join([f">{label_id}\n{seq}" for label_id, seq in zip(very_hiconf_df["label_id"], very_hiconf_df["down_probe"])])
print(down_probe_fasta)

>NM_014913:3321
AAAGCAGAACAGAGGGACCTATTGTCAAGG
>NM_032375:481
TTTGTCGAAGAAGTTTATTGTGGGTCAGGG
>NM_013275:2171
GAGGTCAGTTCTTTATCAGACTCCACAAGG
>NM_001256183:2168
GAGGTCAGTTCTTTATCAGACTCCACAAGG
>NM_001006634:3184
TATGCAAGTCGCCTACTCTCTGCTACCTGG
>NM_004491:2100
AGACATGCCCCAGCTGCCCAGCTTGTGTGG
>NM_024585:1771
CCAGAAGTGTATCCCACGAGGGCATCAGGG
>NM_032047:1365
CACAGACACTAAATTCAAGTCTTTACATAG
>NM_005180:1768
AAAGATGGACTACATGTGATACTCCTATGG
>NM_138793:2815
CAGGTTAGGCACGACCCAGGCTGAGAAGGG
>NM_015005:2554
CCTCTTTCTTCATTGGGGACCAGAATGGGG
>NM_004854:1260
GTGTGATTGGACACCACGAGACCCTGGAGG
>NM_018714:1651
TCCCCTCTGATGACTCATCACTGCCCAAGG
>NM_006565:596
CAGTGGCTCCAGAAGCAGAGGCTGCTGTGG
>NM_032656:3836
GGTGGATGATGATTTCATCTCACGTGCTGG
>NM_014908:1815
GGAGTGGACCTAAACTACAGTTATGCTTGG
>NR_033338:3250
ATTCTGGACCCGGAGGGCCAGAGAAACAGG
>NM_001010924:1590
ATCTCCTTTGATAACCTCACTCCAAGTGGG
>NM_020223:2709
TATATTTGATGAATAAGTATATAAACAGAG
>NM_003468:1682
CACAGTGGCCACCTTCCTCATCGACATGGA
>NM_002048:1328
GCAAAGTCTTCAACGGGCTGCGCTGCACGG
>NM_003272:1305
CTTGGGTAGCATCAGTTAACAGTTTTATGG
>NM_018971:1379
ACCCAGCCTTTCCCTTTGGCTCGGACGGTG
>NM_004807:1223
CAGCGCAAGACGCAGTACCTGTTCGAGCGG
>NM_012405:992
AACTGTTTCCGGTTGGCCGCTGCCACATGG
>NM_004907:1337
CGCCCACAGGTGCTGTCTTAGTGGACTGGG
>NM_000875:9375
GCACATCATGGAATTGATGTGAGCATTAAG
>NM_001291858:9372
GCACATCATGGAATTGATGTGAGCATTAAG
>NM_015483:1790
GAAAGATACGACACTGAGAAAGATGAGTGG
>NM_015353:1176
AGCTCCTTGGAAATGGCCTGTACTTTAAGG
>NM_015353:1241
CATGGTTTCACCCTATGTGTGCCACAATGG
>NM_014851:2195
TGCACCTACTTGTTCCCACCTTGGGAGAGG
>NM_015627:1614
TAGAGACTAAGGGGCAGCTCCTGACCAAAG
>NM_004789:1781
GGCCATGAGCCTCACAGCCCCTCACAAACG
>NM_014916:6647
AAGTTGAGTCCTAGTGCAAAATGCAGGCGG
>NM_138699:1421
ACTTTGGATGAGATTAAGAAGGCCCAGTGG
>NM_145021:1545
AACAGAGCCCAACTTTGAAAATAAACATGG
>NM_018019:1579
CCCCAGCTTCCCTGATTTCTTCCAGATGGG
>NM_018019:971
TTCTTGAAACATTTGCATAGAATTCACTGG
>NM_001543:398
CTAAGTCTCTGTGAATTTGTTGGTCAGTGG
>NM_030759:991
TATGGAGCTCTCTGAGGATATTCTGAAAGG
>NM_016588:691
TCGAGAGGAAGATCCATTAGTTCTTTGGGG
>NM_005124:2717
ACAAATTTAAACCAGTGATAGGCACTTGGG
>NM_001278209:2810
ACAAATTTAAACCAGTGATAGGCACTTGGG
>NM_005392:3674
GCCCAGCGTGGCCCCTCAATTTGAAAATGG
>NM_014602:1875
GTTCCTAGGGTGAGGGCTGAAGCCTTGAGG
>NM_032242:7237
TGTACAGTTAACTGAAGAAGAATTTTAAAG
>NM_032242:1108
TCACGTCCAAGATCGTGCGGCTCTGTGTGG
>NM_012406:1083
CAGATGGAATGGCAGAGGAGCTTACGATGG
>NM_194460:1334
TTTAAATTATTACTGCTTTGAAATAAACGG
>NM_006570:1335
CTCCCCGCTTCCCCAGTCTTTAAACATTGG
>NM_016240:1342
CACTGTGGAGAGGTTTGAGTCTCTGGAAGG
>NM_017841:583
CAGTCTGTGGATGGTAACTACTTATGATGG
>NM_006598:3539
AACAGGCTCAGCAAATCAGGGCGTGGCTGG
>NM_031212:1043
CATATCACAGGCATGGCTAGTGCCTTCAGG
>NM_031212:807
ACCGCAGCTACACCACCCAGCTGACCATGA
>NM_006931:1729
AGGGAGAGACCTCATCAGGATGAACCCAGG
>NM_138927:3243
GGCTGAGCGCTCTATGATGTCAGCTTATGA
>NM_138927:3267
TTATGAACGCTCCATGATGTCAGCTTATGA
>NR_024279:2534
TTGACGTGCTGAAAGACGGAGTAGAATGAG
>NM_173216:4332
CACTTTGGTAAAATGCAAATTATGATATGG
>NM_014409:1486
CGCACCGCCAGGCTGTGGTCATTTGATCGG
>NM_007024:678
CCCATGGGCTGATGGAGCAGCATGTGTGGG
>NM_017994:1463
CACCTTGGACTTGAGGACCTACCTGATGGG
>NM_016272:764
GCCAATGTGCCTGAGGAGCTGAGTGTCTGG
>NM_012288:1898
GTTGTAAATGCCAAGGCATTTGGCTTTGGG
>NM_178014:1365
TCCTCCACTGGTACACAGGCGAGGGCATGG
>NM_175852:1914
CTGGCTGGCATCTGGCACTTGCAATTTTGG
>NM_014823:6074
GTCAGACACTGGGCAGCCTACCAAGGTTGG
>NM_030775:1378
GAAAATGGAAAGGAAGAGCTTATTTAAGAG
>NM_032642:1431
GAAAATGGAAAGGAAGAGCTTATTTAAGAG
>NM_016258:1442
GGGTTTTCATCATTAAGAGCTACTCTGAGG
>NM_001173128:1521
GGGTTTTCATCATTAAGAGCTACTCTGAGG
>NM_001171135:4087
CCTCCGTGAAGACAAGCTGGGCTGGGGAGA

In [214]:
very_hiconf_df = hiconf_df[(hiconf_df["log_pm6a"] > np.percentile(select_df["log_pm6a"],99.8)) & (hiconf_df["cell_perc"] > 0.90)].copy()
very_hiconf_df

exclude_gene = [
    "MKI67",
    "NTN1",
    "RMI2",
    "MICU1",
    "KAT6A",
    "TNFRSF1A",
    "KHDRBS1",
    "CDV3",
    "PRMT6",
    "KDM4A",
    "CENPB",
    "PXDN",
]
very_hiconf_df = very_hiconf_df[~very_hiconf_df["gene_id"].isin(exclude_gene)]
very_hiconf_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density
5,NM_001089:5961,ABCA3,2.685794,2.127319,0.655290,0.711017,1,293,296,GGACG,False,0.6536,280.0,0.952834,0.961819,NM_001089,4.0,6602.0,0.000606
14,NM_198147:462,ABHD15,2.393320,2.227509,0.872642,0.942997,-1,212,229,GGACG,False,0.8122,197.0,0.810287,0.919411,NM_198147,29.0,3492.0,0.008305
16,NM_198147:1838,ABHD15,2.998586,2.858266,0.912698,0.950749,-1,252,258,AGACG,False,0.9102,245.0,0.810287,0.919411,NM_198147,29.0,3492.0,0.008305
27,NM_005736:1364,ACTR1A,2.895120,2.557538,0.803279,0.825807,1,488,493,GGACG,False,0.7918,490.0,0.977891,0.979900,NM_005736,2.0,2830.0,0.000707
32,NM_138422:1052,ADAT3,2.389407,1.779976,0.569767,0.586346,-1,86,93,GGACG,False,0.6180,89.0,0.779622,0.913205,NM_138422,14.0,1599.0,0.008755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2958,NM_003575:2234,ZNF282,3.129509,2.669289,0.761905,0.718320,1,273,276,GGACG,False,0.7547,265.0,0.731175,0.933231,NM_003575,10.0,3651.0,0.002739
2991,NM_001195605:938,ZNF865,3.145893,2.856116,0.847222,0.897226,-1,72,76,GGACG,False,0.7639,72.0,0.576541,0.906464,NM_001195605,29.0,3763.0,0.007707
2993,NM_001195605:1756,ZNF865,3.206811,3.156591,0.965517,0.949771,1,87,90,AGACG,False,0.9512,82.0,0.576541,0.906464,NM_001195605,29.0,3763.0,0.007707
2995,NM_023926:2063,ZSCAN18,2.756144,2.249168,0.701754,0.778869,-1,57,63,GGACG,False,0.7083,48.0,0.817941,0.948312,NM_023926,3.0,2783.0,0.001078
2996,NM_001145543:1819,ZSCAN18,2.973099,2.354091,0.664835,0.778869,-1,182,189,GGACG,False,0.6532,173.0,0.817941,0.909085,NM_001145543,3.0,2539.0,0.001182

KeyError: 'up_count'

In [231]:
blast_columns = ["qseqid", "sseqid", "pident", "length", "mismatch", "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore"]

up_blast_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/select/blast_up_hits_211024.csv",names=blast_columns)
down_blast_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/select/blast_down_hits_211024.csv", names=blast_columns)

up_blast_df["qstrand"] = up_blast_df["qstart"] < up_blast_df["qend"]
up_blast_df["sstrand"] = up_blast_df["sstart"] < up_blast_df["send"]
up_blast_df = up_blast_df[up_blast_df["qstrand"] & up_blast_df["sstrand"]]

down_blast_df["qstrand"] = down_blast_df["qstart"] < down_blast_df["qend"]
down_blast_df["sstrand"] = down_blast_df["sstart"] < down_blast_df["send"]
down_blast_df = down_blast_df[down_blast_df["qstrand"] & down_blast_df["sstrand"]]

up_blast_df = up_blast_df[(up_blast_df["length"] >= 19)]
down_blast_df = down_blast_df[(down_blast_df["length"] >= 19)]
up_blast_df = up_blast_df[~((up_blast_df["length"] == 30) & (up_blast_df["pident"] == 100))]
down_blast_df = down_blast_df[~((down_blast_df["length"] == 30) & (down_blast_df["pident"] == 100))]

up_count = up_blast_df.groupby("qseqid").count()["sseqid"]
up_count = up_count.reset_index()
up_count = up_count.rename(columns={"sseqid": "up_count", "qseqid": "label_id"})
down_count = down_blast_df.groupby("qseqid").count()["sseqid"]
down_count = down_count.reset_index()
down_count = down_count.rename(columns={"sseqid": "down_count", "qseqid": "label_id"})

very_hiconf_df = very_hiconf_df.merge(up_count, on="label_id", how="left").merge(down_count, on="label_id", how="left")
very_hiconf_df.fillna(0, inplace=True)
high_conf_blast_df = very_hiconf_df[(very_hiconf_df["up_count"] == 0) & (very_hiconf_df["down_count"] == 0)]
high_conf_blast_df

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,pos,up_probe_30,down_probe_30,tm_max,seq,has_repeat,up_probe,down_probe,up_count,down_count
0,NM_014913:3321,ADNP2,2.610246,0.716867,0.639166,-1,166,170,GGACG,False,...,3321,TAGCCAGTACCGTAGTGCGTGGGATCTAATGCTAAAATCTGAAGAG...,CCTTGACAATAGGTCCCTCTGTTCTGCTTTCAGAGGCTGAGTCGCT...,72.690258,AAAGCAGAACAGAGGGACCTATTGTCAAGGACGAGGCTCTTCAGAT...,False,CGAGGCTCTTCAGATTTTAGCATTAGATCC,AAAGCAGAACAGAGGGACCTATTGTCAAGG,0.0,0.0
1,NM_032375:481,AKT1S1,2.408016,0.666667,0.650000,-1,93,96,GGACG,False,...,481,TAGCCAGTACCGTAGTGCGTGCCACAGTAAACGAAGGCAAGCGACC...,CCCTGACCCACAATAAACTTCTTCGACAAACAGAGGCTGAGTCGCT...,76.384300,TTTGTCGAAGAAGTTTATTGTGGGTCAGGGACGTCAGGTCGCTTGC...,False,CGTCAGGTCGCTTGCCTTCGTTTACTGTGG,TTTGTCGAAGAAGTTTATTGTGGGTCAGGG,0.0,0.0
5,NM_004491:2100,ARHGAP35,3.293500,0.804878,0.821303,1,82,84,GGACG,False,...,2100,TAGCCAGTACCGTAGTGCGTGCGAGAACTAATCAAGTGCTCAATCT...,CCACACAAGCTGGGCAGCTGGGGCATGTCTCAGAGGCTGAGTCGCT...,79.813633,AGACATGCCCCAGCTGCCCAGCTTGTGTGGACGCTAAGATTGAGCA...,False,CGCTAAGATTGAGCACTTGATTAGTTCTCG,AGACATGCCCCAGCTGCCCAGCTTGTGTGG,0.0,0.0
6,NM_024585:1771,ARMC7,2.801206,0.790541,0.768443,-1,148,149,GGACG,False,...,1771,TAGCCAGTACCGTAGTGCGTGTCCTGACTCCCTTGAGCAACACTCA...,CCCTGATGCCCTCGTGGGATACACTTCTGGCAGAGGCTGAGTCGCT...,78.116857,CCAGAAGTGTATCCCACGAGGGCATCAGGGACGCAGTGAGTGTTGC...,False,CGCAGTGAGTGTTGCTCAAGGGAGTCAGGA,CCAGAAGTGTATCCCACGAGGGCATCAGGG,0.0,0.0
8,NM_005180:1768,BMI1,2.545544,0.925816,0.895357,1,337,339,GGACG,False,...,1768,TAGCCAGTACCGTAGTGCGTGTATAACAACAATCTTTCTTTTCAAT...,CCATAGGAGTATCACATGTAGTCCATCTTTCAGAGGCTGAGTCGCT...,70.512505,AAAGATGGACTACATGTGATACTCCTATGGACGTTAATTGAAAAGA...,False,CGTTAATTGAAAAGAAAGATTGTTGTTATA,AAAGATGGACTACATGTGATACTCCTATGG,0.0,0.0
10,NM_015005:2554,CEP170B,2.972945,0.943662,0.955357,-1,71,74,GGACG,False,...,2554,TAGCCAGTACCGTAGTGCGTGGCCGCAAGCGGTTTCCTAGATAACA...,CCCCATTCTGGTCCCCAATGAAGAAAGAGGCAGAGGCTGAGTCGCT...,76.951973,CCTCTTTCTTCATTGGGGACCAGAATGGGGACGCTGTGTTATCTAG...,False,CGCTGTGTTATCTAGGAAACCGCTTGCGGC,CCTCTTTCTTCATTGGGGACCAGAATGGGG,0.0,0.0
11,NM_004854:1260,CHST10,2.654569,0.611111,0.684800,-1,198,201,GGACG,False,...,1260,TAGCCAGTACCGTAGTGCGTGCCAGCCTCTTTTAAGATGTATGGGG...,CCTCCAGGGTCTCGTGGTGTCCAATCACACCAGAGGCTGAGTCGCT...,77.744087,GTGTGATTGGACACCACGAGACCCTGGAGGACGATGCCCCATACAT...,False,CGATGCCCCATACATCTTAAAAGAGGCTGG,GTGTGATTGGACACCACGAGACCCTGGAGG,0.0,0.0
14,NM_032656:3836,DHX37,2.392832,0.581633,0.559930,1,196,202,GGACG,False,...,3836,TAGCCAGTACCGTAGTGCGTGAGTCCAAAGAGCACACTGAACAGAA...,CCAGCACGTGAGATGAAATCATCATCCACCCAGAGGCTGAGTCGCT...,73.755037,GGTGGATGATGATTTCATCTCACGTGCTGGACGCTGTTCTGTTCAG...,False,CGCTGTTCTGTTCAGTGTGCTCTTTGGACT,GGTGGATGATGATTTCATCTCACGTGCTGG,0.0,0.0
18,NM_020223:2709,FAM20C,2.897343,0.927273,0.938492,-1,275,283,AGACG,False,...,2709,TAGCCAGTACCGTAGTGCGTGTTTGGTAGGTGATTGGCATCTGTGT...,CTCTGTTTATATACTTATTCATCAAATATACAGAGGCTGAGTCGCT...,73.105580,TATATTTGATGAATAAGTATATAAACAGAGACGTGTACACAGATGC...,False,CGTGTACACAGATGCCAATCACCTACCAAA,TATATTTGATGAATAAGTATATAAACAGAG,0.0,0.0
20,NM_002048:1328,GAS1,2.446113,0.545098,0.639591,1,255,263,GGACG,False,...,1328,TAGCCAGTACCGTAGTGCGTGAGCATGTCCTCAATGACGGTGCGGC...,CCGTGCAGCGCAGCCCGTTGAAGACTTTGCCAGAGGCTGAGTCGCT...,79.177090,GCAAAGTCTTCAACGGGCTGCGCTGCACGGACGAATGCCGCACCGT...,False,CGAATGCCGCACCGTCATTGAGGACATGCT,GCAAAGTCTTCAACGGGCTGCGCTGCACGG,0.0,0.0
23,NM_004807:1223,HS6ST1,2.900648,0.723485,0.785714,1,264,269,GGACG,False,...,1223,TAGCCAGTACCGTAGTGCGTGTGAAGGGCCGGATGAACTTGAGGTT...,CCGCTCGAACAGGTACTGCGTCTTGCGCTGCAGAGGCTGAGTCGCT...,78.147578,CAGCGCAAGACGCAGTACCTGTTCGAGCGGACGTTCAACCTCAAGT...,False,CGTTCAACCTCAAGTTCATCCGGCCCTTCA,CAGCGCAAGACGCAGTACCTGTTCGAGCGG,0.0,0.0
24,NM_012405:992,ICMT,3.128682,0.874494,0.915624,-1,741,763,GGATT,False,...,992,TAGCCAGTACCGTAGTGCGTGGTGACTAATGACATAAAACGATTAA...,CCATGTGGCAGCGGCCAACCGGAAACAGTTCAGAGGCTGAGTCGCT...,78.730206,AACTGTTTCCGGTTGGCCGCTGCCACATGGATTTTCTTAATCGTTT...,False,TTTTCTTAATCGTTTTATGTCATTAGTCAC,AACTGTTTCCGGTTGGCCGCTGCCACATGG,0.0,0.0
30,NM_015353:1241,KCTD2,3.230837,0.990000,0.962119,1,100,100,GGACG,False,...,1241,TAGCCAGTACCGTAGTGCGTGAGGGACGGTGTTCCGAAGCAGCTGC...,CCATTGTGGCACACATAGGGTGAAACCATGCAGAGGCTGAGTCGCT...,77.518362,CATGGTTTCACCCTATGTGTGCCACAATGGACGTTAGCAGCTGCTT...,False,CGTTAGCAGCTGCTTCGGAACACCGTCCCT,CATGGTTTCACCCTATGTGTGCCACAATGG,0.0,0.0
31,NM_014851:2195,KLHL21,2.557589,0.954887,0.892284,1,133,136,GGACG,False,...,2195,TAGCCAGTACCGTAGTGCGTGCTCCCTTCACGCGTCCCTCCCAAGT...,CCTCTCCCAAGGTGGGAACAAGTAGGTGCACAGAGGCTGAGTCGCT...,78.838041,TGCACCTACTTGTTCCCACCTTGGGAGAGGACGATGACTTGGGAGG...,False,CGATGACTTGGGAGGGACGCGTGAAGGGAG,TGCACCTACTTGTTCCCACCTTGGGAGAGG,0.0,0.0
34,NM_014916:6647,LMTK2,2.626910,0.821782,0.838346,-1,101,103,GGACG,False,...,6647,TAGCCAGTACCGTAGTGCGTGAGGTCATTTGCTGCGCACTCTCTGG...,CCGCCTGCATTTTGCACTAGGACTCAACTTCAGAGGCTGAGTCGCT...,76.023264,AAGTTGAGTCCTAGTGCAAAATGCAGGCGGACGTTGCCAGAGAGTG...,False,CGTTGCCAGAGAGTGCGCAGCAAATGACCT,AAGTTGAGTCCTAGTGCAAAATGCAGGCGG,0.0,0.0
35,NM_138699:1421,LOC93622,2.395810,0.714286,0.000000,-3,224,226,GGACG,False,...,1421,TAGCCAGTACCGTAGTGCGTGCCACACACTGCCACTCTTCAAGACC...,CCACTGGGCCTTCTTAATCTCATCCAAAGTCAGAGGCTGAGTCGCT...,76.486079,ACTTTGGATGAGATTAAGAAGGCCCAGTGGACGGTTGGTCTTGAAG...,False,CGGTTGGTCTTGAAGAGTGGCAGTGTGTGG,ACTTTGGATGAGATTAAGAAGGCCCAGTGG,0.0,0.0
36,NM_145021:1545,MARCHF8,2.818896,0.961538,0.951042,1,52,53,GGATA,False,...,1545,TAGCCAGTACCGTAGTGCGTGAGAGTTTGTGTCGGAATGACAGATT...,CCATGTTTATTTTCAAAGTTGGGCTCTGTTCAGAGGCTGAGTCGCT...,70.648682,AACAGAGCCCAACTTTGAAAATAAACATGGATATGGAATCTGTCAT...,False,TATGGAATCTGTCATTCCGACACAAACTCT,AACAGAGCCCAACTTTGAAAATAAACATGG,0.0,0.0
38,NM_018019:971,MED9,2.605900,0.674074,0.649218,1,135,142,GGACG,False,...,971,TAGCCAGTACCGTAGTGCGTGTCTATGCCATATGAGTGCAGGCTTA...,CCAGTGAATTCTATGCAAATGTTTCAAGAACAGAGGCTGAGTCGCT...,72.867059,TTCTTGAAACATTTGCATAGAATTCACTGGACGAATTAAGCCTGCA...,False,CGAATTAAGCCTGCACTCATATGGCATAGA,TTCTTGAAACATTTGCATAGAATTCACTGG,0.0,0.0
39,NM_001543:398,NDST1,3.558805,0.902913,0.907443,-1,103,103,GGACG,False,...,398,TAGCCAGTACCGTAGTGCGTGGGCCCCACACAGGAGGAGACACGAG...,CCACTGACCAACAAATTCACAGAGACTTAGCAGAGGCTGAGTCGCT...,78.950781,CTAAGTCTCTGTGAATTTGTTGGTCAGTGGACGATTCTCGTGTCTC...,False,CGATTCTCGTGTCTCCTCCTGTGTGGGGCC,CTAAGTCTCTGTGAATTTGTTGGTCAGTGG,0.0,0.0
44,NM_005392:3674,PHF2,3.082356,0.906667,0.887916,1,150,153,GGACG,False,...,3674,TAGCCAGTACCGTAGTGCGTGAGATCACTCTTAGCAACTTGAGAAA...,CCATTTTCAAATTGAGGGGCCACGCTGGGCCAGAGGCTGAGTCGCT...,78.151217,GCCCAGCGTGGCCCCTCAATTTGAAAATGGACGTCTTTTCTCAAGT...,False,CGTCTTTTCTCAAGTTGCTAAGAGTGATCT,GCCCAGCGTGGCCCCTCAATTTGAAAATGG,0.0,0.0
52,NM_017841:583,SDHAF2,2.866309,0.905325,0.918439,1,169,170,GGACG,False,...,583,TAGCCAGTACCGTAGTGCGTGGCATCTAAGAAGCCGGAAGCAAGGC...,CCATCATAAGTAGTTACCATCCACAGACTGCAGAGGCTGAGTCGCT...,75.742049,CAGTCTGTGGATGGTAACTACTTATGATGGACGTTAGCCTTGCTTC...,False,CGTTAGCCTTGCTTCCGGCTTCTTAGATGC,CAGTCTGTGGATGGTAACTACTTATGATGG,0.0,0.0
53,NM_006598:3539,SLC12A7,2.939813,0.892045,0.947167,-1,176,186,GGACG,False,...,3539,TAGCCAGTACCGTAGTGCGTGCAGCGTCTGCCCTCAGATGCAAGGA...,CCAGCCACGCCCTGATTTGCTGAGCCTGTTCAGAGGCTGAGTCGCT...,78.083963,AACAGGCTCAGCAAATCAGGGCGTGGCTGGACGATTTCCTTGCATC...,False,CGATTTCCTTGCATCTGAGGGCAGACGCTG,AACAGGCTCAGCAAATCAGGGCGTGGCTGG,0.0,0.0
59,NR_024279:2534,SPEN-AS1,2.452236,0.691803,0.000000,-3,305,310,AGACG,False,...,2534,TAGCCAGTACCGTAGTGCGTGTGCTTAATGGCCAGCCAATGAAAAC...,CTCATTCTACTCCGTCTTTCAGCACGTCAACAGAGGCTGAGTCGCT...,74.057431,TTGACGTGCTGAAAGACGGAGTAGAATGAGACGTTGGTTTTCATTG...,False,CGTTGGTTTTCATTGGCTGGCCATTAAGCA,TTGACGTGCTGAAAGACGGAGTAGAATGAG,0.0,0.0
60,NM_173216:4332,ST6GAL1,2.827898,0.790909,0.755233,-1,110,111,GGACG,False,...,4332,TAGCCAGTACCGTAGTGCGTGATGAAACATCTCACCAGACCAATGA...,CCATATCATAATTTGCATTTTACCAAAGTGCAGAGGCTGAGTCGCT...,70.516794,CACTTTGGTAAAATGCAAATTATGATATGGACGTTATCATTGGTCT...,False,CGTTATCATTGGTCTGGTGAGATGTTTCAT,CACTTTGGTAAAATGCAAATTATGATATGG,0.0,0.0
65,NM_012288:1898,TRAM2,3.093027,0.880597,0.961576,1,67,69,GGACG,False,...,1898,TAGCCAGTACCGTAGTGCGTGCACACCATCCTTCTGGATTGAGTTG...,CCCAAAGCCAAATGCCTTGGCATTTACAACCAGAGGCTGAGTCGCT...,74.608364,GTTGTAAATGCCAAGGCATTTGGCTTTGGGACGTGACAACTCAATC...,False,CGTGACAACTCAATCCAGAAGGATGGTGTG,GTTGTAAATGCCAAGGCATTTGGCTTTGGG,0.0,0.0

In [181]:
dorado_fail_df["pos"] = dorado_fail_df["label_id"].str.split(":").str[1].astype(int)

dorado_fail_df = dorado_fail_df[~dorado_fail_df["gene_id"].isin(exclude_gene)]

dorado_fail_df["up_probe"] = dorado_fail_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+31], axis=1)
dorado_fail_df["down_probe"] = dorado_fail_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-30:x["pos"]], axis=1)

dorado_fail_up_probe_fasta = "\n".join([f">{label_id}\n{seq}" for label_id, seq in zip(dorado_fail_df["label_id"], dorado_fail_df["up_probe"])])
dorado_fail_down_probe_fasta = "\n".join([f">{label_id}\n{seq}" for label_id, seq in zip(dorado_fail_df["label_id"], dorado_fail_df["down_probe"])])

In [182]:
print(dorado_fail_up_probe_fasta)

>NM_001013620:638
ACTTCAGCCTTCCTTGGATTTTGTGGCTTC
>NM_020690:2983
ACTTCAGAAAGTATCAGGTAATCAGCAGAT
>NM_018171:3043
TCCCTCCTCCCTATCAAACTAGTATAATGA
>NM_001377448:4028
CGAGGGGGAGCAGCCGGCCCCTGAGGAGGA
>NM_001170629:536
ACTTTCCAAAGAATCCACAGCTCCAGCTCC
>NR_171547:2308
CGCTGCCTCATTGACTCTCTGGGCGTCGGC
>NM_005730:2720
TCATCCCTTCCATTGCCACACCCTAGATCC
>NM_080738:2202
AAAACTACCCAGTGGTGTCTACTGAAGATC
>NM_001329090:805
CTGTGCAGTGGATGGCGAGTGGCTGGTGCC
>NM_001316938:1630
CGGATGAAGAAGGGGTGGGGTTAAGACTCA
>NM_001371462:2217
CGTTGCTTCATCAGGCGTTGCCTCCGGTGT
>NM_001371462:2561
TATTTCTATTCAGATTTATTTATGCCTCTT
>NM_001371462:2250
GTTTGGGGCTTTAGGAAAGCCTGGGTTGGG
>NM_001282618:1722
ACTGCAAATCTAGAAAACTTTTTAGAGAAA
>NM_001136557:2193
CGGCTGGTGGAGGGGGAAGGAGGGTGCGAG
>NM_006041:687
CGCCCCCCAGGCTGCCGTTCCGGGCGCCGC
>NM_001542:603
ACTCCCTCCTTCTGATCTCTTCTTTTTAAT
>NM_152405:308
CGCTTATTGTCCTTCTCTCGATCCGCGCCA
>NM_003724:2200
CTGATGGCTTCTCTGCCCTGCCCTGGCCAC
>NM_004798:4860
ACTTTTCTAAGAGAAGACAGACAAGTTGAC
>NM_032270:1119
ACTTTTCTTGCAATCATACCATGGCACACT
>NR_040103:1355
ACTTTCCTTAGCTCCTTGGTAGTAACTGGG
>NM_001278209:2701
CTGCTAAACAGACTGGAATTGAAACACCAA
>NM_001172437:455
GCACACCGGCCATAAGAGTGCGTGTGTCCC
>NM_001172437:509
CGAGCTCTCTGAAGAGATCAACAACTTAAG
>NM_001080121:594
CTGCGTCAATATCACAATCAAGCAGCACAC
>NM_003913:416
ACTAAACTTGATGATTTAGCTTTGCTAGAA
>NM_021168:1039
ACTGCTCGCGGAGTAACTGCAAGATCTCCT
>NM_001366508:923
ACTTTCAAGGATAACTTCCAAACATGCAAA
>NM_001199974:543
TTGGGTGTTGAAGCATACAGGTCCGAATAG
>NR_077246:698
CGTCACCCCCATCCCCTCTGACAGCACTCT
>NM_001291411:1034
TTTTCCAGAGTCATCTGCAATTGAAGCGCT
>NM_001291411:684
ACTGCAGAACTGTCAGTTGTATCTACATCA
>NM_003185:2748
ATTACATCCAGATGTAGTAAGTTATGTATC
>NM_001113361:2293
ACTTTTAAAGAATTAAACCAAGGCTTAGCC
>NM_001129884:340
GCTCCGCTCCATCGCTGTCTACTATGACAA
>NM_018052:1605
CGTTATCGGATGAATCGGATGAGGTGATCC
>NR_001564:546
ACCCCCAACACTCTGGCCCATCGGGGTGAC
>NM_001354729:1390
TTCCGAACCTGGCCCTCCAAAGCAGAGGAA

In [183]:
print(dorado_fail_down_probe_fasta)

>NM_001013620:638
ATATTTGATGTGTCTTTATGGAAATCATAA
>NM_020690:2983
ACTTAGGTTCTAATGGGACAAATTCTCTTG
>NM_018171:3043
CCAATTCCTGGAACCCCAGCCCACTCCCCC
>NM_001377448:4028
AGCGAGCAGGGAGTCCGGGTGCCCTTGAGG
>NM_001170629:536
TCCCTCCACCAGAGGAAACAGCTCCCACAG
>NR_171547:2308
TCTCAGTGCCCGTCCTGACGAGTGGCTTGG
>NM_005730:2720
AGGGACACCACCCACTCAGGACTCTTCCCC
>NM_080738:2202
TGTCTGGCTGACCTGTACAAGTCCTTCATC
>NM_001329090:805
TGCCACCGGGGGGTGAAGAGCCCCGTATGC
>NM_001316938:1630
GTCACCTTCATGGTCGTCTTCAGGAACAGG
>NM_001371462:2217
TGGAAGGTTAAGGTGGATGCTGTGGTGGGA
>NM_001371462:2561
TGTACAGAAGGATAAAACCCAGGAAAATGG
>NM_001371462:2250
TTGCTTCATCAGGCGTTGCCTCCGGTGTGG
>NM_001282618:1722
TAAAAAAATGAAAGTAAAGGAAAAAAAAAA
>NM_001136557:2193
TGACCCCATGTGTGGGGAAGTGTAGCAAGG
>NM_006041:687
CCGCCAGCCCTGGCCACAGCTCCGGACGGG
>NM_001542:603
ACACTTGCCTCCACTCCTCCCCTTCCCCCC
>NM_152405:308
AGGTGACCATGTGAACTACCTGCTCCCGGG
>NM_003724:2200
CCTTGCCCTGCTCATCCACAGCAGGTGACA
>NM_004798:4860
TCTGACCAAGGGTGGTTAAGTGACACATAG
>NM_032270:1119
GTGGACATTCAGGACATGACTGGATATAAA
>NR_040103:1355
GTTATGGCGACACTAAACAAAGTATTCCTG
>NM_001278209:2701
TGTCAAGCAGCAAAATTGTCACCCAGAGAT
>NM_001172437:455
CCCCCAACAACAACAACAACAACAACTCCA
>NM_001172437:509
GTGTCCCCAACATGACCGAACGAAGAAGGG
>NM_001080121:594
AGTACAGCAACCAGAACAACTTTGTGCACG
>NM_003913:416
TGATAAAGAGGGTATGTCTCCAGCAAAAAG
>NM_021168:1039
TCCATCCGTCCACCCCAGAGCCCCCCCCAG
>NM_001366508:923
TTGTGGCTTGTTTGGAGATCCTCACCTCAG
>NM_001199974:543
AAGTATTCAAGTCTAACAGTGTTGAAATGG
>NR_077246:698
GCTCGGGTATGAAGATCGGGAGGATTGAGG
>NM_001291411:1034
ACCCTGAGCCAAGCACATCAACAACAATGG
>NM_001291411:684
CATCTTAGAAACTCTGAAGCCAGCTACAAA
>NM_003185:2748
TAGAAATAGGTAAAAAACATGGTATAACGG
>NM_001113361:2293
GGAGTTGGCCTTAAACAAAACAAACACAAA
>NM_001129884:340
TTTTCACTGAGAGCTGCAGCATCTCTCCCA
>NM_018052:1605
ACGGACAGCCTCTTTCCCATCCTACTGCAG
>NR_001564:546
TCGGATACCTGCTGATTCCCTTCCCCTCTG
>NM_001354729:1390
GTGGAGAAGCCTCTGATCCCTCTGATGAGG

In [229]:
blast_columns = ["qseqid", "sseqid", "pident", "length", "mismatch", "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore"]

up_blast_df =   pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/select/blast_up_hits_doradofail_211024.csv",names=blast_columns)
down_blast_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/select/blast_down_hits_doradofail_211024.csv", names=blast_columns)

up_blast_df["qstrand"] = up_blast_df["qstart"] < up_blast_df["qend"]
up_blast_df["sstrand"] = up_blast_df["sstart"] < up_blast_df["send"]
up_blast_df = up_blast_df[up_blast_df["qstrand"] & up_blast_df["sstrand"]]

down_blast_df["qstrand"] = down_blast_df["qstart"] < down_blast_df["qend"]
down_blast_df["sstrand"] = down_blast_df["sstart"] < down_blast_df["send"]
down_blast_df = down_blast_df[down_blast_df["qstrand"] & down_blast_df["sstrand"]]

up_blast_df = up_blast_df[(up_blast_df["length"] >= 19)]
down_blast_df = down_blast_df[(down_blast_df["length"] >= 19)]
up_blast_df = up_blast_df[~((up_blast_df["length"] == 30) & (up_blast_df["pident"] == 100))]
down_blast_df = down_blast_df[~((down_blast_df["length"] == 30) & (down_blast_df["pident"] == 100))]

up_count = up_blast_df.groupby("qseqid").count()["sseqid"]
up_count = up_count.reset_index()
up_count = up_count.rename(columns={"sseqid": "up_count", "qseqid": "label_id"})
down_count = down_blast_df.groupby("qseqid").count()["sseqid"]
down_count = down_count.reset_index()
down_count = down_count.rename(columns={"sseqid": "down_count", "qseqid": "label_id"})

In [230]:
dorado_fail_blast_df = dorado_fail_df.merge(up_count, on="label_id", how="left").merge(down_count, on="label_id", how="left")
dorado_fail_blast_df.fillna(0, inplace=True)
dorado_fail_blast_df["blast_hit"] = dorado_fail_blast_df["up_count"] + dorado_fail_blast_df["down_count"]
dorado_fail_blast_df = dorado_fail_blast_df[(dorado_fail_blast_df["blast_hit"] == 0)]
dorado_fail_blast_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,...,refseq,m6a_count,transcript_length,m6a_density,pos,up_probe,down_probe,up_count,down_count,blast_hit
4,NM_001170629:536,CHD8,1.165228,1.009193,0.746835,0.000000,0,79,84,AGAAC,...,NM_001170629,20.0,8467.0,0.002362,536,ACTTTCCAAAGAATCCACAGCTCCAGCTCC,TCCCTCCACCAGAGGAAACAGCTCCCACAG,0.0,0.0,0.0
9,NM_001316938:1630,FBXL12,1.174176,0.702675,0.250000,0.410789,1,20,22,GGACG,...,NM_001316938,6.0,1917.0,0.003130,1630,CGGATGAAGAAGGGGTGGGGTTAAGACTCA,GTCACCTTCATGGTCGTCTTCAGGAACAGG,0.0,0.0,0.0
12,NM_001371462:2250,GALNT11,0.947466,0.554661,0.208333,0.630171,-1,24,24,GGAGT,...,NM_001371462,1.0,2861.0,0.000350,2250,GTTTGGGGCTTTAGGAAAGCCTGGGTTGGG,TTGCTTCATCAGGCGTTGCCTCCGGTGTGG,0.0,0.0,0.0
21,NR_040103:1355,NAXD,0.880428,0.808055,0.821429,0.000000,0,28,34,TGAAC,...,NR_040103,10.0,2612.0,0.003828,1355,ACTTTCCTTAGCTCCTTGGTAGTAACTGGG,GTTATGGCGACACTAAACAAAGTATTCCTG,0.0,0.0,0.0
24,NM_001172437:509,PEG10,0.808276,0.450523,0.148148,0.000000,-3,27,28,GGACG,...,NM_001172437,24.0,6639.0,0.003615,509,CGAGCTCTCTGAAGAGATCAACAACTTAAG,GTGTCCCCAACATGACCGAACGAAGAAGGG,0.0,0.0,0.0
26,NM_003913:416,PRPF4B,0.733431,0.521564,0.489510,0.000000,-1,143,166,AGAAC,...,NM_003913,7.0,7517.0,0.000931,416,ACTAAACTTGATGATTTAGCTTTGCTAGAA,TGATAAAGAGGGTATGTCTCCAGCAAAAAG,0.0,0.0,0.0
34,NM_001113361:2293,TBC1D14,0.775750,0.756598,0.931035,0.000000,0,29,33,AAAAC,...,NM_001113361,7.0,4861.0,0.001440,2293,ACTTTTAAAGAATTAAACCAAGGCTTAGCC,GGAGTTGGCCTTAAACAAAACAAACACAAA,0.0,0.0,0.0
36,NM_018052:1605,VAC14,0.893817,0.646648,0.503704,0.000000,-1,135,151,AGACG,...,NM_018052,2.0,3096.0,0.000646,1605,CGTTATCGGATGAATCGGATGAGGTGATCC,ACGGACAGCCTCTTTCCCATCCTACTGCAG,0.0,0.0,0.0
37,NR_001564:546,XIST,0.778385,0.621211,0.609756,0.000000,-3,82,92,TGAAC,...,NR_001564,17.0,19296.0,0.000881,546,ACCCCCAACACTCTGGCCCATCGGGGTGAC,TCGGATACCTGCTGATTCCCTTCCCCTCTG,0.0,0.0,0.0
38,NM_001354729:1390,XPC,1.221978,0.698606,0.192308,0.213089,-1,26,26,GGATT,...,NM_001354729,6.0,3632.0,0.001652,1390,TTCCGAACCTGGCCCTCCAAAGCAGAGGAA,GTGGAGAAGCCTCTGATCCCTCTGATGAGG,0.0,0.0,0.0

In [279]:
get_pubmed_count("CDV3")

0

In [298]:
refseq_list = [
    "NM_001065",
    "NM_001810",
    "NM_012293",
    "NM_012405",
]

pos_list = [
    1876,
    825,
    3195,
    992,
]

In [301]:
import RNA
final_df_list = []
for refseq, pos in tqdm.tqdm(zip(refseq_list, pos_list), total=len(refseq_list)):
    refseq_df = neg_df[neg_df["refseq"] == refseq].copy()
    refseq_df["pos"] = refseq_df["label_id"].str.split(":").str[1].astype(int)
    seq = seq_dict[refseq]
    refseq_df = refseq_df[(refseq_df["pos"]>50) & (refseq_df["pos"]<(len(seq)-51))]
    refseq_df = refseq_df[(refseq_df["pos"]>pos-500) & (refseq_df["pos"]<(pos+501))].copy()
    refseq_df["seq"] = refseq_df["pos"].apply(lambda x: seq[x-50:x+51])
    refseq_df["mfe"] = refseq_df["seq"].apply(lambda x: RNA.fold(x)[1])
    final_df_list.append(refseq_df)
    if len(refseq_df) == 0:
        raise ValueError("No data")
final_df = pd.concat(final_df_list)
final_df

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  5.13it/s]

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,pos,seq,mfe
965323,NM_001065:1845,TNFRSF1A,0.0,-0.0,0.0,0.0,0,353,353,AGAGC,False,0.0029,349.0,0.890068,0.954823,NM_001065,1845,GCCGACAGTCAGCGCTGTGCGCGCGGAGAGAGGTGCGCCGTGGGCT...,-39.700001
965298,NM_001065:1722,TNFRSF1A,0.0,-0.0,0.0,0.0,0,341,344,CAAGC,False,0.0031,321.0,0.890068,0.954823,NM_001065,1722,TCGCCTTCCAACCCCACTTTTTTCTGGAAAGGAGGGGTCCTGCAGG...,-30.299999
965294,NM_001065:1701,TNFRSF1A,0.0,-0.0,0.0,0.0,0,337,344,AAAGG,False,0.0184,326.0,0.890068,0.954823,NM_001065,1701,TCTAAGGACCGTCCTGCGAGATCGCCTTCCAACCCCACTTTTTTCT...,-31.799999
7246808,NM_001810:968,CENPB,0.0,-0.0,0.0,0.0,0,345,348,AGAAG,False,0.0028,353.0,0.810287,0.982966,NM_001810,968,CCACCCAGCGCCTGAGCGTCCTGCTATGCGCCAATGCCGACGGCAG...,-41.599998
7246794,NM_001810:895,CENPB,0.0,-0.0,0.0,0.0,0,342,343,GGAGG,False,0.0000,341.0,0.810287,0.982966,NM_001810,895,ACCAGTCTATGGTACGACTTCCTGCCCGACCAGGCCGCGGGGCTGT...,-37.799999
7246755,NM_001810:585,CENPB,0.0,-0.0,0.0,0.0,0,325,334,GGAGC,False,0.0032,311.0,0.810287,0.982966,NM_001810,585,GCCGGTCAAGGGCATCATCCTCAAGGAGAAGGCGCTGCGCATAGCC...,-34.299999
7246744,NM_001810:543,CENPB,0.0,-0.0,0.0,0.0,0,329,331,CAAGG,False,0.0000,303.0,0.810287,0.982966,NM_001810,543,CTTGCTCATCGCCTGGTTCCAGCAGATCCGCGCCGCCGGCCTGCCG...,-37.500000
7246717,NM_001810:398,CENPB,0.0,-0.0,0.0,0.0,0,315,319,AGAAC,False,0.0063,315.0,0.810287,0.982966,NM_001810,398,TCGCGCGGCGCTTCAACATCCCGCCGTCCACGCTGAGCACGATCCT...,-33.400002
9800727,NM_012293:2947,PXDN,0.0,-0.0,0.0,0.0,0,192,192,CGAGA,False,0.0054,184.0,0.846608,0.961275,NM_012293,2947,GCCGCTGCTCCCCTTCGCCACCGGGCCGCCCACGGAGTGCATGCGG...,-33.299999
9800731,NM_012293:2955,PXDN,0.0,-0.0,0.0,0.0,0,191,193,AGAGC,False,0.0052,191.0,0.846608,0.961275,NM_012293,2955,TCCCCTTCGCCACCGGGCCGCCCACGGAGTGCATGCGGGACGAGAA...,-32.799999
9800797,NM_012293:3232,PXDN,0.0,-0.0,0.0,0.0,0,187,193,CAATG,False,0.0054,185.0,0.846608,0.961275,NM_012293,3232,GGTGGGCATGAGGACGCTGGGAGAGTACCACGGCTACGACCCCGGC...,-34.799999
9800703,NM_012293:2818,PXDN,0.0,-0.0,0.0,0.0,0,188,190,GGAGC,False,0.0000,186.0,0.846608,0.961275,NM_012293,2818,CAACCAGCTCACCTCCTACATAGACGCATCCAACGTGTACGGGAGC...,-35.099998
9800887,NM_012293:3624,PXDN,0.0,-0.0,0.0,0.0,0,195,195,TGAAA,False,0.0054,184.0,0.846608,0.961275,NM_012293,3624,ACTACAGGGTCTACTGCAATCTATCGGCGGCACACACGTTCGAGGA...,-15.400000
9800888,NM_012293:3625,PXDN,0.0,-0.0,0.0,0.0,0,205,205,GAAAA,False,0.0052,194.0,0.846608,0.961275,NM_012293,3625,CTACAGGGTCTACTGCAATCTATCGGCGGCACACACGTTCGAGGAC...,-15.400000
9800891,NM_012293:3628,PXDN,0.0,-0.0,0.0,0.0,0,202,203,AAATG,False,0.0053,188.0,0.846608,0.961275,NM_012293,3628,CAGGGTCTACTGCAATCTATCGGCGGCACACACGTTCGAGGACCTG...,-17.200001
9800892,NM_012293:3631,PXDN,0.0,-0.0,0.0,0.0,0,208,209,TGAGA,False,0.0333,180.0,0.846608,0.961275,NM_012293,3631,GGTCTACTGCAATCTATCGGCGGCACACACGTTCGAGGACCTGAAA...,-16.900000
9800895,NM_012293:3637,PXDN,0.0,-0.0,0.0,0.0,0,203,206,TAAAA,False,0.0053,189.0,0.846608,0.961275,NM_012293,3637,CTGCAATCTATCGGCGGCACACACGTTCGAGGACCTGAAAAATGAG...,-14.500000
9800701,NM_012293:2811,PXDN,0.0,-0.0,0.0,0.0,0,187,191,GGAGC,False,0.0161,186.0,0.846608,0.961275,NM_012293,2811,AGCAGATCAACCAGCTCACCTCCTACATAGACGCATCCAACGTGTA...,-27.200001
9800900,NM_012293:3648,PXDN,0.0,-0.0,0.0,0.0,0,205,207,AGATC,False,0.0050,200.0,0.846608,0.961275,NM_012293,3648,CGGCGGCACACACGTTCGAGGACCTGAAAAATGAGATTAAAAACCC...,-15.100000
9800902,NM_012293:3657,PXDN,0.0,-0.0,0.0,0.0,0,208,208,AGAAA,False,0.0000,204.0,0.846608,0.961275,NM_012293,3657,ACACGTTCGAGGACCTGAAAAATGAGATTAAAAACCCTGAGATCCG...,-15.700000

In [302]:
final_df["pos"] = final_df["label_id"].str.split(":").str[1].astype(int)

final_df["up_probe"] = final_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+31], axis=1)
final_df["down_probe"] = final_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-30:x["pos"]], axis=1)

neg_up_probe_fasta = "\n".join([f">{label_id}\n{seq}" for label_id, seq in zip(final_df["label_id"], final_df["up_probe"])])
neg_down_probe_fasta = "\n".join([f">{label_id}\n{seq}" for label_id, seq in zip(final_df["label_id"], final_df["down_probe"])])

In [303]:
print(neg_up_probe_fasta)

>NM_001065:1845
GCCTGAGTGGGTGGTTTGCGAGGATGAGGG
>NM_001065:1722
GCAGGAGCTAGCAGCCGCCTACTTGGTGCT
>NM_001065:1701
GGAGGGGTCCTGCAGGGGCAAGCAGGAGCT
>NM_001810:968
AGCTGCCCCCGCTGGTGGCCGGCAAGTCGG
>NM_001810:895
GGCGACGGACGGCCGCGTCAAGCCACCCAG
>NM_001810:585
GCTGGGCATGGACGACTTCACCGCCTCCAA
>NM_001810:543
GGGCATCATCCTCAAGGAGAAGGCGCTGCG
>NM_001810:398
ACAAGCGCGCCATCCTGGCGTCGGAGCGCA
>NM_012293:2947
GAACGAGAGCCCCATCCCCTGCTTCCTGGC
>NM_012293:2955
GCCCCATCCCCTGCTTCCTGGCCGGGGACC
>NM_012293:3232
TGCTGGCATCTTCAACGCCTTCGCCACCGC
>NM_012293:2818
GCATGAGGCCCGCAGCATCCGCGACCTGGC
>NM_012293:3624
AAAATGAGATTAAAAACCCTGAGATCCGGG
>NM_012293:3625
AAATGAGATTAAAAACCCTGAGATCCGGGA
>NM_012293:3628
TGAGATTAAAAACCCTGAGATCCGGGAGAA
>NM_012293:3631
GATTAAAAACCCTGAGATCCGGGAGAAACT
>NM_012293:3637
AAACCCTGAGATCCGGGAGAAACTGAAAAG
>NM_012293:2811
GCACGGAGCATGAGGCCCGCAGCATCCGCG
>NM_012293:3648
TCCGGGAGAAACTGAAAAGGTTGTATGGCT
>NM_012293:3657
AACTGAAAAGGTTGTATGGCTCGACACTCA

In [304]:
print(neg_down_probe_fasta)

>NM_001065:1845
GCGCGGAGAGAGGTGCGCCGTGGGCTCAAG
>NM_001065:1722
TTTCTGGAAAGGAGGGGTCCTGCAGGGGCA
>NM_001065:1701
ATCGCCTTCCAACCCCACTTTTTTCTGGAA
>NM_001810:968
CTGCTATGCGCCAATGCCGACGGCAGCGAG
>NM_001810:895
CCTGCCCGACCAGGCCGCGGGGCTGTGCGG
>NM_001810:585
TCAAGGAGAAGGCGCTGCGCATAGCCGAGG
>NM_001810:543
AGCAGATCCGCGCCGCCGGCCTGCCGGTCA
>NM_001810:398
CCGCCGTCCACGCTGAGCACGATCCTGAAG
>NM_012293:2947
CCGGGCCGCCCACGGAGTGCATGCGGGACG
>NM_012293:2955
CCCACGGAGTGCATGCGGGACGAGAACGAG
>NM_012293:3232
GAGAGTACCACGGCTACGACCCCGGCATCA
>NM_012293:2818
TAGACGCATCCAACGTGTACGGGAGCACGG
>NM_012293:3624
CTATCGGCGGCACACACGTTCGAGGACCTG
>NM_012293:3625
TATCGGCGGCACACACGTTCGAGGACCTGA
>NM_012293:3628
CGGCGGCACACACGTTCGAGGACCTGAAAA
>NM_012293:3631
CGGCACACACGTTCGAGGACCTGAAAAATG
>NM_012293:3637
ACACGTTCGAGGACCTGAAAAATGAGATTA
>NM_012293:2811
TCCTACATAGACGCATCCAACGTGTACGGG
>NM_012293:3648
GACCTGAAAAATGAGATTAAAAACCCTGAG
>NM_012293:3657
AATGAGATTAAAAACCCTGAGATCCGGGAG

In [305]:
blast_columns = ["qseqid", "sseqid", "pident", "length", "mismatch", "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore"]

up_blast_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/res/blast/negative2_up_hits.csv",names=blast_columns)
down_blast_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/res/blast/negative2_down_hits.csv", names=blast_columns)

up_blast_df["qstrand"] = up_blast_df["qstart"] < up_blast_df["qend"]
up_blast_df["sstrand"] = up_blast_df["sstart"] < up_blast_df["send"]
up_blast_df = up_blast_df[up_blast_df["qstrand"] & up_blast_df["sstrand"]]

down_blast_df["qstrand"] = down_blast_df["qstart"] < down_blast_df["qend"]
down_blast_df["sstrand"] = down_blast_df["sstart"] < down_blast_df["send"]
down_blast_df = down_blast_df[down_blast_df["qstrand"] & down_blast_df["sstrand"]]

up_blast_df = up_blast_df[(up_blast_df["length"] >= 20)]
down_blast_df = down_blast_df[(down_blast_df["length"] >= 20)]
up_blast_df = up_blast_df[~((up_blast_df["length"] == 30) & (up_blast_df["pident"] == 100))]
down_blast_df = down_blast_df[~((down_blast_df["length"] == 30) & (down_blast_df["pident"] == 100))]

up_count = up_blast_df.groupby("qseqid").count()["sseqid"]
up_count = up_count.reset_index()
up_count = up_count.rename(columns={"sseqid": "up_count", "qseqid": "label_id"})
down_count = down_blast_df.groupby("qseqid").count()["sseqid"]
down_count = down_count.reset_index()
down_count = down_count.rename(columns={"sseqid": "down_count", "qseqid": "label_id"})

In [306]:
neg_blast_df = final_df.merge(up_count, on="label_id", how="left").merge(down_count, on="label_id", how="left")
neg_blast_df.fillna(0, inplace=True)
neg_blast_df["blast_hit"] = neg_blast_df["up_count"] + neg_blast_df["down_count"]
neg_blast_df = neg_blast_df[(neg_blast_df["blast_hit"] == 0)]
neg_blast_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,...,cell_perc,refseq,pos,seq,mfe,up_probe,down_probe,up_count,down_count,blast_hit
4,NM_001810:895,CENPB,0.0,-0.0,0.0,0.0,0,342,343,GGAGG,...,0.982966,NM_001810,895,ACCAGTCTATGGTACGACTTCCTGCCCGACCAGGCCGCGGGGCTGT...,-37.799999,GGCGACGGACGGCCGCGTCAAGCCACCCAG,CCTGCCCGACCAGGCCGCGGGGCTGTGCGG,0.0,0.0,0.0
5,NM_001810:585,CENPB,0.0,-0.0,0.0,0.0,0,325,334,GGAGC,...,0.982966,NM_001810,585,GCCGGTCAAGGGCATCATCCTCAAGGAGAAGGCGCTGCGCATAGCC...,-34.299999,GCTGGGCATGGACGACTTCACCGCCTCCAA,TCAAGGAGAAGGCGCTGCGCATAGCCGAGG,0.0,0.0,0.0
10,NM_012293:3232,PXDN,0.0,-0.0,0.0,0.0,0,187,193,CAATG,...,0.961275,NM_012293,3232,GGTGGGCATGAGGACGCTGGGAGAGTACCACGGCTACGACCCCGGC...,-34.799999,TGCTGGCATCTTCAACGCCTTCGCCACCGC,GAGAGTACCACGGCTACGACCCCGGCATCA,0.0,0.0,0.0
18,NM_012293:3648,PXDN,0.0,-0.0,0.0,0.0,0,205,207,AGATC,...,0.961275,NM_012293,3648,CGGCGGCACACACGTTCGAGGACCTGAAAAATGAGATTAAAAACCC...,-15.100000,TCCGGGAGAAACTGAAAAGGTTGTATGGCT,GACCTGAAAAATGAGATTAAAAACCCTGAG,0.0,0.0,0.0
19,NM_012293:3657,PXDN,0.0,-0.0,0.0,0.0,0,208,208,AGAAA,...,0.961275,NM_012293,3657,ACACGTTCGAGGACCTGAAAAATGAGATTAAAAACCCTGAGATCCG...,-15.700000,AACTGAAAAGGTTGTATGGCTCGACACTCA,AATGAGATTAAAAACCCTGAGATCCGGGAG,0.0,0.0,0.0

In [6]:
agree_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/select/very_high_conf.tsv", sep="\t", index_col=0).reset_index(drop=True)
agree_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density,hit
0,NM_006565:596,CTCF,2.630316,2.236568,0.745665,0.807812,1,173,173,GGACG,False,0.7314,175,0.895219,0.955317,NM_006565,8,3814,0.002098,367
1,NM_005736:1364,ACTR1A,2.895120,2.557538,0.803279,0.825807,1,488,493,GGACG,False,0.7918,490,0.977891,0.979900,NM_005736,2,2830,0.000707,0
2,NM_145290:3525,ADGRA3,2.676393,2.183380,0.695652,0.773499,-1,276,277,GGACG,False,0.6926,270,0.956869,0.960855,NM_145290,16,4577,0.003496,0
3,NM_032375:532,AKT1S1,3.016171,2.831370,0.890000,0.839323,1,100,101,GGACG,False,0.8750,96,0.814711,0.963261,NM_032375,3,2447,0.001226,0
4,NM_138927:3267,SON,2.415122,2.307777,0.910345,0.924502,1,145,154,GAACG,False,0.8561,132,0.880445,0.967464,NM_138927,36,8393,0.004289,89
5,NM_138927:3243,SON,2.401637,2.207457,0.851351,0.873767,1,148,154,GAACG,False,0.8045,133,0.880445,0.967464,NM_138927,36,8393,0.004289,89
6,NM_015001:741,SPEN,2.883851,2.833272,0.956522,0.923825,1,46,46,GGACG,False,0.9767,43,0.989251,0.983089,NM_015001,42,12385,0.003391,18
7,NM_014663:3515,KDM4A,2.755024,2.458995,0.813370,0.820826,1,359,367,GGACG,False,0.8034,356,0.959576,0.969385,NM_014663,3,4486,0.000669,17
8,NM_001319:1927,CSNK1G2,3.073604,2.681436,0.793151,0.893732,1,730,748,GGACG,False,0.7699,730,0.883239,0.986715,NM_001319,7,2895,0.002418,0
9,NM_002417:980,MKI67,2.361893,2.026780,0.760563,0.711384,-1,71,78,GGACG,False,0.6623,77,0.940261,0.954839,NM_002417,34,12716,0.002674,14
10,NM_003507:1754,FZD7,2.903024,2.854372,0.960784,0.955482,-1,255,260,GGACG,False,0.9569,255,0.640607,0.957196,NM_003507,21,4587,0.004578,17
11,NM_001010924:1590,FAM171A1,2.697631,2.540684,0.892351,0.944195,1,353,364,GGACG,False,0.8914,350,0.931327,0.974568,NM_001010924,18,4182,0.004304,0
12,NR_027451:446,NORAD,2.820073,2.798810,0.976190,0.000000,-3,42,42,GGACG,False,0.9767,43,0.903009,0.981985,NR_027451,7,5378,0.001302,13
13,NM_001065:1876,TNFRSF1A,2.635865,2.116341,0.674352,0.651300,-1,347,357,GGACG,False,0.6343,350,0.890068,0.954823,NM_001065,5,2171,0.002303,12
14,NM_018137:1048,PRMT6,2.992098,2.888870,0.929530,0.957377,1,298,300,GGACG,False,0.9286,294,0.934120,0.955457,NM_018137,11,2621,0.004197,10
15,NM_001810:825,CENPB,3.157752,2.861978,0.842424,0.913360,-1,330,334,GGACG,False,0.8274,336,0.810287,0.982966,NM_001810,14,2890,0.004844,10
16,NM_018971:1373,GPR27,2.639808,2.553286,0.929825,0.947105,1,342,343,GGACG,False,0.9281,334,0.782416,0.966953,NM_018971,11,2642,0.004164,0
17,NM_001810:597,CENPB,2.901590,2.442747,0.739394,0.858509,1,330,335,GGACG,False,0.7407,324,0.810287,0.982966,NM_001810,14,2890,0.004844,10
18,NM_001206:2071,KLF9,2.886841,2.702250,0.881579,0.883446,-1,76,77,GGAGA,False,0.8533,75,0.640607,0.951081,NM_001206,11,5201,0.002115,7
19,NM_138346:1775,KIAA2013,2.651895,2.159449,0.693267,0.832076,-1,802,824,GGACG,False,0.7262,767,0.915679,0.973472,NM_138346,12,2819,0.004257,0
20,NM_002067:1889,GNA11,3.297375,3.102891,0.897833,0.948511,-1,323,332,GGACG,False,0.8994,318,0.859025,0.972211,NM_002067,10,4190,0.002387,8
21,NM_004822:5645,NTN1,2.674269,2.066470,0.630573,0.655234,1,471,500,GGACG,False,0.5449,457,0.838750,0.974741,NM_004822,13,5986,0.002172,8
22,NM_203304:1406,MEX3D,3.154321,2.909654,0.869159,0.938457,-1,107,109,GGACG,False,0.8316,95,0.576541,0.952153,NM_203304,10,3114,0.003211,0
23,NM_012405:992,ICMT,3.128682,2.896143,0.874494,0.915624,-1,741,763,GGATT,False,0.8109,735,0.982596,0.981046,NM_012405,12,4795,0.002503,4
24,NM_194460:1334,RNF126,3.047968,2.770707,0.845779,0.933931,1,616,626,GGACG,False,0.8326,645,0.880872,0.979546,NM_194460,2,1631,0.001226,4
25,NM_003970:4846,MYOM2,3.106454,2.932258,0.900000,0.853199,-1,470,478,GGACG,False,0.8898,463,0.970848,0.973942,NM_003970,4,5008,0.000799,0
26,NM_022833:2141,NIBAN2,2.607689,2.079941,0.666667,0.656167,1,180,187,GGACG,False,0.6167,180,0.856260,0.960921,NM_022833,4,3942,0.001015,0
27,NM_001849:3036,COL6A2,2.526744,2.022392,0.666667,0.760047,-1,492,508,GGACG,False,0.6875,496,0.859025,0.978112,NM_001849,2,3445,0.000581,4
28,NM_005934:4071,MLLT1,2.616506,2.448171,0.882883,0.931805,1,333,363,GGACG,False,0.8625,320,0.887216,0.967530,NM_005934,10,4532,0.002207,3
29,NM_012293:3195,PXDN,2.871657,2.749361,0.915789,0.936917,1,190,193,GGACG,False,0.8969,194,0.846608,0.961275,NM_012293,15,6817,0.002200,2
30,NM_032242:676,PLXNA1,3.140351,2.598445,0.724138,0.735075,1,116,117,GGACG,False,0.7155,116,0.969587,0.961144,NM_032242,15,9309,0.001611,2
31,NM_002356:981,MARCKS,2.687683,2.330944,0.774051,0.916105,1,1133,1158,GGACG,False,0.7714,1146,0.576541,0.957839,NM_002356,5,4296,0.001164,33
32,NR_033338:3250,FAAP100,2.566943,2.320042,0.829114,0.905165,1,158,162,GGATT,False,0.8699,146,0.765022,0.959850,NR_033338,10,3793,0.002636,3
33,NM_016272:764,TOB2,2.869116,2.469243,0.773050,0.793662,1,141,142,GGATT,False,0.7246,138,0.948866,0.954460,NM_016272,11,4337,0.002536,2
34,NM_001099415:2912,POM121C,2.548580,2.005678,0.653710,0.746047,-1,283,303,TGACG,False,0.5694,288,0.965911,0.971090,NM_001099415,12,5867,0.002045,0
35,NM_014811:3615,PPP1R26,2.503581,2.037864,0.688889,0.698052,1,270,280,GGACG,False,0.6828,268,0.838750,0.960047,NM_014811,23,4951,0.004646,0
36,NM_020795:2743,NLGN2,2.652124,2.376987,0.824390,0.843307,1,205,217,GGACG,False,0.7958,191,0.942832,0.959940,NM_020795,10,4980,0.002008,2
37,NM_012293:3381,PXDN,2.325224,2.242015,0.928571,0.930413,1,182,199,GGATT,False,0.8192,177,0.846608,0.961275,NM_012293,15,6817,0.002200,2
38,NM_020440:2956,PTGFRN,2.573867,2.258111,0.787286,0.819444,-1,409,422,GGACG,False,0.7798,386,0.944006,0.977461,NM_020440,15,6314,0.002376,0
39,NM_001089:5961,ABCA3,2.685794,2.127319,0.655290,0.711017,1,293,296,GGACG,False,0.6536,280,0.952834,0.961819,NM_001089,4,6602,0.000606,2
40,NM_006570:1335,RRAGA,3.165622,3.123860,0.968889,0.956867,1,450,455,GGACG,False,0.9581,453,0.975922,0.974379,NM_006570,3,1599,0.001876,1
41,NM_181701:1897,QSOX2,2.611960,2.160741,0.713816,0.802023,1,304,322,GGACG,False,0.7113,291,0.936381,0.964827,NM_181701,11,4501,0.002444,0
42,NM_032595:1281,PPP1R9B,3.205540,3.021730,0.902813,0.942157,1,391,421,GGACG,False,0.8854,314,0.928717,0.985364,NM_032595,7,4212,0.001662,1
43,NM_004472:1012,FOXD1,2.350945,2.097018,0.811224,0.847685,1,196,209,GGACG,False,0.7958,191,0.743961,0.969896,NM_004472,7,2512,0.002787,6
44,NM_016588:691,NRN1,3.024294,2.833947,0.887097,0.910687,1,186,189,GGACG,False,0.8453,181,0.970470,0.957526,NM_016588,5,1582,0.003161,1
45,NM_178448:3273,SAPCD2,2.511361,2.010625,0.666667,0.623418,1,387,398,GGACG,False,0.6447,380,0.864972,0.971066,NM_178448,10,3814,0.002622,0
46,NM_001290264:2192,SLC35E2B,3.047642,2.884313,0.904762,0.894169,1,63,65,GGACG,False,0.8852,61,0.933732,0.962849,NM_001290264,20,6434,0.003108,0
47,NM_001135575:1767,SMIM13,2.275729,2.025191,0.794118,0.837424,1,68,69,AGACG,False,0.7794,68,0.810287,0.958094,NM_001135575,11,4887,0.002251,0
48,NM_022463:1426,NXN,3.109544,2.523765,0.694836,0.776929,-1,213,213,AGACG,False,0.7054,224,0.872315,0.955416,NM_022463,10,3045,0.003284,1
49,NM_012121:1462,CDC42EP4,2.722056,2.492623,0.847926,0.826430,1,217,219,GGACG,False,0.8311,219,0.915679,0.951848,NM_012121,13,3098,0.004196,1
50,NM_001320546:1148,WDR6,2.449718,2.092763,0.760000,0.699817,1,75,84,GGACG,False,0.7324,71,0.961468,0.974453,NM_001320546,21,4284,0.004902,1
51,NR_024279:1171,SPEN-AS1,2.354381,2.308103,0.950495,0.000000,-3,101,107,GGACG,False,0.9619,105,0.970266,0.961737,NR_024279,8,2732,0.002928,0
52,NR_024279:2534,SPEN-AS1,2.452236,2.009451,0.691803,0.000000,-3,305,310,AGACG,False,0.6928,306,0.970266,0.961737,NR_024279,8,2732,0.002928,0
53,NM_015527:2724,TBC1D10B,3.381225,3.123083,0.873418,0.876744,1,474,487,GGACG,False,0.8655,476,0.859025,0.979900,NM_015527,14,3580,0.003911,0
54,NM_017994:1463,TMEM248,3.111821,2.652911,0.761364,0.843684,-1,528,533,GGACG,False,0.7638,525,0.891281,0.965272,NM_017994,7,4229,0.001655,0
55,NM_152308:1117,RMI2,2.437597,2.024977,0.709677,0.830415,1,403,409,AGACG,False,0.6985,408,0.773724,0.973167,NM_152308,7,1427,0.004905,5
56,NM_014077:1189,FAM32A,2.416122,2.039284,0.731161,0.745549,1,491,500,GGACG,False,0.7271,491,0.993685,0.978013,NM_014077,6,1463,0.004101,1
57,NM_001387691:2841,POM121,2.724077,2.019772,0.573034,0.721154,-1,89,90,TGACG,False,0.5375,80,0.672280,0.955696,NM_001387691,10,5842,0.001712,3

In [7]:
disagree_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/select/dorado_fail.tsv", sep="\t", index_col=0).reset_index(drop=True)
disagree_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,drach,pred_dorado,count_dorado,ivt_perc,cell_perc,refseq,m6a_count,transcript_length,m6a_density,hit
0,NM_001329090:805,EPHA2,1.608960,1.455806,0.818182,0.941250,-1,22,24,GCACT,False,0,0,0.872480,0.901347,NM_001329090,10,3878,0.002579,49
1,NM_003724:2200,JRK,1.594822,1.524985,0.909091,0.764723,1,22,25,CAACT,False,0,0,0.633641,0.903382,NM_003724,15,9097,0.001649,2
2,NM_006766:777,KAT6A,1.793477,1.532469,0.750000,0.858974,-1,20,20,GAACG,False,0,0,0.810287,0.906464,NM_006766,27,9153,0.002950,9
3,NM_152405:308,JMY,1.766405,1.105077,0.333333,0.406751,-1,21,22,GGACG,False,0,0,0.797200,0.906464,NM_152405,14,9096,0.001539,4
4,NM_001136557:2193,GPR107,1.787405,1.127730,0.333333,0.214130,1,24,24,GGACG,False,0,0,0.855416,0.908063,NM_001136557,4,6873,0.000582,0
5,NM_006077:1871,MICU1,1.987081,1.232901,0.318182,0.261607,1,22,22,GGATT,False,0,0,0.945733,0.916782,NM_006077,3,2363,0.001270,43
6,NR_171547:2308,CHPF2,2.214009,1.435382,0.380952,0.394277,1,21,21,GGACG,False,0,0,0.748113,0.921084,NR_171547,13,4206,0.003091,0
7,NM_001410823:1309,CDV3,1.869049,1.671504,0.809524,0.678599,1,21,21,GGATT,False,0,0,0.747327,0.923029,NM_001410823,6,3361,0.001785,0
8,NM_001278209:2701,NUP153,1.899402,1.336646,0.480000,0.231919,1,25,25,ATACT,False,0,0,0.906337,0.935234,NM_001278209,15,6119,0.002451,21
9,NM_001346092:1994,TNFRSF1A,2.074902,1.581490,0.600000,0.651300,-1,20,21,GGACG,False,0,0,0.827070,0.936626,NM_001346092,2,2289,0.000874,12
10,NR_073498:1533,KHDRBS1,1.532830,0.994549,0.360000,0.545374,1,25,26,GGACG,False,0,0,0.920141,0.984606,NR_073498,1,2796,0.000358,2

In [13]:
agree_df["dorado_agree"] = True
disagree_df["dorado_agree"] = False
data_df = pd.concat([agree_df, disagree_df])
data_df["refseq"] = data_df["label_id"].str.split(":").str[0]
data_df["pos"] = data_df["label_id"].str.split(":").str[1].astype(int)

In [9]:
import RNA

data_df["mfe"] = data_df["seq"].apply(lambda x: RNA.fold(x)[1])
data_df

,label_id,gene_id,log_pm6a,noisy_or,dom,dom_label,label,count_dom,count_all,5mer,...,cell_perc,refseq,m6a_count,transcript_length,m6a_density,hit,dorado_agree,pos,seq,mfe
0,NM_006565:596,CTCF,2.630316,2.236568,0.745665,0.807812,1,173,173,GGACG,...,0.955317,NM_006565,8,3814,0.002098,367,True,596,GACTGAAGTAATGGAGGGCACAGTGGCTCCAGAAGCAGAGGCTGCT...,-26.100000
1,NM_005736:1364,ACTR1A,2.895120,2.557538,0.803279,0.825807,1,488,493,GGACG,...,0.979900,NM_005736,2,2830,0.000707,0,True,1364,GTGTGCACATGCGAGTGCCGTGTGGCCCTGGGACCCTGGGCCCAGA...,-38.000000
2,NM_145290:3525,ADGRA3,2.676393,2.183380,0.695652,0.773499,-1,276,277,GGACG,...,0.960855,NM_145290,16,4577,0.003496,0,True,3525,GGAGCTCGTATTCAGTGCAAGTCAACGTCCAGCCCCCCAACTCTAA...,-24.100000
3,NM_032375:532,AKT1S1,3.016171,2.831370,0.890000,0.839323,1,100,101,GGACG,...,0.963261,NM_032375,3,2447,0.001226,0,True,532,CGTCAGGTCGCTTGCCTTCGTTTACTGTGGTCATGATTGAGCATAT...,-29.000000
4,NM_138927:3267,SON,2.415122,2.307777,0.910345,0.924502,1,145,154,GAACG,...,0.967464,NM_138927,36,8393,0.004289,89,True,3267,GAGCGCTCTATGATGTCAGCTTATGAACGCTCCATGATGTCAGCTT...,-24.299999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,NR_171547:2308,CHPF2,2.214009,1.435382,0.380952,0.394277,1,21,21,GGACG,...,0.921084,NR_171547,13,4206,0.003091,0,False,2308,GATGGCTGCCGAGGAGACATTCTCAGTGCCCGTCCTGACGAGTGGC...,-34.299999
7,NM_001410823:1309,CDV3,1.869049,1.671504,0.809524,0.678599,1,21,21,GGATT,...,0.923029,NM_001410823,6,3361,0.001785,0,False,1309,CCTATTGCACTATGGAAGTTAAAGTGTCACGACTGCTCTATGCATA...,-15.200000
8,NM_001278209:2701,NUP153,1.899402,1.336646,0.480000,0.231919,1,25,25,ATACT,...,0.935234,NM_001278209,15,6119,0.002451,21,False,2701,CAGACAACAAATGCATAGCCTGTCAAGCAGCAAAATTGTCACCCAG...,-13.900000
9,NM_001346092:1994,TNFRSF1A,2.074902,1.581490,0.600000,0.651300,-1,20,21,GGACG,...,0.936626,NM_001346092,2,2289,0.000874,12,False,1994,GGTGCGCCGTGGGCTCAAGAGCCTGAGTGGGTGGTTTGCGAGGATG...,-34.000000
10,NR_073498:1533,KHDRBS1,1.532830,0.994549,0.360000,0.545374,1,25,26,GGACG,...,0.984606,NR_073498,1,2796,0.000358,2,False,1533,GCCCCTCCTGCTAGGCCAGTGAAGGGAGCATACAGAGAGCACCCAT...,-20.299999

In [10]:
data_df.drop(columns=["seq","refseq","pos"], inplace=True)

In [11]:
data_df.to_csv("/extdata4/baeklab/Hyeonseo/m6A/select/mfe.tsv", sep="\t", index=False)

In [15]:

sys.path.append("/extdata4/baeklab/Hyeonseo/m6A/modformer")
from utils.utils import revcomp_DNA

In [288]:
data_df = pd.concat([high_conf_blast_df, dorado_fail_blast_df])
data_df["blast_hit"] = data_df["up_count"] + data_df["down_count"]
data_df

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,down_probe_30,tm_max,seq,has_repeat,up_probe,down_probe,up_count,down_count,noisy_or,blast_hit
0,NM_014913:3321,ADNP2,2.610246,0.716867,0.639166,-1,166,170,GGACG,False,...,CCTTGACAATAGGTCCCTCTGTTCTGCTTTCAGAGGCTGAGTCGCT...,72.690258,AAAGCAGAACAGAGGGACCTATTGTCAAGGACGAGGCTCTTCAGAT...,False,CGAGGCTCTTCAGATTTTAGCATTAGATCC,AAAGCAGAACAGAGGGACCTATTGTCAAGG,0.0,0.0,NaN,0.0
1,NM_032375:481,AKT1S1,2.408016,0.666667,0.650000,-1,93,96,GGACG,False,...,CCCTGACCCACAATAAACTTCTTCGACAAACAGAGGCTGAGTCGCT...,76.384300,TTTGTCGAAGAAGTTTATTGTGGGTCAGGGACGTCAGGTCGCTTGC...,False,CGTCAGGTCGCTTGCCTTCGTTTACTGTGG,TTTGTCGAAGAAGTTTATTGTGGGTCAGGG,0.0,0.0,NaN,0.0
5,NM_004491:2100,ARHGAP35,3.293500,0.804878,0.821303,1,82,84,GGACG,False,...,CCACACAAGCTGGGCAGCTGGGGCATGTCTCAGAGGCTGAGTCGCT...,79.813633,AGACATGCCCCAGCTGCCCAGCTTGTGTGGACGCTAAGATTGAGCA...,False,CGCTAAGATTGAGCACTTGATTAGTTCTCG,AGACATGCCCCAGCTGCCCAGCTTGTGTGG,0.0,0.0,NaN,0.0
6,NM_024585:1771,ARMC7,2.801206,0.790541,0.768443,-1,148,149,GGACG,False,...,CCCTGATGCCCTCGTGGGATACACTTCTGGCAGAGGCTGAGTCGCT...,78.116857,CCAGAAGTGTATCCCACGAGGGCATCAGGGACGCAGTGAGTGTTGC...,False,CGCAGTGAGTGTTGCTCAAGGGAGTCAGGA,CCAGAAGTGTATCCCACGAGGGCATCAGGG,0.0,0.0,NaN,0.0
8,NM_005180:1768,BMI1,2.545544,0.925816,0.895357,1,337,339,GGACG,False,...,CCATAGGAGTATCACATGTAGTCCATCTTTCAGAGGCTGAGTCGCT...,70.512505,AAAGATGGACTACATGTGATACTCCTATGGACGTTAATTGAAAAGA...,False,CGTTAATTGAAAAGAAAGATTGTTGTTATA,AAAGATGGACTACATGTGATACTCCTATGG,0.0,0.0,NaN,0.0
10,NM_015005:2554,CEP170B,2.972945,0.943662,0.955357,-1,71,74,GGACG,False,...,CCCCATTCTGGTCCCCAATGAAGAAAGAGGCAGAGGCTGAGTCGCT...,76.951973,CCTCTTTCTTCATTGGGGACCAGAATGGGGACGCTGTGTTATCTAG...,False,CGCTGTGTTATCTAGGAAACCGCTTGCGGC,CCTCTTTCTTCATTGGGGACCAGAATGGGG,0.0,0.0,NaN,0.0
11,NM_004854:1260,CHST10,2.654569,0.611111,0.684800,-1,198,201,GGACG,False,...,CCTCCAGGGTCTCGTGGTGTCCAATCACACCAGAGGCTGAGTCGCT...,77.744087,GTGTGATTGGACACCACGAGACCCTGGAGGACGATGCCCCATACAT...,False,CGATGCCCCATACATCTTAAAAGAGGCTGG,GTGTGATTGGACACCACGAGACCCTGGAGG,0.0,0.0,NaN,0.0
14,NM_032656:3836,DHX37,2.392832,0.581633,0.559930,1,196,202,GGACG,False,...,CCAGCACGTGAGATGAAATCATCATCCACCCAGAGGCTGAGTCGCT...,73.755037,GGTGGATGATGATTTCATCTCACGTGCTGGACGCTGTTCTGTTCAG...,False,CGCTGTTCTGTTCAGTGTGCTCTTTGGACT,GGTGGATGATGATTTCATCTCACGTGCTGG,0.0,0.0,NaN,0.0
18,NM_020223:2709,FAM20C,2.897343,0.927273,0.938492,-1,275,283,AGACG,False,...,CTCTGTTTATATACTTATTCATCAAATATACAGAGGCTGAGTCGCT...,73.105580,TATATTTGATGAATAAGTATATAAACAGAGACGTGTACACAGATGC...,False,CGTGTACACAGATGCCAATCACCTACCAAA,TATATTTGATGAATAAGTATATAAACAGAG,0.0,0.0,NaN,0.0
20,NM_002048:1328,GAS1,2.446113,0.545098,0.639591,1,255,263,GGACG,False,...,CCGTGCAGCGCAGCCCGTTGAAGACTTTGCCAGAGGCTGAGTCGCT...,79.177090,GCAAAGTCTTCAACGGGCTGCGCTGCACGGACGAATGCCGCACCGT...,False,CGAATGCCGCACCGTCATTGAGGACATGCT,GCAAAGTCTTCAACGGGCTGCGCTGCACGG,0.0,0.0,NaN,0.0
23,NM_004807:1223,HS6ST1,2.900648,0.723485,0.785714,1,264,269,GGACG,False,...,CCGCTCGAACAGGTACTGCGTCTTGCGCTGCAGAGGCTGAGTCGCT...,78.147578,CAGCGCAAGACGCAGTACCTGTTCGAGCGGACGTTCAACCTCAAGT...,False,CGTTCAACCTCAAGTTCATCCGGCCCTTCA,CAGCGCAAGACGCAGTACCTGTTCGAGCGG,0.0,0.0,NaN,0.0
24,NM_012405:992,ICMT,3.128682,0.874494,0.915624,-1,741,763,GGATT,False,...,CCATGTGGCAGCGGCCAACCGGAAACAGTTCAGAGGCTGAGTCGCT...,78.730206,AACTGTTTCCGGTTGGCCGCTGCCACATGGATTTTCTTAATCGTTT...,False,TTTTCTTAATCGTTTTATGTCATTAGTCAC,AACTGTTTCCGGTTGGCCGCTGCCACATGG,0.0,0.0,NaN,0.0
30,NM_015353:1241,KCTD2,3.230837,0.990000,0.962119,1,100,100,GGACG,False,...,CCATTGTGGCACACATAGGGTGAAACCATGCAGAGGCTGAGTCGCT...,77.518362,CATGGTTTCACCCTATGTGTGCCACAATGGACGTTAGCAGCTGCTT...,False,CGTTAGCAGCTGCTTCGGAACACCGTCCCT,CATGGTTTCACCCTATGTGTGCCACAATGG,0.0,0.0,NaN,0.0
31,NM_014851:2195,KLHL21,2.557589,0.954887,0.892284,1,133,136,GGACG,False,...,CCTCTCCCAAGGTGGGAACAAGTAGGTGCACAGAGGCTGAGTCGCT...,78.838041,TGCACCTACTTGTTCCCACCTTGGGAGAGGACGATGACTTGGGAGG...,False,CGATGACTTGGGAGGGACGCGTGAAGGGAG,TGCACCTACTTGTTCCCACCTTGGGAGAGG,0.0,0.0,NaN,0.0
34,NM_014916:6647,LMTK2,2.626910,0.821782,0.838346,-1,101,103,GGACG,False,...,CCGCCTGCATTTTGCACTAGGACTCAACTTCAGAGGCTGAGTCGCT...,76.023264,AAGTTGAGTCCTAGTGCAAAATGCAGGCGGACGTTGCCAGAGAGTG...,False,CGTTGCCAGAGAGTGCGCAGCAAATGACCT,AAGTTGAGTCCTAGTGCAAAATGCAGGCGG,0.0,0.0,NaN,0.0
35,NM_138699:1421,LOC93622,2.395810,0.714286,0.000000,-3,224,226,GGACG,False,...,CCACTGGGCCTTCTTAATCTCATCCAAAGTCAGAGGCTGAGTCGCT...,76.486079,ACTTTGGATGAGATTAAGAAGGCCCAGTGGACGGTTGGTCTTGAAG...,False,CGGTTGGTCTTGAAGAGTGGCAGTGTGTGG,ACTTTGGATGAGATTAAGAAGGCCCAGTGG,0.0,0.0,NaN,0.0
36,NM_145021:1545,MARCHF8,2.818896,0.961538,0.951042,1,52,53,GGATA,False,...,CCATGTTTATTTTCAAAGTTGGGCTCTGTTCAGAGGCTGAGTCGCT...,70.648682,AACAGAGCCCAACTTTGAAAATAAACATGGATATGGAATCTGTCAT...,False,TATGGAATCTGTCATTCCGACACAAACTCT,AACAGAGCCCAACTTTGAAAATAAACATGG,0.0,0.0,NaN,0.0
38,NM_018019:971,MED9,2.605900,0.674074,0.649218,1,135,142,GGACG,False,...,CCAGTGAATTCTATGCAAATGTTTCAAGAACAGAGGCTGAGTCGCT...,72.867059,TTCTTGAAACATTTGCATAGAATTCACTGGACGAATTAAGCCTGCA...,False,CGAATTAAGCCTGCACTCATATGGCATAGA,TTCTTGAAACATTTGCATAGAATTCACTGG,0.0,0.0,NaN,0.0
39,NM_001543:398,NDST1,3.558805,0.902913,0.907443,-1,103,103,GGACG,False,...,CCACTGACCAACAAATTCACAGAGACTTAGCAGAGGCTGAGTCGCT...,78.950781,CTAAGTCTCTGTGAATTTGTTGGTCAGTGGACGATTCTCGTGTCTC...,False,CGATTCTCGTGTCTCCTCCTGTGTGGGGCC,CTAAGTCTCTGTGAATTTGTTGGTCAGTGG,0.0,0.0,NaN,0.0
44,NM_005392:3674,PHF2,3.082356,0.906667,0.887916,1,150,153,GGACG,False,...,CCATTTTCAAATTGAGGGGCCACGCTGGGCCAGAGGCTGAGTCGCT...,78.151217,GCCCAGCGTGGCCCCTCAATTTGAAAATGGACGTCTTTTCTCAAGT...,False,CGTCTTTTCTCAAGTTGCTAAGAGTGATCT,GCCCAGCGTGGCCCCTCAATTTGAAAATGG,0.0,0.0,NaN,0.0
52,NM_017841:583,SDHAF2,2.866309,0.905325,0.918439,1,169,170,GGACG,False,...,CCATCATAAGTAGTTACCATCCACAGACTGCAGAGGCTGAGTCGCT...,75.742049,CAGTCTGTGGATGGTAACTACTTATGATGGACGTTAGCCTTGCTTC...,False,CGTTAGCCTTGCTTCCGGCTTCTTAGATGC,CAGTCTGTGGATGGTAACTACTTATGATGG,0.0,0.0,NaN,0.0
53,NM_006598:3539,SLC12A7,2.939813,0.892045,0.947167,-1,176,186,GGACG,False,...,CCAGCCACGCCCTGATTTGCTGAGCCTGTTCAGAGGCTGAGTCGCT...,78.083963,AACAGGCTCAGCAAATCAGGGCGTGGCTGGACGATTTCCTTGCATC...,False,CGATTTCCTTGCATCTGAGGGCAGACGCTG,AACAGGCTCAGCAAATCAGGGCGTGGCTGG,0.0,0.0,NaN,0.0
59,NR_024279:2534,SPEN-AS1,2.452236,0.691803,0.000000,-3,305,310,AGACG,False,...,CTCATTCTACTCCGTCTTTCAGCACGTCAACAGAGGCTGAGTCGCT...,74.057431,TTGACGTGCTGAAAGACGGAGTAGAATGAGACGTTGGTTTTCATTG...,False,CGTTGGTTTTCATTGGCTGGCCATTAAGCA,TTGACGTGCTGAAAGACGGAGTAGAATGAG,0.0,0.0,NaN,0.0
60,NM_173216:4332,ST6GAL1,2.827898,0.790909,0.755233,-1,110,111,GGACG,False,...,CCATATCATAATTTGCATTTTACCAAAGTGCAGAGGCTGAGTCGCT...,70.516794,CACTTTGGTAAAATGCAAATTATGATATGGACGTTATCATTGGTCT...,False,CGTTATCATTGGTCTGGTGAGATGTTTCAT,CACTTTGGTAAAATGCAAATTATGATATGG,0.0,0.0,NaN,0.0
65,NM_012288:1898,TRAM2,3.093027,0.880597,0.961576,1,67,69,GGACG,False,...,CCCAAAGCCAAATGCCTTGGCATTTACAACCAGAGGCTGAGTCGCT...,74.608364,GTTGTAAATGCCAAGGCATTTGGCTTTGGGACGTGACAACTCAATC...,False,CGTGACAACTCAATCCAGAAGGATGGTGTG,GTTGTAAATGCCAAGGCATTTGGCTTTGGG,0.0,0.0,NaN,0.0
4,NM_001170629:536,CHD8,1.165228,0.746835,0.000000,0,79,84,AGAAC,False,...,NaN,NaN,NaN,NaN,ACTTTCCAAAGAATCCACAGCTCCAGCTCC,TCCCTCCACCAGAGGAAACAGCTCCCACAG,0.0,0.0,1.009193,0.0
9,NM_001316938:1630,FBXL12,1.174176,0.250000,0.410789,1,20,22,GGACG,False,...,NaN,NaN,NaN,NaN,CGGATGAAGAAGGGGTGGGGTTAAGACTCA,GTCACCTTCATGGTCGTCTTCAGGAACAGG,0.0,0.0,0.702675,0.0
12,NM_001371462:2250,GALNT11,0.947466,0.208333,0.630171,-1,24,24,GGAGT,False,...,NaN,NaN,NaN,NaN,GTTTGGGGCTTTAGGAAAGCCTGGGTTGGG,TTGCTTCATCAGGCGTTGCCTCCGGTGTGG,0.0,0.0,0.554661,0.0
21,NR_040103:1355,NAXD,0.880428,0.821429,0.000000,0,28,34,TGAAC,False,...,NaN,NaN,NaN,NaN,ACTTTCCTTAGCTCCTTGGTAGTAACTGGG,GTTATGGCGACACTAAACAAAGTATTCCTG,0.0,0.0,0.808055,0.0
24,NM_001172437:509,PEG10,0.808276,0.148148,0.000000,-3,27,28,GGACG,False,...,NaN,NaN,NaN,NaN,CGAGCTCTCTGAAGAGATCAACAACTTAAG,GTGTCCCCAACATGACCGAACGAAGAAGGG,0.0,0.0,0.450523,0.0
26,NM_003913:416,PRPF4B,0.733431,0.489510,0.000000,-1,143,166,AGAAC,False,...,NaN,NaN,NaN,NaN,ACTAAACTTGATGATTTAGCTTTGCTAGAA,TGATAAAGAGGGTATGTCTCCAGCAAAAAG,0.0,0.0,0.521564,0.0
34,NM_001113361:2293,TBC1D14,0.775750,0.931035,0.000000,0,29,33,AAAAC,False,...,NaN,NaN,NaN,NaN,ACTTTTAAAGAATTAAACCAAGGCTTAGCC,GGAGTTGGCCTTAAACAAAACAAACACAAA,0.0,0.0,0.756598,0.0
36,NM_018052:1605,VAC14,0.893817,0.503704,0.000000,-1,135,151,AGACG,False,...,NaN,NaN,NaN,NaN,CGTTATCGGATGAATCGGATGAGGTGATCC,ACGGACAGCCTCTTTCCCATCCTACTGCAG,0.0,0.0,0.646648,0.0
37,NR_001564:546,XIST,0.778385,0.609756,0.000000,-3,82,92,TGAAC,False,...,NaN,NaN,NaN,NaN,ACCCCCAACACTCTGGCCCATCGGGGTGAC,TCGGATACCTGCTGATTCCCTTCCCCTCTG,0.0,0.0,0.621211,0.0
38,NM_001354729:1390,XPC,1.221978,0.192308,0.213089,-1,26,26,GGATT,False,...,NaN,NaN,NaN,NaN,TTCCGAACCTGGCCCTCCAAAGCAGAGGAA,GTGGAGAAGCCTCTGATCCCTCTGATGAGG,0.0,0.0,0.698606,0.0

In [289]:
up_seq= "tagccagtaccgtagtgcgtg".upper()
down_seq = "cagaggctgagtcgctgcat".upper()
data_df["up_probe_30"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+31]), axis=1)
data_df["down_probe_30"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-30:x["pos"]])+down_seq, axis=1)
data_df["up_probe_25"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+26]), axis=1)
data_df["down_probe_25"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-25:x["pos"]])+down_seq, axis=1)
data_df["up_probe_20"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+21]), axis=1)
data_df["down_probe_20"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-20:x["pos"]])+down_seq, axis=1)

from Bio.SeqUtils import MeltingTemp as mt
tmfunc = (lambda x: mt.Tm_NN(x, saltcorr=6, nn_table=mt.DNA_NN4))
data_df["tm_up_30"] = data_df["up_probe_30"].apply(tmfunc)
data_df["tm_down_30"] = data_df["down_probe_30"].apply(tmfunc)
data_df["tm_up_25"] = data_df["up_probe_25"].apply(tmfunc)
data_df["tm_down_25"] = data_df["down_probe_25"].apply(tmfunc)
data_df["tm_up_20"] = data_df["up_probe_20"].apply(tmfunc)
data_df["tm_down_20"] = data_df["down_probe_20"].apply(tmfunc)

repeats = ["A"*5, "C"*5, "G"*5, "T"*5]
data_df["seq"] = data_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-30:x["pos"]+31], axis=1)
data_df["has_repeat"] = data_df["seq"].apply(lambda x: any([repeat in x for repeat in repeats]))
data_df= data_df[~data_df["has_repeat"]].copy()

data_df["tm_max"] = data_df[["tm_up_30", "tm_down_30", "tm_up_25", "tm_down_25", "tm_up_20", "tm_down_20"]].max(axis=1)
data_df = data_df[data_df["tm_max"] < 78].copy()
data_df.drop(columns=["noisy_or", "tm_up_30", "tm_down_30", "tm_up_25", "tm_down_25", "tm_up_20", "tm_down_20",
                      "up_probe_25", "down_probe_25", "up_probe_20", "down_probe_20", "up_probe", "down_probe",
                      "up_count", "down_count"
                      ], inplace=True)

pos_site_df = data_df.copy()
pos_site_df

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,m6a_count,transcript_length,m6a_density,pos,up_probe_30,down_probe_30,tm_max,seq,has_repeat,blast_hit
0,NM_014913:3321,ADNP2,2.610246,0.716867,0.639166,-1,166,170,GGACG,False,...,32.0,5157.0,0.006205,3321,TAGCCAGTACCGTAGTGCGTGGGATCTAATGCTAAAATCTGAAGAG...,CCTTGACAATAGGTCCCTCTGTTCTGCTTTCAGAGGCTGAGTCGCT...,72.690258,AAAGCAGAACAGAGGGACCTATTGTCAAGGACGAGGCTCTTCAGAT...,False,0.0
1,NM_032375:481,AKT1S1,2.408016,0.666667,0.650000,-1,93,96,GGACG,False,...,3.0,2447.0,0.001226,481,TAGCCAGTACCGTAGTGCGTGCCACAGTAAACGAAGGCAAGCGACC...,CCCTGACCCACAATAAACTTCTTCGACAAACAGAGGCTGAGTCGCT...,76.384300,TTTGTCGAAGAAGTTTATTGTGGGTCAGGGACGTCAGGTCGCTTGC...,False,0.0
8,NM_005180:1768,BMI1,2.545544,0.925816,0.895357,1,337,339,GGACG,False,...,6.0,3540.0,0.001695,1768,TAGCCAGTACCGTAGTGCGTGTATAACAACAATCTTTCTTTTCAAT...,CCATAGGAGTATCACATGTAGTCCATCTTTCAGAGGCTGAGTCGCT...,70.512505,AAAGATGGACTACATGTGATACTCCTATGGACGTTAATTGAAAAGA...,False,0.0
10,NM_015005:2554,CEP170B,2.972945,0.943662,0.955357,-1,71,74,GGACG,False,...,20.0,6700.0,0.002985,2554,TAGCCAGTACCGTAGTGCGTGGCCGCAAGCGGTTTCCTAGATAACA...,CCCCATTCTGGTCCCCAATGAAGAAAGAGGCAGAGGCTGAGTCGCT...,76.951973,CCTCTTTCTTCATTGGGGACCAGAATGGGGACGCTGTGTTATCTAG...,False,0.0
11,NM_004854:1260,CHST10,2.654569,0.611111,0.684800,-1,198,201,GGACG,False,...,18.0,2854.0,0.006307,1260,TAGCCAGTACCGTAGTGCGTGCCAGCCTCTTTTAAGATGTATGGGG...,CCTCCAGGGTCTCGTGGTGTCCAATCACACCAGAGGCTGAGTCGCT...,77.744087,GTGTGATTGGACACCACGAGACCCTGGAGGACGATGCCCCATACAT...,False,0.0
14,NM_032656:3836,DHX37,2.392832,0.581633,0.559930,1,196,202,GGACG,False,...,3.0,4559.0,0.000658,3836,TAGCCAGTACCGTAGTGCGTGAGTCCAAAGAGCACACTGAACAGAA...,CCAGCACGTGAGATGAAATCATCATCCACCCAGAGGCTGAGTCGCT...,73.755037,GGTGGATGATGATTTCATCTCACGTGCTGGACGCTGTTCTGTTCAG...,False,0.0
18,NM_020223:2709,FAM20C,2.897343,0.927273,0.938492,-1,275,283,AGACG,False,...,16.0,3176.0,0.005038,2709,TAGCCAGTACCGTAGTGCGTGTTTGGTAGGTGATTGGCATCTGTGT...,CTCTGTTTATATACTTATTCATCAAATATACAGAGGCTGAGTCGCT...,73.105580,TATATTTGATGAATAAGTATATAAACAGAGACGTGTACACAGATGC...,False,0.0
30,NM_015353:1241,KCTD2,3.230837,0.990000,0.962119,1,100,100,GGACG,False,...,17.0,3657.0,0.004649,1241,TAGCCAGTACCGTAGTGCGTGAGGGACGGTGTTCCGAAGCAGCTGC...,CCATTGTGGCACACATAGGGTGAAACCATGCAGAGGCTGAGTCGCT...,77.518362,CATGGTTTCACCCTATGTGTGCCACAATGGACGTTAGCAGCTGCTT...,False,0.0
34,NM_014916:6647,LMTK2,2.626910,0.821782,0.838346,-1,101,103,GGACG,False,...,28.0,8974.0,0.003120,6647,TAGCCAGTACCGTAGTGCGTGAGGTCATTTGCTGCGCACTCTCTGG...,CCGCCTGCATTTTGCACTAGGACTCAACTTCAGAGGCTGAGTCGCT...,76.023264,AAGTTGAGTCCTAGTGCAAAATGCAGGCGGACGTTGCCAGAGAGTG...,False,0.0
35,NM_138699:1421,LOC93622,2.395810,0.714286,0.000000,-3,224,226,GGACG,False,...,9.0,1973.0,0.004562,1421,TAGCCAGTACCGTAGTGCGTGCCACACACTGCCACTCTTCAAGACC...,CCACTGGGCCTTCTTAATCTCATCCAAAGTCAGAGGCTGAGTCGCT...,76.486079,ACTTTGGATGAGATTAAGAAGGCCCAGTGGACGGTTGGTCTTGAAG...,False,0.0
36,NM_145021:1545,MARCHF8,2.818896,0.961538,0.951042,1,52,53,GGATA,False,...,9.0,5281.0,0.001704,1545,TAGCCAGTACCGTAGTGCGTGAGAGTTTGTGTCGGAATGACAGATT...,CCATGTTTATTTTCAAAGTTGGGCTCTGTTCAGAGGCTGAGTCGCT...,70.648682,AACAGAGCCCAACTTTGAAAATAAACATGGATATGGAATCTGTCAT...,False,0.0
38,NM_018019:971,MED9,2.605900,0.674074,0.649218,1,135,142,GGACG,False,...,8.0,2209.0,0.003622,971,TAGCCAGTACCGTAGTGCGTGTCTATGCCATATGAGTGCAGGCTTA...,CCAGTGAATTCTATGCAAATGTTTCAAGAACAGAGGCTGAGTCGCT...,72.867059,TTCTTGAAACATTTGCATAGAATTCACTGGACGAATTAAGCCTGCA...,False,0.0
52,NM_017841:583,SDHAF2,2.866309,0.905325,0.918439,1,169,170,GGACG,False,...,5.0,1186.0,0.004216,583,TAGCCAGTACCGTAGTGCGTGGCATCTAAGAAGCCGGAAGCAAGGC...,CCATCATAAGTAGTTACCATCCACAGACTGCAGAGGCTGAGTCGCT...,75.742049,CAGTCTGTGGATGGTAACTACTTATGATGGACGTTAGCCTTGCTTC...,False,0.0
59,NR_024279:2534,SPEN-AS1,2.452236,0.691803,0.000000,-3,305,310,AGACG,False,...,8.0,2732.0,0.002928,2534,TAGCCAGTACCGTAGTGCGTGTGCTTAATGGCCAGCCAATGAAAAC...,CTCATTCTACTCCGTCTTTCAGCACGTCAACAGAGGCTGAGTCGCT...,74.057431,TTGACGTGCTGAAAGACGGAGTAGAATGAGACGTTGGTTTTCATTG...,False,0.0
60,NM_173216:4332,ST6GAL1,2.827898,0.790909,0.755233,-1,110,111,GGACG,False,...,12.0,4604.0,0.002606,4332,TAGCCAGTACCGTAGTGCGTGATGAAACATCTCACCAGACCAATGA...,CCATATCATAATTTGCATTTTACCAAAGTGCAGAGGCTGAGTCGCT...,70.516794,CACTTTGGTAAAATGCAAATTATGATATGGACGTTATCATTGGTCT...,False,0.0
65,NM_012288:1898,TRAM2,3.093027,0.880597,0.961576,1,67,69,GGACG,False,...,11.0,7047.0,0.001561,1898,TAGCCAGTACCGTAGTGCGTGCACACCATCCTTCTGGATTGAGTTG...,CCCAAAGCCAAATGCCTTGGCATTTACAACCAGAGGCTGAGTCGCT...,74.608364,GTTGTAAATGCCAAGGCATTTGGCTTTGGGACGTGACAACTCAATC...,False,0.0
4,NM_001170629:536,CHD8,1.165228,0.746835,0.000000,0,79,84,AGAAC,False,...,20.0,8467.0,0.002362,536,TAGCCAGTACCGTAGTGCGTGGGAGCTGGAGCTGTGGATTCTTTGG...,CTGTGGGAGCTGTTTCCTCTGGTGGAGGGACAGAGGCTGAGTCGCT...,77.785008,TCCCTCCACCAGAGGAAACAGCTCCCACAGAACTTTCCAAAGAATC...,False,0.0
9,NM_001316938:1630,FBXL12,1.174176,0.250000,0.410789,1,20,22,GGACG,False,...,6.0,1917.0,0.003130,1630,TAGCCAGTACCGTAGTGCGTGTGAGTCTTAACCCCACCCCTTCTTC...,CCTGTTCCTGAAGACGACCATGAAGGTGACCAGAGGCTGAGTCGCT...,77.191770,GTCACCTTCATGGTCGTCTTCAGGAACAGGACGGATGAAGAAGGGG...,False,0.0
21,NR_040103:1355,NAXD,0.880428,0.821429,0.000000,0,28,34,TGAAC,False,...,10.0,2612.0,0.003828,1355,TAGCCAGTACCGTAGTGCGTGCCCAGTTACTACCAAGGAGCTAAGG...,CAGGAATACTTTGTTTAGTGTCGCCATAACCAGAGGCTGAGTCGCT...,74.297754,GTTATGGCGACACTAAACAAAGTATTCCTGAACTTTCCTTAGCTCC...,False,0.0
24,NM_001172437:509,PEG10,0.808276,0.148148,0.000000,-3,27,28,GGACG,False,...,24.0,6639.0,0.003615,509,TAGCCAGTACCGTAGTGCGTGCTTAAGTTGTTGATCTCTTCAGAGA...,CCCTTCTTCGTTCGGTCATGTTGGGGACACCAGAGGCTGAGTCGCT...,76.897641,GTGTCCCCAACATGACCGAACGAAGAAGGGACGAGCTCTCTGAAGA...,False,0.0
36,NM_018052:1605,VAC14,0.893817,0.503704,0.000000,-1,135,151,AGACG,False,...,2.0,3096.0,0.000646,1605,TAGCCAGTACCGTAGTGCGTGGGATCACCTCATCCGATTCATCCGA...,CTGCAGTAGGATGGGAAAGAGGCTGTCCGTCAGAGGCTGAGTCGCT...,76.223088,ACGGACAGCCTCTTTCCCATCCTACTGCAGACGTTATCGGATGAAT...,False,0.0
38,NM_001354729:1390,XPC,1.221978,0.192308,0.213089,-1,26,26,GGATT,False,...,6.0,3632.0,0.001652,1390,TAGCCAGTACCGTAGTGCGTGTTCCTCTGCTTTGGAGGGCCAGGTT...,CCTCATCAGAGGGATCAGAGGCTTCTCCACCAGAGGCTGAGTCGCT...,77.984993,GTGGAGAAGCCTCTGATCCCTCTGATGAGGATTCCGAACCTGGCCC...,False,0.0

In [290]:
pos_site_df["seq"] = pos_site_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-50:x["pos"]+51], axis=1)
pos_site_df["mfe"] = pos_site_df["seq"].apply(lambda x: RNA.fold(x)[1])
pos_site_df["gc"] = pos_site_df["seq"].apply(lambda x: (x.count("G")+x.count("C"))/len(x))
pos_site_df.drop(columns=["seq"], inplace=True)

In [291]:
pos_site_df

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,transcript_length,m6a_density,pos,up_probe_30,down_probe_30,tm_max,has_repeat,blast_hit,mfe,gc
0,NM_014913:3321,ADNP2,2.610246,0.716867,0.639166,-1,166,170,GGACG,False,...,5157.0,0.006205,3321,TAGCCAGTACCGTAGTGCGTGGGATCTAATGCTAAAATCTGAAGAG...,CCTTGACAATAGGTCCCTCTGTTCTGCTTTCAGAGGCTGAGTCGCT...,72.690258,False,0.0,-17.299999,0.376238
1,NM_032375:481,AKT1S1,2.408016,0.666667,0.650000,-1,93,96,GGACG,False,...,2447.0,0.001226,481,TAGCCAGTACCGTAGTGCGTGCCACAGTAAACGAAGGCAAGCGACC...,CCCTGACCCACAATAAACTTCTTCGACAAACAGAGGCTGAGTCGCT...,76.384300,False,0.0,-25.000000,0.475248
8,NM_005180:1768,BMI1,2.545544,0.925816,0.895357,1,337,339,GGACG,False,...,3540.0,0.001695,1768,TAGCCAGTACCGTAGTGCGTGTATAACAACAATCTTTCTTTTCAAT...,CCATAGGAGTATCACATGTAGTCCATCTTTCAGAGGCTGAGTCGCT...,70.512505,False,0.0,-10.800000,0.297030
10,NM_015005:2554,CEP170B,2.972945,0.943662,0.955357,-1,71,74,GGACG,False,...,6700.0,0.002985,2554,TAGCCAGTACCGTAGTGCGTGGCCGCAAGCGGTTTCCTAGATAACA...,CCCCATTCTGGTCCCCAATGAAGAAAGAGGCAGAGGCTGAGTCGCT...,76.951973,False,0.0,-33.700001,0.633663
11,NM_004854:1260,CHST10,2.654569,0.611111,0.684800,-1,198,201,GGACG,False,...,2854.0,0.006307,1260,TAGCCAGTACCGTAGTGCGTGCCAGCCTCTTTTAAGATGTATGGGG...,CCTCCAGGGTCTCGTGGTGTCCAATCACACCAGAGGCTGAGTCGCT...,77.744087,False,0.0,-26.700001,0.504950
14,NM_032656:3836,DHX37,2.392832,0.581633,0.559930,1,196,202,GGACG,False,...,4559.0,0.000658,3836,TAGCCAGTACCGTAGTGCGTGAGTCCAAAGAGCACACTGAACAGAA...,CCAGCACGTGAGATGAAATCATCATCCACCCAGAGGCTGAGTCGCT...,73.755037,False,0.0,-28.500000,0.435644
18,NM_020223:2709,FAM20C,2.897343,0.927273,0.938492,-1,275,283,AGACG,False,...,3176.0,0.005038,2709,TAGCCAGTACCGTAGTGCGTGTTTGGTAGGTGATTGGCATCTGTGT...,CTCTGTTTATATACTTATTCATCAAATATACAGAGGCTGAGTCGCT...,73.105580,False,0.0,-9.600000,0.346535
30,NM_015353:1241,KCTD2,3.230837,0.990000,0.962119,1,100,100,GGACG,False,...,3657.0,0.004649,1241,TAGCCAGTACCGTAGTGCGTGAGGGACGGTGTTCCGAAGCAGCTGC...,CCATTGTGGCACACATAGGGTGAAACCATGCAGAGGCTGAGTCGCT...,77.518362,False,0.0,-22.700001,0.574257
34,NM_014916:6647,LMTK2,2.626910,0.821782,0.838346,-1,101,103,GGACG,False,...,8974.0,0.003120,6647,TAGCCAGTACCGTAGTGCGTGAGGTCATTTGCTGCGCACTCTCTGG...,CCGCCTGCATTTTGCACTAGGACTCAACTTCAGAGGCTGAGTCGCT...,76.023264,False,0.0,-27.200001,0.554455
35,NM_138699:1421,LOC93622,2.395810,0.714286,0.000000,-3,224,226,GGACG,False,...,1973.0,0.004562,1421,TAGCCAGTACCGTAGTGCGTGCCACACACTGCCACTCTTCAAGACC...,CCACTGGGCCTTCTTAATCTCATCCAAAGTCAGAGGCTGAGTCGCT...,76.486079,False,0.0,-23.299999,0.495050
36,NM_145021:1545,MARCHF8,2.818896,0.961538,0.951042,1,52,53,GGATA,False,...,5281.0,0.001704,1545,TAGCCAGTACCGTAGTGCGTGAGAGTTTGTGTCGGAATGACAGATT...,CCATGTTTATTTTCAAAGTTGGGCTCTGTTCAGAGGCTGAGTCGCT...,70.648682,False,0.0,-10.600000,0.376238
38,NM_018019:971,MED9,2.605900,0.674074,0.649218,1,135,142,GGACG,False,...,2209.0,0.003622,971,TAGCCAGTACCGTAGTGCGTGTCTATGCCATATGAGTGCAGGCTTA...,CCAGTGAATTCTATGCAAATGTTTCAAGAACAGAGGCTGAGTCGCT...,72.867059,False,0.0,-16.799999,0.376238
52,NM_017841:583,SDHAF2,2.866309,0.905325,0.918439,1,169,170,GGACG,False,...,1186.0,0.004216,583,TAGCCAGTACCGTAGTGCGTGGCATCTAAGAAGCCGGAAGCAAGGC...,CCATCATAAGTAGTTACCATCCACAGACTGCAGAGGCTGAGTCGCT...,75.742049,False,0.0,-26.400000,0.564356
59,NR_024279:2534,SPEN-AS1,2.452236,0.691803,0.000000,-3,305,310,AGACG,False,...,2732.0,0.002928,2534,TAGCCAGTACCGTAGTGCGTGTGCTTAATGGCCAGCCAATGAAAAC...,CTCATTCTACTCCGTCTTTCAGCACGTCAACAGAGGCTGAGTCGCT...,74.057431,False,0.0,-25.799999,0.504950
60,NM_173216:4332,ST6GAL1,2.827898,0.790909,0.755233,-1,110,111,GGACG,False,...,4604.0,0.002606,4332,TAGCCAGTACCGTAGTGCGTGATGAAACATCTCACCAGACCAATGA...,CCATATCATAATTTGCATTTTACCAAAGTGCAGAGGCTGAGTCGCT...,70.516794,False,0.0,-16.900000,0.336634
65,NM_012288:1898,TRAM2,3.093027,0.880597,0.961576,1,67,69,GGACG,False,...,7047.0,0.001561,1898,TAGCCAGTACCGTAGTGCGTGCACACCATCCTTCTGGATTGAGTTG...,CCCAAAGCCAAATGCCTTGGCATTTACAACCAGAGGCTGAGTCGCT...,74.608364,False,0.0,-32.500000,0.534653
4,NM_001170629:536,CHD8,1.165228,0.746835,0.000000,0,79,84,AGAAC,False,...,8467.0,0.002362,536,TAGCCAGTACCGTAGTGCGTGGGAGCTGGAGCTGTGGATTCTTTGG...,CTGTGGGAGCTGTTTCCTCTGGTGGAGGGACAGAGGCTGAGTCGCT...,77.785008,False,0.0,-16.500000,0.495050
9,NM_001316938:1630,FBXL12,1.174176,0.250000,0.410789,1,20,22,GGACG,False,...,1917.0,0.003130,1630,TAGCCAGTACCGTAGTGCGTGTGAGTCTTAACCCCACCCCTTCTTC...,CCTGTTCCTGAAGACGACCATGAAGGTGACCAGAGGCTGAGTCGCT...,77.191770,False,0.0,-33.700001,0.554455
21,NR_040103:1355,NAXD,0.880428,0.821429,0.000000,0,28,34,TGAAC,False,...,2612.0,0.003828,1355,TAGCCAGTACCGTAGTGCGTGCCCAGTTACTACCAAGGAGCTAAGG...,CAGGAATACTTTGTTTAGTGTCGCCATAACCAGAGGCTGAGTCGCT...,74.297754,False,0.0,-13.800000,0.386139
24,NM_001172437:509,PEG10,0.808276,0.148148,0.000000,-3,27,28,GGACG,False,...,6639.0,0.003615,509,TAGCCAGTACCGTAGTGCGTGCTTAAGTTGTTGATCTCTTCAGAGA...,CCCTTCTTCGTTCGGTCATGTTGGGGACACCAGAGGCTGAGTCGCT...,76.897641,False,0.0,-20.700001,0.504950
36,NM_018052:1605,VAC14,0.893817,0.503704,0.000000,-1,135,151,AGACG,False,...,3096.0,0.000646,1605,TAGCCAGTACCGTAGTGCGTGGGATCACCTCATCCGATTCATCCGA...,CTGCAGTAGGATGGGAAAGAGGCTGTCCGTCAGAGGCTGAGTCGCT...,76.223088,False,0.0,-32.299999,0.554455
38,NM_001354729:1390,XPC,1.221978,0.192308,0.213089,-1,26,26,GGATT,False,...,3632.0,0.001652,1390,TAGCCAGTACCGTAGTGCGTGTTCCTCTGCTTTGGAGGGCCAGGTT...,CCTCATCAGAGGGATCAGAGGCTTCTCCACCAGAGGCTGAGTCGCT...,77.984993,False,0.0,-33.099998,0.564356

In [293]:
pos_site_df = pos_site_df[(pos_site_df["gc"] >= 0.4) & (pos_site_df["gc"] <= 0.6)].copy()
pos_site_df

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,transcript_length,m6a_density,pos,up_probe_30,down_probe_30,tm_max,has_repeat,blast_hit,mfe,gc
1,NM_032375:481,AKT1S1,2.408016,0.666667,0.650000,-1,93,96,GGACG,False,...,2447.0,0.001226,481,TAGCCAGTACCGTAGTGCGTGCCACAGTAAACGAAGGCAAGCGACC...,CCCTGACCCACAATAAACTTCTTCGACAAACAGAGGCTGAGTCGCT...,76.384300,False,0.0,-25.000000,0.475248
11,NM_004854:1260,CHST10,2.654569,0.611111,0.684800,-1,198,201,GGACG,False,...,2854.0,0.006307,1260,TAGCCAGTACCGTAGTGCGTGCCAGCCTCTTTTAAGATGTATGGGG...,CCTCCAGGGTCTCGTGGTGTCCAATCACACCAGAGGCTGAGTCGCT...,77.744087,False,0.0,-26.700001,0.504950
14,NM_032656:3836,DHX37,2.392832,0.581633,0.559930,1,196,202,GGACG,False,...,4559.0,0.000658,3836,TAGCCAGTACCGTAGTGCGTGAGTCCAAAGAGCACACTGAACAGAA...,CCAGCACGTGAGATGAAATCATCATCCACCCAGAGGCTGAGTCGCT...,73.755037,False,0.0,-28.500000,0.435644
30,NM_015353:1241,KCTD2,3.230837,0.990000,0.962119,1,100,100,GGACG,False,...,3657.0,0.004649,1241,TAGCCAGTACCGTAGTGCGTGAGGGACGGTGTTCCGAAGCAGCTGC...,CCATTGTGGCACACATAGGGTGAAACCATGCAGAGGCTGAGTCGCT...,77.518362,False,0.0,-22.700001,0.574257
34,NM_014916:6647,LMTK2,2.626910,0.821782,0.838346,-1,101,103,GGACG,False,...,8974.0,0.003120,6647,TAGCCAGTACCGTAGTGCGTGAGGTCATTTGCTGCGCACTCTCTGG...,CCGCCTGCATTTTGCACTAGGACTCAACTTCAGAGGCTGAGTCGCT...,76.023264,False,0.0,-27.200001,0.554455
35,NM_138699:1421,LOC93622,2.395810,0.714286,0.000000,-3,224,226,GGACG,False,...,1973.0,0.004562,1421,TAGCCAGTACCGTAGTGCGTGCCACACACTGCCACTCTTCAAGACC...,CCACTGGGCCTTCTTAATCTCATCCAAAGTCAGAGGCTGAGTCGCT...,76.486079,False,0.0,-23.299999,0.495050
52,NM_017841:583,SDHAF2,2.866309,0.905325,0.918439,1,169,170,GGACG,False,...,1186.0,0.004216,583,TAGCCAGTACCGTAGTGCGTGGCATCTAAGAAGCCGGAAGCAAGGC...,CCATCATAAGTAGTTACCATCCACAGACTGCAGAGGCTGAGTCGCT...,75.742049,False,0.0,-26.400000,0.564356
59,NR_024279:2534,SPEN-AS1,2.452236,0.691803,0.000000,-3,305,310,AGACG,False,...,2732.0,0.002928,2534,TAGCCAGTACCGTAGTGCGTGTGCTTAATGGCCAGCCAATGAAAAC...,CTCATTCTACTCCGTCTTTCAGCACGTCAACAGAGGCTGAGTCGCT...,74.057431,False,0.0,-25.799999,0.504950
65,NM_012288:1898,TRAM2,3.093027,0.880597,0.961576,1,67,69,GGACG,False,...,7047.0,0.001561,1898,TAGCCAGTACCGTAGTGCGTGCACACCATCCTTCTGGATTGAGTTG...,CCCAAAGCCAAATGCCTTGGCATTTACAACCAGAGGCTGAGTCGCT...,74.608364,False,0.0,-32.500000,0.534653
4,NM_001170629:536,CHD8,1.165228,0.746835,0.000000,0,79,84,AGAAC,False,...,8467.0,0.002362,536,TAGCCAGTACCGTAGTGCGTGGGAGCTGGAGCTGTGGATTCTTTGG...,CTGTGGGAGCTGTTTCCTCTGGTGGAGGGACAGAGGCTGAGTCGCT...,77.785008,False,0.0,-16.500000,0.495050
9,NM_001316938:1630,FBXL12,1.174176,0.250000,0.410789,1,20,22,GGACG,False,...,1917.0,0.003130,1630,TAGCCAGTACCGTAGTGCGTGTGAGTCTTAACCCCACCCCTTCTTC...,CCTGTTCCTGAAGACGACCATGAAGGTGACCAGAGGCTGAGTCGCT...,77.191770,False,0.0,-33.700001,0.554455
24,NM_001172437:509,PEG10,0.808276,0.148148,0.000000,-3,27,28,GGACG,False,...,6639.0,0.003615,509,TAGCCAGTACCGTAGTGCGTGCTTAAGTTGTTGATCTCTTCAGAGA...,CCCTTCTTCGTTCGGTCATGTTGGGGACACCAGAGGCTGAGTCGCT...,76.897641,False,0.0,-20.700001,0.504950
36,NM_018052:1605,VAC14,0.893817,0.503704,0.000000,-1,135,151,AGACG,False,...,3096.0,0.000646,1605,TAGCCAGTACCGTAGTGCGTGGGATCACCTCATCCGATTCATCCGA...,CTGCAGTAGGATGGGAAAGAGGCTGTCCGTCAGAGGCTGAGTCGCT...,76.223088,False,0.0,-32.299999,0.554455
38,NM_001354729:1390,XPC,1.221978,0.192308,0.213089,-1,26,26,GGATT,False,...,3632.0,0.001652,1390,TAGCCAGTACCGTAGTGCGTGTTCCTCTGCTTTGGAGGGCCAGGTT...,CCTCATCAGAGGGATCAGAGGCTTCTCCACCAGAGGCTGAGTCGCT...,77.984993,False,0.0,-33.099998,0.564356

In [255]:
neg_df = select_df[(select_df["log_pm6a"] < 0.05) & ((select_df["label"] == 0 )|( select_df["label"] == -3)) & (~select_df["drach"]) & (select_df["cell_perc"] > 0.9)].copy().sort_values("gene_id")
print(neg_df)

                label_id gene_id  log_pm6a  noisy_or       dom  dom_label  \
10894245   NM_015665:569    AAAS -0.000000 -0.000000  0.012000        0.0
10894190   NM_015665:337    AAAS -0.000000 -0.000000  0.020576        0.0
10894189   NM_015665:332    AAAS  0.010492  0.005417  0.037118        0.0
10894187   NM_015665:322    AAAS -0.000000 -0.000000  0.002033        0.0
10894186   NM_015665:321    AAAS -0.000000 -0.000000  0.012295        0.0
...                  ...     ...       ...       ...       ...        ...
10561998   NM_015113:391   ZZEF1  0.000000 -0.000000  0.000000        0.0
10561999  NM_015113:3914   ZZEF1  0.000000 -0.000000  0.000000        0.0
10562000  NM_015113:3916   ZZEF1  0.000000 -0.000000  0.000000        0.0
10561992  NM_015113:3885   ZZEF1  0.000000 -0.000000  0.000000        0.0
10562802  NM_015113:6850   ZZEF1 -0.000000 -0.000000  0.011628        0.0

          label  count_dom  count_all   5mer  drach  pred_dorado  \
10894245     -3        500        510  TGAAT  False       0.0000
10894190     -3        486        494  GCACA  False       0.0126
10894189     -3        458        491  CCATG  False       0.1163
10894187     -3        492        496  GAAGG  False       0.0020
10894186     -3        488        493  GGAAG  False       0.0020
...         ...        ...        ...    ...    ...          ...
10561998      0         21         21  AGAGC  False       0.0000
10561999      0         42         43  CCAGA  False       0.0238
10562000      0         43         43  AGAGT  False       0.0000
10561992      0         37         41  GGAAA  False       0.0000
10562802      0         86         88  GCACA  False       0.0000

          count_dorado  ivt_perc  cell_perc     refseq
10894245         512.0  0.988863   0.981754  NM_015665
10894190         478.0  0.988863   0.981754  NM_015665
10894189         361.0  0.988863   0.981754  NM_015665
10894187         494.0  0.988863   0.981754  NM_015665
10894186         496.0  0.988863   0.981754  NM_015665
...                ...       ...        ...        ...
10561998          21.0  0.859025   0.930025  NM_015113
10561999          42.0  0.859025   0.930025  NM_015113
10562000          43.0  0.859025   0.930025  NM_015113
10561992          39.0  0.859025   0.930025  NM_015113
10562802          81.0  0.859025   0.930025  NM_015113

[3208397 rows x 16 columns]

In [294]:
refseq_list = pos_site_df["refseq"].unique()

neg_df["refseq"] = neg_df["label_id"].str.split(":").str[0]
neg_site_df = neg_df[neg_df["refseq"].isin(refseq_list)].copy()
neg_site_df["gene_id"].value_counts()

gene_id
CHD8        1920
LMTK2       1794
PEG10       1623
TRAM2       1313
DHX37        757
KCTD2        588
XPC          552
VAC14        530
CHST10       525
LOC93622     365
AKT1S1       328
SPEN-AS1     280
SDHAF2       256
FBXL12        82
Name: count, dtype: int64

In [307]:
up_seq= "tagccagtaccgtagtgcgtg".upper()
down_seq = "cagaggctgagtcgctgcat".upper()

data_df = neg_site_df.copy().reset_index(drop=True)
data_df["pos"] = data_df["label_id"].str.split(":").str[1].astype(int)
data_df["up_probe_30"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+31]), axis=1)
data_df["down_probe_30"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-30:x["pos"]])+down_seq, axis=1)
data_df["up_probe_25"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+26]), axis=1)
data_df["down_probe_25"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-25:x["pos"]])+down_seq, axis=1)
data_df["up_probe_20"] = data_df.apply(lambda x: up_seq+revcomp_DNA(seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+21]), axis=1)
data_df["down_probe_20"] = data_df.apply(lambda x: revcomp_DNA(seq_dict[x["refseq"]][x["pos"]-20:x["pos"]])+down_seq, axis=1)

from Bio.SeqUtils import MeltingTemp as mt
tmfunc = (lambda x: mt.Tm_NN(x, saltcorr=6, nn_table=mt.DNA_NN4))
data_df["tm_up_30"] = data_df["up_probe_30"].apply(tmfunc)
data_df["tm_down_30"] = data_df["down_probe_30"].apply(tmfunc)
data_df["tm_up_25"] = data_df["up_probe_25"].apply(tmfunc)
data_df["tm_down_25"] = data_df["down_probe_25"].apply(tmfunc)
data_df["tm_up_20"] = data_df["up_probe_20"].apply(tmfunc)
data_df["tm_down_20"] = data_df["down_probe_20"].apply(tmfunc)

repeats = ["A"*5, "C"*5, "G"*5, "T"*5]
data_df["seq"] = data_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-30:x["pos"]+31], axis=1)
data_df["has_repeat"] = data_df["seq"].apply(lambda x: any([repeat in x for repeat in repeats]))
data_df= data_df[~data_df["has_repeat"]].copy()

data_df["tm_max"] = data_df[["tm_up_30", "tm_down_30", "tm_up_25", "tm_down_25", "tm_up_20", "tm_down_20"]].max(axis=1)
data_df = data_df[data_df["tm_max"] < 75].copy()
data_df.drop(columns=["tm_up_30", "tm_down_30", "tm_up_25", "tm_down_25", "tm_up_20", "tm_down_20",
                      "up_probe_25", "down_probe_25", "up_probe_20", "down_probe_20", "seq"
                      ], inplace=True)

In [308]:
data_df[data_df["log_pm6a"] == 0.0]["gene_id"].value_counts()

gene_id
PEG10       612
CHD8        519
LMTK2       362
TRAM2       242
XPC          86
LOC93622     75
KCTD2        60
CHST10       55
VAC14        46
SDHAF2       41
DHX37        30
SPEN-AS1     20
FBXL12       17
AKT1S1        9
Name: count, dtype: int64

In [309]:
data_df = data_df[data_df["log_pm6a"] == 0.0].copy()

In [310]:
data_df["gene_id"].value_counts()

gene_id
PEG10       612
CHD8        519
LMTK2       362
TRAM2       242
XPC          86
LOC93622     75
KCTD2        60
CHST10       55
VAC14        46
SDHAF2       41
DHX37        30
SPEN-AS1     20
FBXL12       17
AKT1S1        9
Name: count, dtype: int64

In [311]:
data_df["seq"] = data_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-50:x["pos"]+51], axis=1)
data_df = data_df[data_df["seq"].apply(len) == 101].copy()
data_df["mfe"] = data_df["seq"].apply(lambda x: RNA.fold(x)[1])
data_df["gc"] = data_df["seq"].apply(lambda x: (x.count("G")+x.count("C"))/len(x))
data_df.drop(columns=["seq"], inplace=True)

data_df = data_df[(data_df["gc"] >= 0.4) & (data_df["gc"] <= 0.6) & (data_df["mfe"] > -30)].copy()
data_df["gene_id"].value_counts()

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,ivt_perc,cell_perc,refseq,pos,up_probe_30,down_probe_30,has_repeat,tm_max,mfe,gc
1,NM_032375:459,AKT1S1,-0.0,0.012048,0.0,0,83,91,GAAGA,False,...,0.814711,0.963261,NM_032375,459,TAGCCAGTACCGTAGTGCGTGACCTGACGTCCCTGACCCACAATAA...,TCGACAAAAGTAGAGGAAATCGGTGCTCGTCAGAGGCTGAGTCGCT...,False,74.293441,-25.299999,0.485149
6,NM_032375:1971,AKT1S1,-0.0,0.029412,0.0,0,408,429,CCAGT,False,...,0.814711,0.963261,NM_032375,1971,TAGCCAGTACCGTAGTGCGTGAGGAAAAGCGGACGGTGACTATGTA...,GGTCAAGCCCTTTACAGGATTTGAGCCAATCAGAGGCTGAGTCGCT...,False,73.560597,-23.299999,0.485149
8,NM_032375:1816,AKT1S1,-0.0,0.064171,0.0,0,374,401,TTAAG,False,...,0.814711,0.963261,NM_032375,1816,TAGCCAGTACCGTAGTGCGTGTAGAGCTTAGAACTCAGCGAGCCAA...,AATAGAAGGAATCTGTCGCTAGGCGGAGAGCAGAGGCTGAGTCGCT...,False,74.412695,-33.799999,0.495050
9,NM_001170629:7079,CHD8,-0.0,0.022599,0.0,0,177,181,TGAGG,False,...,0.903009,0.967135,NM_001170629,7079,TAGCCAGTACCGTAGTGCGTGTGCTTCTGGAATGTTAACTTCAATC...,CATCTTTGATTTGAACTGTAAACTCCTTTTCAGAGGCTGAGTCGCT...,False,70.798859,-20.900000,0.425743
10,NM_001170629:7074,CHD8,0.0,0.000000,0.0,0,190,192,AAAGA,False,...,0.903009,0.967135,NM_001170629,7074,TAGCCAGTACCGTAGTGCGTGCTGGAATGTTAACTTCAATCCTTCC...,TTGATTTGAACTGTAAACTCCTTTTCATCCCAGAGGCTGAGTCGCT...,False,70.636140,-20.200001,0.415842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2167,NM_001354729:973,XPC,0.0,0.000000,0.0,0,20,20,ACAGC,False,...,0.900671,0.920128,NM_001354729,973,TAGCCAGTACCGTAGTGCGTGTTTGCTGTTGCTGACTTCAGAGGAA...,GTAGAGACAATACCAGCCGGGTCAAGAGCTCAGAGGCTGAGTCGCT...,False,74.840894,-20.100000,0.514851
2170,NM_001354729:2106,XPC,-0.0,0.033333,0.0,0,30,31,TGAGG,False,...,0.900671,0.920128,NM_001354729,2106,TAGCCAGTACCGTAGTGCGTGTCACCATCTTGTAGGGTACTTCTCC...,CACCACTCTTGCTTTCTTCAGCCACGTGTCCAGAGGCTGAGTCGCT...,False,74.811292,-28.600000,0.504950
2171,NM_001354729:2116,XPC,0.0,0.000000,0.0,0,31,31,AGAAG,False,...,0.900671,0.920128,NM_001354729,2116,TAGCCAGTACCGTAGTGCGTGGAAAAGCCTTTCACCATCTTGTAGG...,CTCCAAGCCTCACCACTCTTGCTTTCTTCACAGAGGCTGAGTCGCT...,False,73.802031,-26.799999,0.524752
2172,NM_001354729:2117,XPC,0.0,0.000000,0.0,0,31,31,GAAGT,False,...,0.900671,0.920128,NM_001354729,2117,TAGCCAGTACCGTAGTGCGTGAGAAAAGCCTTTCACCATCTTGTAG...,TCTCCAAGCCTCACCACTCTTGCTTTCTTCCAGAGGCTGAGTCGCT...,False,74.410102,-24.500000,0.524752
2173,NM_001354729:2120,XPC,0.0,0.000000,0.0,0,29,30,GTACC,False,...,0.900671,0.920128,NM_001354729,2120,TAGCCAGTACCGTAGTGCGTGGTTAGAAAAGCCTTTCACCATCTTG...,ACTTCTCCAAGCCTCACCACTCTTGCTTTCCAGAGGCTGAGTCGCT...,False,74.515202,-25.900000,0.524752

In [312]:
data_df["gene_id"].value_counts()

gene_id
CHD8        444
PEG10       326
TRAM2       183
LMTK2       149
KCTD2        55
LOC93622     49
XPC          47
VAC14        43
CHST10       36
SDHAF2       35
DHX37        28
FBXL12        9
SPEN-AS1      6
AKT1S1        3
Name: count, dtype: int64

In [314]:
data_df = data_df[(data_df["gc"] >= 0.4) & (data_df["gc"] <= 0.6) & (data_df["mfe"] > -30)].copy()

In [315]:
neg_site_df = data_df.copy()

## sample 10 sites per gene
cand_list = []
for gene_id in neg_site_df["gene_id"].unique():
    gene_df = neg_site_df[neg_site_df["gene_id"] == gene_id].copy()
    gene_df = gene_df.sample(min(10, len(gene_df)))
    cand_list.append(gene_df)
neg_site_df = pd.concat(cand_list)

neg_site_df

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,ivt_perc,cell_perc,refseq,pos,up_probe_30,down_probe_30,has_repeat,tm_max,mfe,gc
6,NM_032375:1971,AKT1S1,-0.0,0.029412,0.0,0,408,429,CCAGT,False,...,0.814711,0.963261,NM_032375,1971,TAGCCAGTACCGTAGTGCGTGAGGAAAAGCGGACGGTGACTATGTA...,GGTCAAGCCCTTTACAGGATTTGAGCCAATCAGAGGCTGAGTCGCT...,False,73.560597,-23.299999,0.485149
1,NM_032375:459,AKT1S1,-0.0,0.012048,0.0,0,83,91,GAAGA,False,...,0.814711,0.963261,NM_032375,459,TAGCCAGTACCGTAGTGCGTGACCTGACGTCCCTGACCCACAATAA...,TCGACAAAAGTAGAGGAAATCGGTGCTCGTCAGAGGCTGAGTCGCT...,False,74.293441,-25.299999,0.485149
334,NM_001170629:3089,CHD8,-0.0,0.017857,0.0,0,112,115,TGAGA,False,...,0.903009,0.967135,NM_001170629,3089,TAGCCAGTACCGTAGTGCGTGCGAAGCTCAGGACAATCTGACAAAA...,CAAAAGTGGTGATCAGAGCGTCAAACTTGTCAGAGGCTGAGTCGCT...,False,71.114928,-22.700001,0.465347
504,NM_001170629:1933,CHD8,0.0,0.000000,0.0,0,97,98,AGAAG,False,...,0.903009,0.967135,NM_001170629,1933,TAGCCAGTACCGTAGTGCGTGAATTATCAGATGAGGTATTACGTTT...,CTTACCCACTACAGGAGTGATGGTGTTGAGCAGAGGCTGAGTCGCT...,False,73.867675,-24.900000,0.425743
327,NM_001170629:3102,CHD8,-0.0,0.008929,0.0,0,112,115,TCAGA,False,...,0.903009,0.967135,NM_001170629,3102,TAGCCAGTACCGTAGTGCGTGCCATTCAATTTCACGAAGCTCAGGA...,GACAAAATCATCTCAAAAGTGGTGATCAGACAGAGGCTGAGTCGCT...,False,71.631519,-18.200001,0.415842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2164,NM_001354729:998,XPC,0.0,0.000000,0.0,0,20,20,ACAGC,False,...,0.900671,0.920128,NM_001354729,998,TAGCCAGTACCGTAGTGCGTGTCTTTCCTTGGAAGGTTTCTTTCCC...,GTTGCTGACTTCAGAGGAATTGGCTGTAGACAGAGGCTGAGTCGCT...,False,73.496918,-22.200001,0.495050
2104,NM_001354729:1106,XPC,0.0,0.000000,0.0,0,20,20,AAAGG,False,...,0.900671,0.920128,NM_001354729,1106,TAGCCAGTACCGTAGTGCGTGCTTAGCAAAGGTTTCCTCTTGTTTG...,TTGCTGGTCTTTGGTTTGGTGTGGTTTTCTCAGAGGCTGAGTCGCT...,False,73.470188,-18.200001,0.485149
2155,NM_001354729:3421,XPC,0.0,0.000000,0.0,0,38,39,CCAAG,False,...,0.900671,0.920128,NM_001354729,3421,TAGCCAGTACCGTAGTGCGTGTTTAGGCTTCTGTCACCACAAAATG...,GGAAAACTAGATCCCAGCAGATGACCTGTACAGAGGCTGAGTCGCT...,False,72.645052,-17.200001,0.415842
2093,NM_001354729:1546,XPC,-0.0,0.038462,0.0,0,26,26,CAAGA,False,...,0.900671,0.920128,NM_001354729,1546,TAGCCAGTACCGTAGTGCGTGTCTGCCTTCTCACCATCGCTGCACA...,TGCCTCTTTTACTGCTTGAAGAGCTTGAGGCAGAGGCTGAGTCGCT...,False,73.806027,-20.400000,0.485149
2100,NM_001354729:1863,XPC,0.0,0.000000,0.0,0,28,28,ACAGG,False,...,0.900671,0.920128,NM_001354729,1863,TAGCCAGTACCGTAGTGCGTGCCTGAAACTCCAAGTCTTCTTTCTT...,GTCCATAAATGGGCTCTGGTATGGTCTCAACAGAGGCTGAGTCGCT...,False,73.191701,-20.200001,0.514851

In [316]:
neg_site_df["pos"] = neg_site_df["label_id"].str.split(":").str[1].astype(int)

neg_site_df["up_probe"] = neg_site_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]+1:x["pos"]+31], axis=1)
neg_site_df["down_probe"] = neg_site_df.apply(lambda x: seq_dict[x["refseq"]][x["pos"]-30:x["pos"]], axis=1)

neg_up_probe_fasta = "\n".join([f">{label_id}\n{seq}" for label_id, seq in zip(neg_site_df["label_id"], neg_site_df["up_probe"])])
neg_down_probe_fasta = "\n".join([f">{label_id}\n{seq}" for label_id, seq in zip(neg_site_df["label_id"], neg_site_df["down_probe"])])

In [318]:
print(neg_up_probe_fasta)

>NM_032375:1971
GTCTCTACATAGTCACCGTCCGCTTTTCCT
>NM_032375:459
GAAGTTTATTGTGGGTCAGGGACGTCAGGT
>NM_001170629:3089
GATGATTTTGTCAGATTGTCCTGAGCTTCG
>NM_001170629:1933
AGAGAAAACGTAATACCTCATCTGATAATT
>NM_001170629:3102
GATTGTCCTGAGCTTCGTGAAATTGAATGG
>NM_001170629:4064
GGTGTACCGCCTCATCACTCGTAATTCCTA
>NM_001170629:2223
GATGCAGCCATTGTAGACAAAGTGCTTTCT
>NM_001170629:3376
TTCTTAAGCCAATGATGCTGAGAAGACTCA
>NM_001170629:7132
TGGGAGATGGACATCCACTGTTTCATAAGA
>NM_001170629:2531
GCCCGTTATTTACTACCTGGTGAAATGGTG
>NM_001170629:3836
ACGTATTGATGGGCGAGTTAGAGGCAACCT
>NM_001170629:3718
TTGACAAGTTGCTTCCAAAGCTTAAAGCTG
>NM_004854:495
TGTGTACAGTGCCAAACAGGAGTTTCTGTT
>NM_004854:1644
GTTTGGATGTAAGATGCTCTGAGGACCCTG
>NM_004854:689
AGAATCTCTCGCACACTCCTGTCTCCAAGT
>NM_004854:486
AGACCCAGATGTGTACAGTGCCAAACAGGA
>NM_004854:736
TTTGTCTGTGACAAGCACAAGATTCTTTTC
>NM_004854:753
CAAGATTCTTTTCTGCCAGACTCCCAAAGT
>NM_004854:2456
TTTCGATTCCTTTCATCTCAGCAAAATGGG
>NM_004854:2039
TTTTGTTCCTGTAGACAGTCAGCGATGGCC
>NM_004854:452
TGGTGGCTAGCAAGTTCATCACGTTGACCT
>NM_004854:470
TCACGTTGACCTTTAAAGACCCAGATGTGT
>NM_032656:331
AGGAGAAGAAAGTGCTGCAGAAAATCTTAG
>NM_032656:329
GAAGGAGAAGAAAGTGCTGCAGAAAATCTT
>NM_032656:2245
AGGCGCTCAACGTTGAAAAGGTCATCAACT
>NM_032656:328
AGAAGGAGAAGAAAGTGCTGCAGAAAATCT
>NM_032656:335
GAAGAAAGTGCTGCAGAAAATCTTAGAACA
>NM_032656:340
AAGTGCTGCAGAAAATCTTAGAACAGAAGG
>NM_032656:428
AGCTGAGATGAGACTCTTTTATACCACTTC
>NM_032656:419
GGCTTCCGAAGCTGAGATGAGACTCTTTTA
>NM_032656:1130
GGAGACCAGAATCAAGTTCATGACGGATGG
>NM_032656:341
AGTGCTGCAGAAAATCTTAGAACAGAAGGA
>NM_001316938:1810
TATGCTCATAAAAGTGCTCAATTATATTTT
>NM_001316938:1378
GACTTGAGGAAACTGAAAGCCCCAGGTTGA
>NM_001316938:1388
AACTGAAAGCCCCAGGTTGAGAGAACAGAG
>NM_001316938:1720
CACCCACAAGCCTATACACCATTTATATAC
>NM_001316938:1519
GGATGATCATAGCTACCTCACGGTTACATT
>NM_001316938:1525
TCATAGCTACCTCACGGTTACATTGCAAAG
>NM_001316938:1729
GCCTATACACCATTTATATACCTACACGCA
>NM_001316938:1530
GCTACCTCACGGTTACATTGCAAAGCCTTA
>NM_001316938:1534
CCTCACGGTTACATTGCAAAGCCTTACTCT
>NM_015353:1064
GAACAGATCTTTACAACAGCAGCTGGGCTG
>NM_015353:2378
TCTGTAGCATAGCATAGAACCCGGTATACA
>NM_015353:1061
TTAGAACAGATCTTTACAACAGCAGCTGGG
>NM_015353:2277
ATGACTGCAGACTGTGCCAAATGTCTTTTG
>NM_015353:712
TTCCTCTGTGTTGTCTCCAGAGAACTAAAT
>NM_015353:702
TCAGGCAGAATTCCTCTGTGTTGTCTCCAG
>NM_015353:699
GGATCAGGCAGAATTCCTCTGTGTTGTCTC
>NM_015353:665
TCAGCATCGGATCTTCCTATAACTACGGCA
>NM_015353:2436
CACACCTATGCGCCACATTTTACAGCTGTA
>NM_015353:1334
GGTTTTAGGTAAAGCATAGAGTTGCCAGAG
>NM_014916:1307
TATCTGGTCTCTGGGTGTGACACTTTGGGA
>NM_014916:7080
GCCTCGAGTACATTTATTAACCTTTTGGGG
>NM_014916:2346
GAGTCAGTCATAACAGGCCACTTTGAGAAA
>NM_014916:2671
ACGTAAGCACAAAGGGTGACGATACAGATG
>NM_014916:8402
GGTTGGGCTTCTGTTAGAGTGGCTTCAAAA
>NM_014916:1298
GTATAGTAATATCTGGTCTCTGGGTGTGAC
>NM_014916:4611
ACAAGTAACCTGCTCAGCTCCAAGCCTTCT
>NM_014916:2639
AAATAAGCCAGGCTTGTCTTTGTTGCAGGA
>NM_014916:8251
TTCCTGTTTCCCGAAATAAGGTATTTGTAG
>NM_014916:3821
CAACTCCAGTGACCTGGAATTAAGAGCCAC
>NM_138699:1158
AGGAATATGGCCTATACAGTACGTACGCTG
>NM_138699:1657
ACAACTTTGTTATAATACAGTCTCTGCCAC
>NM_138699:1810
GACTCCACAGAGACTAAAATCAGAGCTCTG
>NM_138699:767
ATGTTGTTACGAGATTGGAGCGTTTGCGAT
>NM_138699:863
TATCAAGCTCAAAATTTATGTTGTGATGAT
>NM_138699:895
ATTTCTCCCACTTGTACTTTAGGTGGCCAA
>NM_138699:776
CGAGATTGGAGCGTTTGCGATGACCTTCCT
>NM_138699:1669
TAATACAGTCTCTGCCACAGATGCATGTGA
>NM_138699:862
ATATCAAGCTCAAAATTTATGTTGTGATGA
>NM_138699:1602
GCAACCTACAATTGGGATGAGTTCTAGGTA
>NM_001172437:3886
ACCACTTCAAAAGGATCAGAATCCACGTAA
>NM_001172437:2962
TAGGCTGCCAAATTTGCTGTTTAACATTTA
>NM_001172437:2198
ATTACTCCAACGATTGCACCTAATGGAGCC
>NM_001172437:2178
GAAATGTAAAAGATGGGCTAATTACTCCAA
>NM_001172437:2334
ATTTAGAAGACCAAGCACACCTGGCAACGT
>NM_001172437:2181
ATGTAAAAGATGGGCTAATTACTCCAACGA
>NM_001172437:4296
TGGTGTATATCTCAAATTGCCTGACATGAA
>NM_001172437:3342
AGACTATGTCTTCACATCATGGTGCAAATC
>NM_001172437:3411
CCATCATCATGCCATGATGGCTTCCACAAA
>NM_001172437:3881
TGGTAACCACTTCAAAAGGATCAGAATCCA
>NM_017841:403
GCCCCAGAAATATTTGAAAATGAAGTCATG
>NM_017841:329
ACCTCTATGACCGCCTGATTAACGAGCCTA
>NM_017841:678
TACATGTAAATGCACAATGTGACTCATTCT
>NM_017841:318
AAAGCAGCTGAACCTCTATGACCGCCTGAT
>NM_017841:362
ATGACTGGGATATTTACTACTGGGCCACAG
>NM_017841:687
ATGCACAATGTGACTCATTCTCATACTTTT
>NM_017841:336
TGACCGCCTGATTAACGAGCCTAGTAATGA
>NM_017841:372
TATTTACTACTGGGCCACAGAAGCTAAACC
>NM_017841:118
CGCTTCTACAGAGGTGACAGCCCAACAGAT
>NM_017841:101
GTGTGACATCATTCAGACGCTTCTACAGAG
>NR_024279:2532
GACGTTGGTTTTCATTGGCTGGCCATTAAG
>NR_024279:2528
ATGAGACGTTGGTTTTCATTGGCTGGCCAT
>NR_024279:2529
TGAGACGTTGGTTTTCATTGGCTGGCCATT
>NR_024279:2600
GCCCATTATTTATATCGGAGCCATAAACTT
>NR_024279:2557
TTAAGCACGCACTGCGCAACTGTTTTCCAG
>NR_024279:2598
TAGCCCATTATTTATATCGGAGCCATAAAC
>NM_012288:6094
GAACTGTTCGAGCTCCTAATTCAGTGTTAC
>NM_012288:500
GCTGGTCGTCTTTCATTTCACCTCGGTGAT
>NM_012288:6772
AGTGTCTGTTTTCTACTCTAGCCTGTTCAT
>NM_012288:3202
CCCGTGGTTGCTTTTGATTACCCTTAGGAA
>NM_012288:487
ATGAATCTGGACAGCTGGTCGTCTTTCATT
>NM_012288:3100
TAGATAAATTTTAGCTTCCCAGTAACTGAG
>NM_012288:478
GCAAGTTCAATGAATCTGGACAGCTGGTCG
>NM_012288:2183
GCAGTTCATATACCTGCCTGAGATAGGCTG
>NM_012288:3124
ACTGAGGGATTTGTTTCCTAACGCCATTGG
>NM_012288:6646
CAGATTTGAGTGTTCATGTGATGAGACTGT
>NM_018052:3020
CGTAGGCACCAGCACAAAGATCTGAATGAT
>NM_018052:1840
TAAGTTCATGATCAACCTTCTCAAGAGATT
>NM_018052:958
AATGTGTGAGGTTGTTCTTGGAGAATTCTT
>NM_018052:1020
AGTTTGCTGAGATGGCCAACATCCTGGTGA
>NM_018052:1828
TTCTTACTTTTATAAGTTCATGATCAACCT
>NM_018052:763
CAAGTTTGACCTGGTGAGCTTCATCCCCTT
>NM_018052:1843
GTTCATGATCAACCTTCTCAAGAGATTCAG
>NM_018052:991
AGAAATTAAGAAGAACCCCTCCAGTGTGAA
>NM_018052:1842
AGTTCATGATCAACCTTCTCAAGAGATTCA
>NM_018052:994
AATTAAGAAGAACCCCTCCAGTGTGAAGTT
>NM_001354729:3123
GATACTCTTCTGCCTCCTAGACCTGTTCTT
>NM_001354729:1962
AGCGGCATCTCCTGAAATATGAGGCCATCT
>NM_001354729:1086
CCAAACCAAAGACCAGCAAAGGAACCAAAC
>NM_001354729:1538
AGAGGCAAGAAAATGTGCAGCGATGGTGAG
>NM_001354729:1539
GAGGCAAGAAAATGTGCAGCGATGGTGAGA
>NM_001354729:998
GCAAAGGGAAAGAAACCTTCCAAGGAAAGA
>NM_001354729:1106
GGAACCAAACAAGAGGAAACCTTTGCTAAG
>NM_001354729:3421
AGTAACATTTTGTGGTGACAGAAGCCTAAA
>NM_001354729:1546
GAAAATGTGCAGCGATGGTGAGAAGGCAGA
>NM_001354729:1863
GGGAGAAGAAAGAAGACTTGGAGTTTCAGG

In [319]:
print(neg_down_probe_fasta)

>NM_032375:1971
ATTGGCTCAAATCCTGTAAAGGGCTTGACC
>NM_032375:459
ACGAGCACCGATTTCCTCTACTTTTGTCGA
>NM_001170629:3089
ACAAGTTTGACGCTCTGATCACCACTTTTG
>NM_001170629:1933
CTCAACACCATCACTCCTGTAGTGGGTAAG
>NM_001170629:3102
TCTGATCACCACTTTTGAGATGATTTTGTC
>NM_001170629:4064
GTCATCGAATTGGGCAGAGCAAAGCTGTGA
>NM_001170629:2223
GCAGTTCTTTGTGGAGAATCCCAGTGAAGA
>NM_001170629:3376
ACAGAGGAACAGGTTCAAAAGCTACAGGCC
>NM_001170629:7132
CAGAAGCACAAGTTGATGGCGAATGGAGTA
>NM_001170629:2531
AGTCTCACAGTATTGACAAGGACAATGGGG
>NM_001170629:3836
ATTATTTAATCCAGAGGAGGTACTTATATG
>NM_001170629:3718
ATGGTTCGTTCAGCCGGCAAACTGGTTCTT
>NM_004854:495
AGTTCATCACGTTGACCTTTAAAGACCCAG
>NM_004854:1644
TATGACGCAGAACCCCAACTGTTACAACTT
>NM_004854:689
ATCAGAAACGTCTGCAGGGATGATGCCCTG
>NM_004854:486
TGGCTAGCAAGTTCATCACGTTGACCTTTA
>NM_004854:736
TCCTGTCTCCAAGTTTGTCCTGGACCGAAT
>NM_004854:753
TCCTGGACCGAATATTTGTCTGTGACAAGC
>NM_004854:2456
CAGCATCACAGAATTCAGTGTAGTTTATAC
>NM_004854:2039
TTGTGGAGGCAAAGCATTCTTTCTGTGACT
>NM_004854:452
GCCGCATGCTTTTGGGTGATTTTCATGTTC
>NM_004854:470
ATTTTCATGTTCATGGTGGCTAGCAAGTTC
>NM_032656:331
TCGAAGAAGGAGAAGAAGCCTCTGACCAAG
>NM_032656:329
TGTCGAAGAAGGAGAAGAAGCCTCTGACCA
>NM_032656:2245
AGGCCTGTTGAAGACTTAATCCTTCAAATG
>NM_032656:328
CTGTCGAAGAAGGAGAAGAAGCCTCTGACC
>NM_032656:335
AGAAGGAGAAGAAGCCTCTGACCAAGAAGG
>NM_032656:340
GAGAAGAAGCCTCTGACCAAGAAGGAGAAG
>NM_032656:428
TACAGAAGCTGAGTGAAGTCCAGGCTTCCG
>NM_032656:419
CAGAGATGCTACAGAAGCTGAGTGAAGTCC
>NM_032656:1130
ACCAGATCCGGTATGAAGGAAACGTGACAG
>NM_032656:341
AGAAGAAGCCTCTGACCAAGAAGGAGAAGA
>NM_001316938:1810
AGGCGATGCAGACTCGCGATTCAATGATCG
>NM_001316938:1378
TGAGCAGCACCTTGAAGAGGGCAGATAATC
>NM_001316938:1388
CTTGAAGAGGGCAGATAATCAGACTTGAGG
>NM_001316938:1720
GAGTACCCAAGAAGGACTGTCTATGCATGC
>NM_001316938:1519
TGGGAAGCCTAGTTCCCACATCTGGAAATA
>NM_001316938:1525
GCCTAGTTCCCACATCTGGAAATAAGGATG
>NM_001316938:1729
AGAAGGACTGTCTATGCATGCACACCCACA
>NM_001316938:1530
GTTCCCACATCTGGAAATAAGGATGATCAT
>NM_001316938:1534
CCACATCTGGAAATAAGGATGATCATAGCT
>NM_015353:1064
AAACCTGCTTTCATTTGCTTAGCCAGTATT
>NM_015353:2378
CTAGGACCCTCAGTCTCCTTGTTTCTCTGT
>NM_015353:1061
CAGAAACCTGCTTTCATTTGCTTAGCCAGT
>NM_015353:2277
CCAAGGTACGTCTGGGTAGTAGTTTCTGGA
>NM_015353:712
CTATAACTACGGCAATGAGGATCAGGCAGA
>NM_015353:702
TCGGATCTTCCTATAACTACGGCAATGAGG
>NM_015353:699
GCATCGGATCTTCCTATAACTACGGCAATG
>NM_015353:665
ATGTCCGACGGCTGGAAATTCGAACAGCTC
>NM_015353:2436
ACAGGGGTTTCTGCTGACACATCAACGTCT
>NM_015353:1334
AAAGGGTTCTAGCTGCAGTTTGTCGAATTG
>NM_014916:1307
TGCTAACTGCAGATCAGACTAAGTATAGTA
>NM_014916:7080
ATGGAATCTGTCGTCGTCTTATACAGTGTC
>NM_014916:2346
CACTTTAAGTTCCAGTTTGGATAACCCCAA
>NM_014916:2671
AATAAGCCAGGCTTGTCTTTGTTGCAGGAA
>NM_014916:8402
TTCAGAAGTGAACCAAGGGTTAGACGCCAG
>NM_014916:1298
AAGACAGACTGCTAACTGCAGATCAGACTA
>NM_014916:4611
CTTCTCCCCAGATCCTTTTATGTCAAAGAC
>NM_014916:2639
ACTCTTTAGATACTGAGCTTCAGTTTGCTG
>NM_014916:8251
TGTAAAAGGCCTTTCCAAACCCCTCCTTTT
>NM_014916:3821
AGCCAGATGAAAGTTGTCTGTCTGCTTTGC
>NM_138699:1158
AAAGACAGCTTTTCATTAATGTCCCACGTA
>NM_138699:1657
TAGGTACATGTGTTTGCTGACTTTGGGGTA
>NM_138699:1810
GATGATGACTAGCCTAGGTCATCAGAGCCC
>NM_138699:767
TGAAGCGGAGGTACATGCTGGAAACGTGTG
>NM_138699:863
GTTGGGTTTGTTTGACTCCCGGATATGAGA
>NM_138699:895
ATCAAGCTCAAAATTTATGTTGTGATGATG
>NM_138699:776
GGTACATGCTGGAAACGTGTGAATGTTGTT
>NM_138699:1669
TTTGCTGACTTTGGGGTAAACAACTTTGTT
>NM_138699:862
GGTTGGGTTTGTTTGACTCCCGGATATGAG
>NM_138699:1602
ACTGGTGCACATCGTGTAACCTGTCTGGTG
>NM_001172437:3886
TCCTTAGTGAGCTCCACATTACTTGATGGT
>NM_001172437:2962
CCTGCCAAAACCTCCATCACCATCTAAATT
>NM_001172437:2198
TTTTGTGGCAAGAAATGTAAAAGATGGGCT
>NM_001172437:2178
GAAATGGCAGCTCTTCGAGATTTTGTGGCA
>NM_001172437:2334
CAGAATCAGTATCCTCGCCTATCTATTCCA
>NM_001172437:2181
ATGGCAGCTCTTCGAGATTTTGTGGCAAGA
>NM_001172437:4296
CAAAGCACAGTTTGAGCAGTAGAAAACAAC
>NM_001172437:3342
AGTGCTCTCTCAGATGGACTCTTGCATGTT
>NM_001172437:3411
CCAATGACTCCGGCTTTGACACAACACCTT
>NM_001172437:3881
GGACTTCCTTAGTGAGCTCCACATTACTTG
>NM_017841:403
TATTTACTACTGGGCCACAGAAGCTAAACC
>NM_017841:329
CATCTGCAGCACATGACAGAAAAGCAGCTG
>NM_017841:678
CAAGTGATGGACATAACCCTCTCCTAGGAC
>NM_017841:318
TTGCTAAAGAACATCTGCAGCACATGACAG
>NM_017841:362
CTCTATGACCGCCTGATTAACGAGCCTAGT
>NM_017841:687
GACATAACCCTCTCCTAGGACATACATGTA
>NM_017841:336
AGCACATGACAGAAAAGCAGCTGAACCTCT
>NM_017841:372
GCCTGATTAACGAGCCTAGTAATGACTGGG
>NM_017841:118
GTCTCCTTTGCTCAGTGTGACATCATTCAG
>NM_017841:101
TCAAGGCACAGCCTATTGTCTCCTTTGCTC
>NR_024279:2532
CCTTGACGTGCTGAAAGACGGAGTAGAATG
>NR_024279:2528
ATGTCCTTGACGTGCTGAAAGACGGAGTAG
>NR_024279:2529
TGTCCTTGACGTGCTGAAAGACGGAGTAGA
>NR_024279:2600
TGCGCAACTGTTTTCCAGATACGGGTTTAT
>NR_024279:2557
GAATGAGACGTTGGTTTTCATTGGCTGGCC
>NR_024279:2598
ACTGCGCAACTGTTTTCCAGATACGGGTTT
>NM_012288:6094
CACATAAACACATACATGTCTGACTGTTGC
>NM_012288:500
TCAAACACAGCAAGTTCAATGAATCTGGAC
>NM_012288:6772
CCTGAGCAACTGATAATGCAAATGTGGACA
>NM_012288:3202
TACGATAAGGTTGCAGAAATGGGAAGAGCT
>NM_012288:487
CATCTCTCCAAAGTCAAACACAGCAAGTTC
>NM_012288:3100
GCAACTCCCCTTCTCCAAGTCACTTACATC
>NM_012288:478
AAACGGCTTCATCTCTCCAAAGTCAAACAC
>NM_012288:2183
CATTCACAAGCATTCAAAACCAAACCAAAC
>NM_012288:3124
TACATCATAGATAAATTTTAGCTTCCCAGT
>NM_012288:6646
AGTAAATATAATACCGCTGTTTCCTTGGGT
>NM_018052:3020
GTGTGTGTGTGTGTGTGTGTACTTGTATGC
>NM_018052:1840
CTTCAACTCCCACCATGAATTCTTACTTTT
>NM_018052:958
TCCTGGGTGACAATGGCAAAGAGATTCGCA
>NM_018052:1020
AAAGAAATTAAGAAGAACCCCTCCAGTGTG
>NM_018052:1828
TAGAATGTTCTCCTTCAACTCCCACCATGA
>NM_018052:763
GCCTTTTAAAGGACATTGTGACTGAGAGCA
>NM_018052:1843
CAACTCCCACCATGAATTCTTACTTTTATA
>NM_018052:991
TGTGTGAGGTTGTTCTTGGAGAATTCTTAA
>NM_018052:1842
TCAACTCCCACCATGAATTCTTACTTTTAT
>NM_018052:994
GTGAGGTTGTTCTTGGAGAATTCTTAAAAG
>NM_001354729:3123
ACCCTTTGAGCTACAGAACACTTTGCTAGG
>NM_001354729:1962
TTATATAAGAACCACCCTCTGTATGCCCTG
>NM_001354729:1086
GAAACTTCCAGCCAAGTTCTAGAAAACCAC
>NM_001354729:1538
AGCGGCATCCTCAAGCTCTTCAAGCAGTAA
>NM_001354729:1539
GCGGCATCCTCAAGCTCTTCAAGCAGTAAA
>NM_001354729:998
TCTACAGCCAATTCCTCTGAAGTCAGCAAC
>NM_001354729:1106
AGAAAACCACACCAAACCAAAGACCAGCAA
>NM_001354729:3421
TACAGGTCATCTGCTGGGATCTAGTTTTCC
>NM_001354729:1546
CCTCAAGCTCTTCAAGCAGTAAAAGAGGCA
>NM_001354729:1863
TTGAGACCATACCAGAGCCCATTTATGGAC

In [321]:
blast_columns = ["qseqid", "sseqid", "pident", "length", "mismatch", "gapopen", "qstart", "qend", "sstart", "send", "evalue", "bitscore"]

up_blast_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/select/blast_neg_up_hits_211024.csv",names=blast_columns)
down_blast_df = pd.read_csv("/extdata4/baeklab/Hyeonseo/m6A/select/blast_neg_down_hits_211024.csv", names=blast_columns)

up_blast_df["qstrand"] = up_blast_df["qstart"] < up_blast_df["qend"]
up_blast_df["sstrand"] = up_blast_df["sstart"] < up_blast_df["send"]
up_blast_df = up_blast_df[up_blast_df["qstrand"] & up_blast_df["sstrand"]]

down_blast_df["qstrand"] = down_blast_df["qstart"] < down_blast_df["qend"]
down_blast_df["sstrand"] = down_blast_df["sstart"] < down_blast_df["send"]
down_blast_df = down_blast_df[down_blast_df["qstrand"] & down_blast_df["sstrand"]]

up_blast_df = up_blast_df[(up_blast_df["length"] >= 20)]
down_blast_df = down_blast_df[(down_blast_df["length"] >= 20)]
up_blast_df = up_blast_df[~((up_blast_df["length"] == 30) & (up_blast_df["pident"] == 100))]
down_blast_df = down_blast_df[~((down_blast_df["length"] == 30) & (down_blast_df["pident"] == 100))]

up_count = up_blast_df.groupby("qseqid").count()["sseqid"]
up_count = up_count.reset_index()
up_count = up_count.rename(columns={"sseqid": "up_count", "qseqid": "label_id"})
down_count = down_blast_df.groupby("qseqid").count()["sseqid"]
down_count = down_count.reset_index()
down_count = down_count.rename(columns={"sseqid": "down_count", "qseqid": "label_id"})

In [322]:
neg_blast_df = neg_site_df.merge(up_count, on="label_id", how="left").merge(down_count, on="label_id", how="left")
neg_blast_df.fillna(0, inplace=True)
neg_blast_df["blast_hit"] = neg_blast_df["up_count"] + neg_blast_df["down_count"]
neg_blast_df = neg_blast_df[(neg_blast_df["blast_hit"] == 0)]
neg_blast_df

,label_id,gene_id,log_pm6a,dom,dom_label,label,count_dom,count_all,5mer,drach,...,down_probe_30,has_repeat,tm_max,mfe,gc,up_probe,down_probe,up_count,down_count,blast_hit
0,NM_032375:1971,AKT1S1,-0.0,0.029412,0.0,0,408,429,CCAGT,False,...,GGTCAAGCCCTTTACAGGATTTGAGCCAATCAGAGGCTGAGTCGCT...,False,73.560597,-23.299999,0.485149,GTCTCTACATAGTCACCGTCCGCTTTTCCT,ATTGGCTCAAATCCTGTAAAGGGCTTGACC,0.0,0.0,0.0
3,NM_001170629:1933,CHD8,0.0,0.000000,0.0,0,97,98,AGAAG,False,...,CTTACCCACTACAGGAGTGATGGTGTTGAGCAGAGGCTGAGTCGCT...,False,73.867675,-24.900000,0.425743,AGAGAAAACGTAATACCTCATCTGATAATT,CTCAACACCATCACTCCTGTAGTGGGTAAG,0.0,0.0,0.0
8,NM_001170629:7132,CHD8,-0.0,0.005464,0.0,0,183,192,TAATG,False,...,TACTCCATTCGCCATCAACTTGTGCTTCTGCAGAGGCTGAGTCGCT...,False,73.923924,-19.299999,0.415842,TGGGAGATGGACATCCACTGTTTCATAAGA,CAGAAGCACAAGTTGATGGCGAATGGAGTA,0.0,0.0,0.0
10,NM_001170629:3836,CHD8,0.0,0.000000,0.0,0,126,129,TGAAC,False,...,CATATAAGTACCTCCTCTGGATTAAATAATCAGAGGCTGAGTCGCT...,False,74.914789,-26.299999,0.465347,ACGTATTGATGGGCGAGTTAGAGGCAACCT,ATTATTTAATCCAGAGGAGGTACTTATATG,0.0,0.0,0.0
11,NM_001170629:3718,CHD8,-0.0,0.007937,0.0,0,126,131,TTATT,False,...,AAGAACCAGTTTGCCGGCTGAACGAACCATCAGAGGCTGAGTCGCT...,False,74.937033,-20.200001,0.465347,TTGACAAGTTGCTTCCAAAGCTTAAAGCTG,ATGGTTCGTTCAGCCGGCAAACTGGTTCTT,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,NM_001354729:1086,XPC,0.0,0.000000,0.0,0,20,20,ACACC,False,...,GTGGTTTTCTAGAACTTGGCTGGAAGTTTCCAGAGGCTGAGTCGCT...,False,74.295792,-19.600000,0.475248,CCAAACCAAAGACCAGCAAAGGAACCAAAC,GAAACTTCCAGCCAAGTTCTAGAAAACCAC,0.0,0.0,0.0
120,NM_001354729:1538,XPC,0.0,0.000000,0.0,0,25,26,AAAAG,False,...,TTACTGCTTGAAGAGCTTGAGGATGCCGCTCAGAGGCTGAGTCGCT...,False,74.621176,-17.500000,0.485149,AGAGGCAAGAAAATGTGCAGCGATGGTGAG,AGCGGCATCCTCAAGCTCTTCAAGCAGTAA,0.0,0.0,0.0
121,NM_001354729:1539,XPC,0.0,0.000000,0.0,0,26,26,AAAGA,False,...,TTTACTGCTTGAAGAGCTTGAGGATGCCGCCAGAGGCTGAGTCGCT...,False,74.701489,-17.500000,0.475248,GAGGCAAGAAAATGTGCAGCGATGGTGAGA,GCGGCATCCTCAAGCTCTTCAAGCAGTAAA,0.0,0.0,0.0
122,NM_001354729:998,XPC,0.0,0.000000,0.0,0,20,20,ACAGC,False,...,GTTGCTGACTTCAGAGGAATTGGCTGTAGACAGAGGCTGAGTCGCT...,False,73.496918,-22.200001,0.495050,GCAAAGGGAAAGAAACCTTCCAAGGAAAGA,TCTACAGCCAATTCCTCTGAAGTCAGCAAC,0.0,0.0,0.0
124,NM_001354729:3421,XPC,0.0,0.000000,0.0,0,38,39,CCAAG,False,...,GGAAAACTAGATCCCAGCAGATGACCTGTACAGAGGCTGAGTCGCT...,False,72.645052,-17.200001,0.415842,AGTAACATTTTGTGGTGACAGAAGCCTAAA,TACAGGTCATCTGCTGGGATCTAGTTTTCC,0.0,0.0,0.0

In [323]:
neg_blast_df["gene_id"].value_counts()

gene_id
SDHAF2      8
LOC93622    8
PEG10       7
LMTK2       7
CHST10      7
TRAM2       7
XPC         7
KCTD2       6
SPEN-AS1    6
VAC14       6
CHD8        4
DHX37       3
FBXL12      2
AKT1S1      1
Name: count, dtype: int64

In [122]:
neg_blast_df.drop(columns=["up_probe_30", "down_probe_30", "seq"], inplace=True)
neg_blast_df.to_csv("/extdata4/baeklab/Hyeonseo/m6A/select/neg_blast.tsv", sep = "\t")

In [324]:
print(pos_site_df)

             label_id   gene_id  log_pm6a       dom  dom_label  label  \
1       NM_032375:481    AKT1S1  2.408016  0.666667   0.650000     -1
11     NM_004854:1260    CHST10  2.654569  0.611111   0.684800     -1
14     NM_032656:3836     DHX37  2.392832  0.581633   0.559930      1
30     NM_015353:1241     KCTD2  3.230837  0.990000   0.962119      1
34     NM_014916:6647     LMTK2  2.626910  0.821782   0.838346     -1
35     NM_138699:1421  LOC93622  2.395810  0.714286   0.000000     -3
52      NM_017841:583    SDHAF2  2.866309  0.905325   0.918439      1
59     NR_024279:2534  SPEN-AS1  2.452236  0.691803   0.000000     -3
65     NM_012288:1898     TRAM2  3.093027  0.880597   0.961576      1
4    NM_001170629:536      CHD8  1.165228  0.746835   0.000000      0
9   NM_001316938:1630    FBXL12  1.174176  0.250000   0.410789      1
24   NM_001172437:509     PEG10  0.808276  0.148148   0.000000     -3
36     NM_018052:1605     VAC14  0.893817  0.503704   0.000000     -1
38  NM_001354729:1390       XPC  1.221978  0.192308   0.213089     -1

    count_dom  count_all   5mer  drach  ...  transcript_length  m6a_density  \
1          93         96  GGACG  False  ...             2447.0     0.001226
11        198        201  GGACG  False  ...             2854.0     0.006307
14        196        202  GGACG  False  ...             4559.0     0.000658
30        100        100  GGACG  False  ...             3657.0     0.004649
34        101        103  GGACG  False  ...             8974.0     0.003120
35        224        226  GGACG  False  ...             1973.0     0.004562
52        169        170  GGACG  False  ...             1186.0     0.004216
59        305        310  AGACG  False  ...             2732.0     0.002928
65         67         69  GGACG  False  ...             7047.0     0.001561
4          79         84  AGAAC  False  ...             8467.0     0.002362
9          20         22  GGACG  False  ...             1917.0     0.003130
24         27         28  GGACG  False  ...             6639.0     0.003615
36        135        151  AGACG  False  ...             3096.0     0.000646
38         26         26  GGATT  False  ...             3632.0     0.001652

     pos                                        up_probe_30  \
1    481  TAGCCAGTACCGTAGTGCGTGCCACAGTAAACGAAGGCAAGCGACC...
11  1260  TAGCCAGTACCGTAGTGCGTGCCAGCCTCTTTTAAGATGTATGGGG...
14  3836  TAGCCAGTACCGTAGTGCGTGAGTCCAAAGAGCACACTGAACAGAA...
30  1241  TAGCCAGTACCGTAGTGCGTGAGGGACGGTGTTCCGAAGCAGCTGC...
34  6647  TAGCCAGTACCGTAGTGCGTGAGGTCATTTGCTGCGCACTCTCTGG...
35  1421  TAGCCAGTACCGTAGTGCGTGCCACACACTGCCACTCTTCAAGACC...
52   583  TAGCCAGTACCGTAGTGCGTGGCATCTAAGAAGCCGGAAGCAAGGC...
59  2534  TAGCCAGTACCGTAGTGCGTGTGCTTAATGGCCAGCCAATGAAAAC...
65  1898  TAGCCAGTACCGTAGTGCGTGCACACCATCCTTCTGGATTGAGTTG...
4    536  TAGCCAGTACCGTAGTGCGTGGGAGCTGGAGCTGTGGATTCTTTGG...
9   1630  TAGCCAGTACCGTAGTGCGTGTGAGTCTTAACCCCACCCCTTCTTC...
24   509  TAGCCAGTACCGTAGTGCGTGCTTAAGTTGTTGATCTCTTCAGAGA...
36  1605  TAGCCAGTACCGTAGTGCGTGGGATCACCTCATCCGATTCATCCGA...
38  1390  TAGCCAGTACCGTAGTGCGTGTTCCTCTGCTTTGGAGGGCCAGGTT...

                                        down_probe_30     tm_max  has_repeat  \
1   CCCTGACCCACAATAAACTTCTTCGACAAACAGAGGCTGAGTCGCT...  76.384300       False
11  CCTCCAGGGTCTCGTGGTGTCCAATCACACCAGAGGCTGAGTCGCT...  77.744087       False
14  CCAGCACGTGAGATGAAATCATCATCCACCCAGAGGCTGAGTCGCT...  73.755037       False
30  CCATTGTGGCACACATAGGGTGAAACCATGCAGAGGCTGAGTCGCT...  77.518362       False
34  CCGCCTGCATTTTGCACTAGGACTCAACTTCAGAGGCTGAGTCGCT...  76.023264       False
35  CCACTGGGCCTTCTTAATCTCATCCAAAGTCAGAGGCTGAGTCGCT...  76.486079       False
52  CCATCATAAGTAGTTACCATCCACAGACTGCAGAGGCTGAGTCGCT...  75.742049       False
59  CTCATTCTACTCCGTCTTTCAGCACGTCAACAGAGGCTGAGTCGCT...  74.057431       False
65  CCCAAAGCCAAATGCCTTGGCATTTACAACCAGAGGCTGAGTCGCT...  74.608364       False
4   CTGTGGGAGCTGTTTCCTCTGGTGGAGGGACAGAGGCTGAGTCGCT...  77.785008       False
9   CCTGTTCCTGAAGACGACCATGAAGGTGACCAGAGGCTGAGTCGCT...  77.191770       False
24  CCCTTCTTCGTTCGGTCATGTTGGGGACACCAGAGGCTGAGTCGCT...  76.897641       False
36  CTGCAGTAGGATGGGAAAGAGGCTGTCCGTCAGAGGCTGAGTCGCT...  76.223088       False
38  CCTCATCAGAGGGATCAGAGGCTTCTCCACCAGAGGCTGAGTCGCT...  77.984993       False

    blast_hit        mfe        gc
1         0.0 -25.000000  0.475248
11        0.0 -26.700001  0.504950
14        0.0 -28.500000  0.435644
30        0.0 -22.700001  0.574257
34        0.0 -27.200001  0.554455
35        0.0 -23.299999  0.495050
52        0.0 -26.400000  0.564356
59        0.0 -25.799999  0.504950
65        0.0 -32.500000  0.534653
4         0.0 -16.500000  0.495050
9         0.0 -33.700001  0.554455
24        0.0 -20.700001  0.504950
36        0.0 -32.299999  0.554455
38        0.0 -33.099998  0.564356

[14 rows x 26 columns]

In [325]:
print(neg_blast_df)

              label_id gene_id  log_pm6a       dom  dom_label  label  \
0       NM_032375:1971  AKT1S1      -0.0  0.029412        0.0      0
3    NM_001170629:1933    CHD8       0.0  0.000000        0.0      0
8    NM_001170629:7132    CHD8      -0.0  0.005464        0.0      0
10   NM_001170629:3836    CHD8       0.0  0.000000        0.0      0
11   NM_001170629:3718    CHD8      -0.0  0.007937        0.0      0
..                 ...     ...       ...       ...        ...    ...
119  NM_001354729:1086     XPC       0.0  0.000000        0.0      0
120  NM_001354729:1538     XPC       0.0  0.000000        0.0      0
121  NM_001354729:1539     XPC       0.0  0.000000        0.0      0
122   NM_001354729:998     XPC       0.0  0.000000        0.0      0
124  NM_001354729:3421     XPC       0.0  0.000000        0.0      0

     count_dom  count_all   5mer  drach  ...  \
0          408        429  CCAGT  False  ...
3           97         98  AGAAG  False  ...
8          183        192  TAATG  False  ...
10         126        129  TGAAC  False  ...
11         126        131  TTATT  False  ...
..         ...        ...    ...    ...  ...
119         20         20  ACACC  False  ...
120         25         26  AAAAG  False  ...
121         26         26  AAAGA  False  ...
122         20         20  ACAGC  False  ...
124         38         39  CCAAG  False  ...

                                         down_probe_30  has_repeat     tm_max  \
0    GGTCAAGCCCTTTACAGGATTTGAGCCAATCAGAGGCTGAGTCGCT...       False  73.560597
3    CTTACCCACTACAGGAGTGATGGTGTTGAGCAGAGGCTGAGTCGCT...       False  73.867675
8    TACTCCATTCGCCATCAACTTGTGCTTCTGCAGAGGCTGAGTCGCT...       False  73.923924
10   CATATAAGTACCTCCTCTGGATTAAATAATCAGAGGCTGAGTCGCT...       False  74.914789
11   AAGAACCAGTTTGCCGGCTGAACGAACCATCAGAGGCTGAGTCGCT...       False  74.937033
..                                                 ...         ...        ...
119  GTGGTTTTCTAGAACTTGGCTGGAAGTTTCCAGAGGCTGAGTCGCT...       False  74.295792
120  TTACTGCTTGAAGAGCTTGAGGATGCCGCTCAGAGGCTGAGTCGCT...       False  74.621176
121  TTTACTGCTTGAAGAGCTTGAGGATGCCGCCAGAGGCTGAGTCGCT...       False  74.701489
122  GTTGCTGACTTCAGAGGAATTGGCTGTAGACAGAGGCTGAGTCGCT...       False  73.496918
124  GGAAAACTAGATCCCAGCAGATGACCTGTACAGAGGCTGAGTCGCT...       False  72.645052

           mfe        gc                        up_probe  \
0   -23.299999  0.485149  GTCTCTACATAGTCACCGTCCGCTTTTCCT
3   -24.900000  0.425743  AGAGAAAACGTAATACCTCATCTGATAATT
8   -19.299999  0.415842  TGGGAGATGGACATCCACTGTTTCATAAGA
10  -26.299999  0.465347  ACGTATTGATGGGCGAGTTAGAGGCAACCT
11  -20.200001  0.465347  TTGACAAGTTGCTTCCAAAGCTTAAAGCTG
..         ...       ...                             ...
119 -19.600000  0.475248  CCAAACCAAAGACCAGCAAAGGAACCAAAC
120 -17.500000  0.485149  AGAGGCAAGAAAATGTGCAGCGATGGTGAG
121 -17.500000  0.475248  GAGGCAAGAAAATGTGCAGCGATGGTGAGA
122 -22.200001  0.495050  GCAAAGGGAAAGAAACCTTCCAAGGAAAGA
124 -17.200001  0.415842  AGTAACATTTTGTGGTGACAGAAGCCTAAA

                         down_probe up_count  down_count  blast_hit
0    ATTGGCTCAAATCCTGTAAAGGGCTTGACC      0.0         0.0        0.0
3    CTCAACACCATCACTCCTGTAGTGGGTAAG      0.0         0.0        0.0
8    CAGAAGCACAAGTTGATGGCGAATGGAGTA      0.0         0.0        0.0
10   ATTATTTAATCCAGAGGAGGTACTTATATG      0.0         0.0        0.0
11   ATGGTTCGTTCAGCCGGCAAACTGGTTCTT      0.0         0.0        0.0
..                              ...      ...         ...        ...
119  GAAACTTCCAGCCAAGTTCTAGAAAACCAC      0.0         0.0        0.0
120  AGCGGCATCCTCAAGCTCTTCAAGCAGTAA      0.0         0.0        0.0
121  GCGGCATCCTCAAGCTCTTCAAGCAGTAAA      0.0         0.0        0.0
122  TCTACAGCCAATTCCTCTGAAGTCAGCAAC      0.0         0.0        0.0
124  TACAGGTCATCTGCTGGGATCTAGTTTTCC      0.0         0.0        0.0

[79 rows x 27 columns]

In [326]:
pos_site_df.to_csv("/extdata4/baeklab/Hyeonseo/m6A/select/pos_site_211024.tsv", sep="\t", index=False)
neg_blast_df.to_csv("/extdata4/baeklab/Hyeonseo/m6A/select/neg_site_211024.tsv", sep="\t", index=False)